### ISSUE TITLE
Fire length and difficulty

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#100]
_## Issue created anonymously for a user ##_
Make fires last longer and different ones

**Comment by JamStonedScones** [comment]
To expand on this a little, when we had fires before the "incident" they would take the piss to go out at the end. When it was massive and you started hosing it down it would slowly reduce at a nice rate but when it got smaller it seemed as if you where having no effect, maybe a way in which the speed that the flames extinguish could be based on the percentage of fire remaining, for example. When arriving on scene, the fire is at 100% the effect of the hose is reduces to 50, when the fire starts going down percentage wise then the hoses effect should climb slightly to give the effect that once it starts getting smaller its easier to put out


Ps I was not high when I wrote all this but you know hoe I can overthink small systems like this and add complex math in there

**Comment by Dale1987** [comment]
Yeah jam you were deffo high writing this 🤣

**Comment by JamStonedScones** [comment]
It makes sense tho, no?

**Comment by Dale1987** [comment]
Yeah it does lol

**Comment by jxckUK** [comment]
Its a good suggestion, but unfortunately that is beyond our capabilities as SmartFires is a closed source solution.

I'll send in your suggestion to London Studios though @JamStonedScones!

In terms of fire length etc. I'm going to ask @telboycafc to take a look at the configuration.

**Comment by jxckUK** [comment]
Submitted to London Studios and changes have been made to the configuration. Closing in favour of https://github.com/LondonsBlueLine/tracker/issues/107
