### ISSUE TITLE
LAS New Assets/Vehicles 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#101]
I’ve categorised these as to which role they should be useable for. These are just ones I’ve found so I’m not sure if they’re suitable or not.

Some additional uniforms found here -  https://www.gta5-mods.com/player/eup-british-paramedic-uniform

**Emergency Ambulance Crew**

https://gta5mod.net/gta-5-mods/vehicles/cars/generic-uk-renault-master-ambulance-1-0/

**Paramedic**

Generic RRV - [https://www.gta5-mods.com/vehicles/els-2015-london-ambulance-service-vw-tiguan-rrv ](https://www.gta5-mods.com/vehicles/els-2015-london-ambulance-service-vw-tiguan-rrv)

Ambulance with enterable interior - https://store.state-zero.com/products/2017-sprinter-generic-was-ambulance

Ambulance - https://www.gta5-mods.com/vehicles/2015-london-ambulance-els

**Advanced Paramedic**

Land Rover RRV - https://store.state-zero.com/products/2020-land-rover-defender-rapid-response-vehicle

BMW RRV (Skin) - 
https://www.gta5-mods.com/paintjobs/london-ambulance-service-rrv-bmw-x5-skin

https://www.gta5-mods.com/paintjobs/las-land-rover-discovery-4

https://www.gta5-mods.com/paintjobs/london-ambulance-service-skoda-octavia

**HART**

[2020 London Ambulance Service Diamond Casino Support Unit (semi-realistic)](https://unionmods.com/?p=viewfile&file=71)

https://www.gta5-mods.com/paintjobs/london-ambulance-service-mercedes-benz-sprinter-incident-response-unit 

https://www.gta5-mods.com/paintjobs/2017-london-ambulance-service-mercedes-benz-sprinter

**HEMS** 

HEMS RRV with different skins - https://www.gta5-mods.com/vehicles/2018-london-air-ambulance-skoda-octavia-vrs-estate-els 

**Command (Gold, Silver, Bronze)**

[[ELS] 2018 Land Rover Discovery - Fictional - Ambulance Officers Car](https://unionmods.com/?p=viewfile&file=414)

[[ELS] 2019 BMW 5 Series Ambulance Officer](https://unionmods.com/?p=viewfile&file=388)

**Comment by MrJC9** [comment]
**Note the first 2 currently have other Ambulance Service skins** - unsure if they can be used.

**Paramedic**
An improved Merc Ambulance that can be added alongside the current one https://unionmods.com/?p=viewfile&file=38

**HART**
https://www.gta5-mods.com/vehicles/2020-mercedes-sprinter-south-east-coast-ambulance-service-incident-support-unit-els

**Advanced Paramedic**
Generic V70 RRV (Skin with model link)
https://www.gta5-mods.com/paintjobs/british-volvo-v70-ambulance

**Comment by Dale1987** [comment]
Will Close out this as have added everything from the list possible
