### ISSUE TITLE
NPAS Helicopters

### ISSUE THREAD

**Issue by Crazycallum** [LondonsBlueLine/tracker#106]
Can I have 2 helicopter in NPAS. 

https://www.unionmods.com/?p=viewfile&file=457 - Eurocopter EC135

https://www.unionmods.com/?p=viewfile&file=468 - Eurocopter EC145

**Comment by Crazycallum** [comment]
Update on it?

**Comment by Dale1987** [comment]
Been looking at Different helicopters but cant find any with decent MPS skin
