### ISSUE TITLE
Smart Fires Spawning Rate

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#107]
**Is your feature request related to a problem? Please describe.**
When playing as LFB its quite frustrating that you never get a second to yourself, the fires spawn at such a rate that you never get time to return to station after a incident, especially if there is more than 2 people active as the division.

**Describe the solution you'd like**
Perhaps turn down the spawn rate of fires to allow the personnel to deal with an incident and return to station.

**Describe alternatives you've considered**
Remove the option that is spawns more when more are on as LFB as it gets relentless.

**Additional context**

**Comment by telboycafc** [comment]
I have tinkered with the difficulty of the fires, this will require feed back from players though to tell me weather they are lasting long enough. Also, fires will now spawn every 15 minutes. If this is too long or too short, let me know, we can tinker again.
