### ISSUE TITLE
NPAS Bug

### ISSUE THREAD

**Issue by Crazycallum** [LondonsBlueLine/tracker#109]
![image](https://user-images.githubusercontent.com/101276141/161279899-cfc3591f-4bfb-4978-9559-b9d20b8fbdc6.png)
When I go into the NPAS helicopter Garage and when I try to back out this happens

**Comment by Dale1987** [comment]
Just tried on DEV and have same issue, for the moment dont go into the garage if your not going to select NPAS

**Comment by MrJC9** [comment]
There’s a similar issue with the HEMS garage. Thought I’d mention on this because a potential fix might work for both

**Comment by jxckUK** [comment]
https://github.com/ProjectHyde/ProjectHyde/commit/2023e7b9fb7ac0dd788204465be1c3bac5d4ea3d

This has been resolved but its a limitation of the garages script. I've had to move NPAS Ground Services to be under the emergency response garage and move HEMS under the Paramedic garage.

**Comment by jxckUK** [comment]
Okay so that fix didn't work but I've spent about an hour readjusting some things, all sorted now.
