### ISSUE TITLE
A bigger fire station for roleplays

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#111]
_## Issue created anonymously for a user ##_
I think we should add a bigger fire station the only ones I could find on gta5mods is like Vinewood and sandy shores stuff. Just thought we could add this for more roleplays within the station its self and not just fires. So most of the time we can RP cooking food for the crew doing role calls within the server so RP shifts when people are online so we can do some more roleplays within the server/city

**Comment by JamStonedScones** [comment]
I was recently looking for some to buy online to replace Davis fire station. If someone can find one I'm happy to put half the money towards.

**Comment by telboycafc** [comment]
Update - Currently keeping an eye on a fire station in production by Alien modding which is still a WIP. If the station meets our standards and is what we feel a decent price range, it can deffo be looked at.

**Comment by jxckUK** [comment]
Closing in favour of https://github.com/LondonsBlueLine/tracker/issues/185
