### ISSUE TITLE
add binoculars

### ISSUE THREAD

**Issue by Rjamison21** [LondonsBlueLine/tracker#112]
for police so when they are staking out a premises or a area that is about to get raided then they can observer in more detail with the binoculars at a safe distance so they don't get seen

**Comment by jxckUK** [comment]
I'll take a look at the feasibility of this soon.

**Comment by jxckUK** [comment]
Added on /binoculars

https://github.com/ProjectHyde/ProjectHyde/commit/9e3149cbe9218910833a95b5704131f604966ffb
