### ISSUE TITLE
NPAS

### ISSUE THREAD

**Issue by Crazycallum** [LondonsBlueLine/tracker#116]
Can we get lockers in the NPAS Base so we can change uniform

**Comment by telboycafc** [comment]
I Put lockers there already, where did they go ?

**Comment by jxckUK** [comment]
> I Put lockers there already, where did they go ?

I thought this - maybe he's missed them?

**Comment by Dale1987** [comment]
No they arent they havent been since we had the messup mergeing files together to push to main

**Comment by telboycafc** [comment]
tested in dev and done, will be ready in next update.
