### ISSUE TITLE
Adjust civilian spawn points

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#117]
Any chance we can change the spawn location for the civs to spawn as there is now a fire callout that spawns inside the building. The fire is better than the spawn point.

**Comment by jxckUK** [comment]
@telboycafc - What if we start putting them inside apartments and houses? Might be a nice way to RP it a little?

**Comment by telboycafc** [comment]
Sounds good to me, will work on it.

**Comment by telboycafc** [comment]
More CIV spawn locations have been added and will be random now.
