### ISSUE TITLE
CID

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#118]
Since Covert Policing Unit has been disbanded, can I suggest that I may take the team under the wing of RTPC as I believe I have the potential to make it a used division within the LBLRP community.

**Comment by JamStonedScones** [comment]
Sorry this being the collision investigation unit within covert policing, should have made that clear. Weed

**Comment by Dale1987** [comment]
This has been Approved by Gold Command, CIU is now a Subdivision of RTPC
