### ISSUE TITLE
Teamspeak 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#119]
_## Issue created anonymously for a user ##_
I really think during operations etc we use teamspesk, LFB , Firearms , MPS all in separate channels on the teamspeak and met in one, when met want to attach us they send us a cad attachment and join the SFC , Or LFB or MPS , or ambulance etc and say their call sign and what they have been attached too.

**Comment by CalLBLRP** [comment]
-1 

Reason: We have an in-game radio for a reason, we can utilise the channels and have multiple dispatchers on at a time. 1 for main and 1 for tac ops, no need to purchase a TeamSpeak server for a ridiculous price.

**Comment by Dale1987** [comment]
This topic already was discussed between leadership team before the server was realeased. Teamspeak isnt something we want to use. Jack has spent time devolping the in game radio which can be utilised with the different channels. 

Another difficulty is for when new players join they then need to sort out teamspeak so they can join the radio etc.

**Comment by jxckUK** [comment]
Hi Calum,

Thanks for your suggestion - this is something that, as the others have discussed, has been brought up before. I just want to clarify the reasons so that any future suggestions can reference this one:

1.  TeamSpeak creates a barrier for entry, regardless of how significant. As a public server with a set up that encourages new players to jump in and get involved this is not something we'd want to introduce.
2.  TeamSpeak is an external platform with no integration in the game. When we bring out new features like we did with CAD integration, we wouldn't be able to display that information within TeamSpeak.
3. TeamSpeak requires a separate independent server, while we have the capacity to deploy this, it adds another management level we'd need to consider. It also comes with additional moderation requirements and a host of documentation to create to manage it effectively.

This stance is not likely to change in the future and the suggestion is therefore closed.
