### ISSUE TITLE
Working LFB ladder

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#121]
You see the ladder trucks try to add a script where the stands come out of the sides to raise the ladder truck and to also add a working ladder so we can control it.

**Comment by Dale1987** [comment]
This would only be possible with the correct Model, which would need purchased from Alien Mods which i believe is over £40

**Comment by WolfRanger88** [comment]
@jxckUK Inferno Ladders added to all relevant vehicles. Can this be combined with the eye script to collect from vehicle. Command is /ladder collect and /ladder store

**Comment by jxckUK** [comment]
Added to Roadmap - [PH-LFB v1](https://github.com/ProjectHyde/ProjectHyde/issues/45)
