### ISSUE TITLE
Add additional vehicles to the spike strip allocations

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#127]
**Describe the bug**
There is some certain vehicles in RTPC that you cant deploy spikes from

RTPC: Volvo V60 new
Interceptor: Audi S4
Interceptor: BMW 135i
Interceptor: BMW 540i XDrive M-Sport
Interceptor: BMW M5 F90
Panther: 330D F30
Panther: Skoda Karoq

**Comment by Dale1987** [comment]
@WolfRanger88

**Comment by Dale1987** [comment]
Il get numbers for them later

**Comment by JamStonedScones** [comment]
any updates on this?

**Comment by jxckUK** [comment]
> any updates on this?

I'll catch up with Wolf to do this tonight.

**Comment by WolfRanger88** [comment]
@Dale1987 Can I get numbers please as these appear not to be on the vehicle tracker.

**Comment by Dale1987** [comment]
@WolfRanger88  will get after work today, had no power in the flat last night, its just came back on

**Comment by Dale1987** [comment]
@WolfRanger88 every vehicle is on the tracker lol

Volvo V60 - MPS150

the other vehicles iv checked and they all seem to already have them just the detection point is a little bit behind the boot

**Comment by WolfRanger88** [comment]
I thought they were not there but when i checked the config all models had it. 

Ticket closing as spike strips available.
