### ISSUE TITLE
LAS Uniform issues & changes

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#129]
**Uniforms missing gloves**
Emergency Ambulance Crew - 1 uniform
All Paramedic Uniforms 
All Advanced Paramedic Uniforms 
HART & HEMS Uniforms 

**Clipping issue with the shirt on LAS Gold/Silver uniforms**
Shirt is currently set as drawable 178 can we get it changed to drawable 15 (as shown below) so there isn't a clipping issue with another shirt under the uniform shirt. This change needs to be made to all 3 of the LAS Gold/Silver uniforms (LAS Band A&B).
![20220407180215_1](https://user-images.githubusercontent.com/102492709/162267969-2118665c-f007-4254-b570-f552bec872b0.jpg)

**Operational uniforms for all 3 command levels (Band A&B)**
Can I get an additional Operational Uniform variant for all 3 LAS Gold/Silver uniforms with the LAS white shirt, Legs drawable 150 & Texture 3, Shoes 25. This uniform to be added alongside each of the current 3 LAS Gold/Silver uniforms as an operational variant for each (for when we attend calls)
![20220407181944_1](https://user-images.githubusercontent.com/102492709/162268030-375955ca-80db-4567-b8ad-f23535e2046d.jpg)

**Comment by telboycafc** [comment]
Done, ready for @jxckUK to merge to live.

**Comment by telboycafc** [comment]
nope, hold fire

**Comment by telboycafc** [comment]
ok, @jxckUK now you can merge. All have been fixed.
