### ISSUE TITLE
LFB alarm & additional resources

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#131]
Add the Firefighter alarm so for example when a firefighter in a building which is on fire dosen't move for more than 5 seconds, the alarm goes off which then the IC could hear and make it a Mayday as they know a firefighter is down

Maybe add water rescue trucks and eup

**Comment by Dale1987** [comment]
Have added a couple new vehicles to LFB recently, jack would need to look at adding an alarm and as for the generation rate of fires this should have already been fixed

**Comment by jxckUK** [comment]
Added to https://github.com/ProjectHyde/ProjectHyde/issues/45
