### ISSUE TITLE
Add an additional civ role with access to more items

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#134]
A advanced civ role given to those trusted with access to more things in game?

**Comment by Dale1987** [comment]
What do you mean by more items?

**Comment by JamStonedScones** [comment]
as in locking the vehicles garage behind that maybe, more variety of weapons, firearms? Maybe even make it so that you can only make your own ped when Adv and just choose GTA ped models?

**Comment by jxckUK** [comment]
> as in locking the vehicles garage behind that maybe, more variety of weapons, firearms? Maybe even make it so that you can only make your own ped when Adv and just choose GTA ped models?

Hmm... this one I think needs a vote from the Leadership as it has pros and cons. Submitted on 18/04.

**Comment by jxckUK** [comment]
This was approved by Leadership vote 60:40.

We'll look to add the role into Discord and attach additional armoury options etc to it shortly.

**Comment by jxckUK** [comment]
Closing this as this has been discussed and approved and will be implemented shortly. More details to follow soon.
