### ISSUE TITLE
Garage and locker re-configuration for Scorpion

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#137]
Can we get the motorcycle taken out of the RTPC garage and locker uniform too please as its ment to be locket to Scorpion, Can i also steal the other marked bike from the SEG garage as we only have 1 bike available please, thank you.

**Comment by Dale1987** [comment]
Garage Config Done

**Comment by Dale1987** [comment]
Lockers updated, Ready for push to main
