### ISSUE TITLE
Issue with HART Navara

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#138]
Can I get the 2 new Ford Ambulances added to the Defib & Stretcher script and the new Nissan Navara added to the Defib script. Also minor detail but Ford Transit is spelt wrong in the garage menu for one of the 2 new Ford Ambulances.

Also, not sure if its the design of the vehicle or a bug but when you turn on the lightbar blue lights using Q in the Navara, it turns the headlights off, if you press Q again the headlights turn on but the rear red's also turn on.

**Comment by Dale1987** [comment]
Messaged Alien mods about the issue with Headlights Turning off on 1st ELS cycle

**Comment by Dale1987** [comment]
Update: i have messaged alien mods again about the issue

**Comment by Dale1987** [comment]
this issue has been resolved and will  be pushed as part of the new els update in the future
