### ISSUE TITLE
LAS Vehicle Additions 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#139]
New LAS vehicles:

**Advanced Paramedic**
Not sure if this is already the same as the one we have (if this could added alongside the existing as this looks to be a newer model) https://unionmods.com/?p=viewfile&file=452

**HART**
https://unionmods.com/?p=viewfile&file=121

https://modification-universe.com/forums/resources/john-deere-gator-asap911-mini-pack.48/ 
**With this skin** https://unionmods.com/?p=viewfile&file=589

**Doctor/HEMS**
https://unionmods.com/?p=viewfile&file=322

**Comment by Dale1987** [comment]
None if these vehciles can be used as i have no permission to reskin them

The gator is also from abother server that is called blackshire, this cant be reskinned either. 

Every single vehicle on union mods iv been through a hundred times mate, if we could use it it would be in already

**Comment by Dale1987** [comment]
Il add more vehicles when i can, you now have 26 vehciles within LAS. Next vehicle  update will be a while away now
