### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by WolfRanger88** [LondonsBlueLine/tracker#14]
**Is your feature request related to a problem? Please describe.**
There is no way to clean a car if it gets dirty

**Describe the solution you'd like**
Working car wash facility

**Describe alternatives you've considered**
Found a script that allows use of hose to clean car.

**Additional context**
N/A

**Comment by jxckUK** [comment]
As discussed in DMs, there is a script we can use if we want to add this but otherwise its probably not something to invest time into putting inside one of our in house scripts.
