### ISSUE TITLE
NPAS Uniforms V2 Update

### ISSUE THREAD

**Issue by Crazycallum** [LondonsBlueLine/tracker#143]
Can I am few minor changes to my uniforms please.

**NPAS Comms Uniform:**

**Clothes:**
Mask: 0 | Texture: 0
Hands: 8 | Texture: 0
Legs: 124 | Texture: 1
Bags and Parachute: 0 | Texture: 0
Shoes: 25 | Texture: 0
Scarf and Chais: 0 | Texture: 0
Shirt: 205 | Texture: 0
Body armour: 59 | Texture: 0
Decals: 133 | Texture: 0
Jackets: 408 | Texture: 0 

**Props:**
Hats and helmets: 185 | Texture: 0

![NPAS Comms Uniform](https://user-images.githubusercontent.com/101276141/163429650-629ee157-d65e-4823-8cf3-117f27566e71.png)

**NPAS Driver Uniform:**

**Clothes:**
Mask: 121 | Texture: 0
Hands: 8 | Texture: 0
Legs: 124 | Texture: 1
Bags and Parachute: 0 | Texture: 0
Shoes: 25 | Texture: 0
Scarf and Chais: 0 | Texture: 0
Shirt: 205 | Texture: 0
Body armour: 59 | Texture: 0
Decals: 133 | Texture: 0
Jackets: 408 | Texture: 0 

**Props:**
Hats and helmets: 170 | Texture: 0

![NPAS Driver Uniforms](https://user-images.githubusercontent.com/101276141/163431713-57875952-bcfd-4105-8f85-a78382af6e3a.png)

**Comment by Dale1987** [comment]
Updated and ready to be pushed to main
