### ISSUE TITLE
Could I Own A Garbage Company within LBL RP To Clean the Streets.

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jxckUK** [comment]
We are focused on emergency service roleplay and as such this isn't on any of our plans.

**Comment by MikeyDeann** [comment]
> 

ok Is their Going to be Ever Like Proper AA Team??
