### ISSUE TITLE
Custom Messageboards

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#149]
I was having a look around and was wondering if there was something you could do with these to maybe add them in the game for NHW and RTPC for road closures and whatever.
https://acepilot2k7.com/vehicle-message-boards/

**Comment by jxckUK** [comment]
Unfortunately not a FiveM ready resource so not something I'd be able to add in at this stage. I think LondonStudios may be working on something similar and if so, we'll look to acquire that.
