### ISSUE TITLE
La Mesa Traffic Base For RTPC

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#153]
Possibly add this station in as a base for RTPC to spawn into and operate from 

Video link: https://www.youtube.com/watch?v=_KBw1BzD5ps

To be purchased from Benzz

**Comment by telboycafc** [comment]
We have looked at this. We have just recently purchased the new station at Heathrow, so at the moment I would say this station wouldn't be a high priority right now as we now have 3 for police, and need to balance interiors out a bit more in terms of LFB ect. But something we are aware of for in the future unless something better comes out.
