### ISSUE TITLE
CIU Vest

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#156]
Spoken to dale about the possibility of skinning a vest for collision investigation, preferably a high vis one.

**Comment by Dale1987** [comment]
CIU vest done and waiting to be put on dev to test

**Comment by jxckUK** [comment]
Closed in https://github.com/LondonsBlueLine/assets/commit/6cf7bf524503ddc702650fed3c3ea6f3f240a57a
