### ISSUE TITLE
[FEAT] Voice GPS

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#158]
This would be a great feature especially when you aren't paying attention to the map, it will actually speak to you when you set a waypoint.

https://forum.cfx.re/t/release-voice-gps-spoken-gps-directions-with-road-names/172442

**Comment by Dale1987** [comment]
I like this idea

**Comment by jxckUK** [comment]
Approved - will add shortly for testing then roll it out to main.
