### ISSUE TITLE
BMW M2 handling line adjustment

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#161]
Hello, is there any chance i can have a faster handling line put on the BMW M2 in interceptor garage, Suggest maybe the feltzer one as the current one just feels a but sluggish, thank you!

**Comment by JamStonedScones** [comment]
Can we also add an ANPR on it as it does say ANPR on the bonnet and has the camera icons on it, or het them taken off?

**Comment by Dale1987** [comment]
ANPR will get added will have a look at these when im on

**Comment by JamStonedScones** [comment]
Thank you

**Comment by Dale1987** [comment]
Going to close this down now as cant seen to fix the issue unfortunatley
