### ISSUE TITLE
Some vehicles to take consideration adding to the RTPC garages?

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#162]
https://unionmods.com/?p=viewfile&file=557
https://unionmods.com/?p=viewfile&file=487
https://unionmods.com/?p=viewfile&file=432
Thanks guys.

**Comment by Dale1987** [comment]
Already tested these in dev mate and didnt pass qc
The audi at the top has dodgy windows

The audi pack has an issue with the bumpers which i tried to sort but couldnt

And i believe the BMW is already in donator garage, but if not i will seek permission to reskin and add it

**Comment by jxckUK** [comment]
@Dale1987 - Any news on the BMW?

**Comment by Dale1987** [comment]
No message back from them mate unfortunately
