### ISSUE TITLE
Armoured land rover issues

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#164]
When someone gets in the back of the land rover in the supervisor garage, you can see their whole body sticking out and also when your like 20metres away from it it is invisible

**Comment by Dale1987** [comment]
Oh shit yeah thats a problem with the model then, unfortunately i will have to remove it

**Comment by jxckUK** [comment]
This probably is fictional as well so if it was to return it would need to go to donators.

**Comment by Dale1987** [comment]
removed from garages
