### ISSUE TITLE
Retro vehicles and additional SFC vehicles

### ISSUE THREAD

**Issue by astron0myy** [LondonsBlueLine/tracker#165]
https://unionmods.com/?p=viewfile&file=601 (Retro vehicles)
https://unionmods.com/?p=viewfile&file=72 (CTSFO)
https://unionmods.com/?p=viewfile&file=137 (SEG)
https://www.unionmods.com/?p=viewfile&file=144 (MO19 - Comes with skin)
https://unionmods.com/?p=viewfile&file=347 (MO19 - Skin for model above)
https://unionmods.com/?p=viewfile&file=478 (SEG)
https://www.gta5-mods.com/vehicles/west-mercia-police-bmw-x5-e70-arv-els (MO19 - Comes with skin)
https://unionmods.com/?p=viewfile&file=249 ( MO19 - Skin for model above)

**Comment by Dale1987** [comment]
No retro vehicles will be added to divisional garages only donator

**Comment by Dale1987** [comment]
A couple of these i have already looked at ain dev and have found  problems will double check them though.

But be advised your garage has recently been updated i wil be looking to work on other garages/ divisions befofe i update SFC again

**Comment by jxckUK** [comment]
Retro vehicles, particularly marked ones are a great addition but there's a couple of things I need to clarify:

- At the moment we're restricted to existing sirens as we use all our audio slots. To fully implement retro vehicles we would need to complete the ELS review.
- No fictional vehicles that are marked will be added to standard garages, full stop. We spend a lot of time correlating our garages to actual MPS fleet data. We can be a bit more lenient with unmarked vehicles as these are obviously not included in fleet data.
- Retro vehicles can be added to Donator garages and/or event garages however.

**Comment by Dale1987** [comment]
This was closed as vehicles requested havr already been in dev and tested

**Comment by jxckUK** [comment]
> This was closed as vehicles requested havr already been in dev and tested

Including the retro pack?

**Comment by Dale1987** [comment]
Audi a6 - dodgy model
Jaguar XES - in donator garage
Kent BMW - dodgy model gun locker keeps popping out if boot
Discovery sport- already in server
Bmw x5- west mercia dodgy texture on the wheels and bumpers

**Comment by Dale1987** [comment]
The retro pack is already downloaded on my pc its not just retro vehicles

**Comment by Dale1987** [comment]
Iv already gone through it and taken like 8 vehicles out of the pack, but they arent SFC vehicles, there is 2 X5s which we already have models of

**Comment by jxckUK** [comment]
Fair enough! Think thats a comprehensive answer.
