### ISSUE TITLE
Enable the ability for window rifling

### ISSUE THREAD

**Issue by astron0myy** [LondonsBlueLine/tracker#166]
This will start wars... I'm aware. But hey ho,

We need this for MO19 due to vehicle tactics as well as scare tactics in vehicles. It's a really nice realistic feature when you're doing a containment on a vehicle and the passenger of both the Front and Side car are at risk if they leave the car, so being able to use the window rifle eliminates that risk as well as keeping it nice and realistic.

To counter the boot, I believe only the passengers of the vehicles should be able to use the Window, due to the driver focusing on driving.

https://unionmods.com/?p=viewfile&file=194

**Comment by jxckUK** [comment]
I'll take a look into this when I've got some capacity, I don't want to enable this globally and I also don't want this to become an option for civilians.

Overall though, I'll accept this is a standard practice in MPS and therefore is approved.

**Comment by jxckUK** [comment]
@astron0myy - The URL you've sent also doesn't function.

**Comment by jxckUK** [comment]
This is longer term than just slapping a resource in so I'm moving it to the roadmap as a P3 item.

https://github.com/ProjectHyde/ProjectHyde/issues/69
