### ISSUE TITLE
Speed Gun

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#168]
_## Issue created anonymously for a user ##_
The radar, so you can clock what speed anyone is going and used within or out of any car (marked or unmarked). Firearms can not use this but rtpc, dsu and bcu’s can use this feature

**Comment by telboycafc** [comment]
Will look in to this. However, will be unlikely that DSU, SFC, will not have use of this feature. BCU not too sure on.

**Comment by jxckUK** [comment]
We do have a radar gun and it is unused so this is probably not a good use of our time at the moment.
