### ISSUE TITLE
Player last connected

### ISSUE THREAD

**Issue by KyHewitt** [LondonsBlueLine/tracker#17]
Have a way to store when a player last connected to the server and this updates every time they connect.
have a way so that Bronze command upwards can easily check these to update there activity records.

**Comment by jxckUK** [comment]
This will be included in **PH-CAD** for all registered users and will show activity logs for all units. Is that sufficient? @KyHewitt

**Comment by jxckUK** [comment]
As discussed - the CAD will show activity records.
