### ISSUE TITLE
Allow civilians to retrieve registered vehicles

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#170]
![image](https://user-images.githubusercontent.com/100094183/165134956-674ccbaf-6b5b-4a52-9f64-2c9428aeb676.png)
the ability to change your plate as a civ as the new ANPR means that is happens everyrtime

**Comment by JamStonedScones** [comment]
sweet, for now would there be a way to delete a car from the system and replace it with one someone it trying to create until they delete it and it reverts back or is that too much work for a short term fix?

**Comment by jxckUK** [comment]
> sweet, for now would there be a way to delete a car from the system and replace it with one someone it trying to create until they delete it and it reverts back or is that too much work for a short term fix?

Yeah at this point I think quickest fix is to just let you set a temporary plate with a command.
