### ISSUE TITLE
Add McDonalds interior

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#172]
_## Issue created anonymously for a user ##_
https://unionmods.com/?p=viewfile&file=229

**Comment by telboycafc** [comment]
We can look in to this, test in dev and see if it passes quality control.

**Comment by telboycafc** [comment]
any update on this dale, was it any good?

**Comment by telboycafc** [comment]
Update for this suggestion - It was put in the Dev build and tested. Sadly it kept making us crash. So on this basis, it has not passed QC and will have to decline the suggestion for the link provided. If you manage to find a better one, we can test it and see how it does. But for now, will close this suggestion. 

Thanks. LBL Dev Team.
