### ISSUE TITLE
RTPC CIU VAN 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#174]
_## Issue created anonymously for a user ##_
could u get the ciu spot light working on the roof so we get more rp

**Comment by telboycafc** [comment]
I believe @Dale1987 may be looking in to this...

**Comment by Dale1987** [comment]
This needs to be a feature added ny @jxckUK  through the eye as the light on the top is an extra on the vehicle

**Comment by jxckUK** [comment]
This is on the roadmap so I'm going to close this item and track it there.
