### ISSUE TITLE
LFB suggestions and improvements

### ISSUE THREAD

**Issue by Mattsmiith93** [LondonsBlueLine/tracker#175]
LFB improvements 

Technical rescue unit, for water rescues / line rescues from height. 

option for an OIC tabard so points of contact for each service are identifiable on scene. 

Option to change uniform out-with the fire station, perhaps an option can be available from one of the lockers or from the boot of a service vehicle? 

Keep up the great work, 😀

**Comment by telboycafc** [comment]
@Mattsmiith93 We will look in to these suggestions. could you provide a picture of the technical rescue unit please. 
The OIC tabard , we may already have one, we just need to look in the EUP to confirm, but yes can be done either way.  
So being able to change uniform from the appliances is something that is already on the road map to be done, bare in mind jack is currently  working on other projects such as CAD ect ect, so no time frame on when it will be complete, but is something we already want to do.

**Comment by jxckUK** [comment]
Merging this into https://github.com/LondonsBlueLine/tracker/issues/185
