### ISSUE TITLE
indicator and Headlights Issue On Marked CIU Van

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#177]
I'm indicating Left it turns the Right Mirror indicator On when i Turn right the  Left Ones Turn On. and the headlight don't have Low Beam They Only Have High Beam Headlights On the Marked CIU Van Insted of Going Low Beam Medium them High beam,

**Comment by MikeyDeann** [comment]
Headlight fixed after Server restart

**Comment by telboycafc** [comment]
@Dale1987 any chance you could have a look when you get a spare moment. Or @MikeyDeann did the server restart fix all the issues ?

**Comment by Dale1987** [comment]
If the indicators are qorking incorrectly this is a problem with the model. So we have 2 options:

Remove the van from the garages
Or
Dont use the indicators on the van

There is no other model around like this so would be very hard to get it replaced

**Comment by Dale1987** [comment]
We are looking at changing our ELS also so i can see if this can help with the indicators

**Comment by jxckUK** [comment]
Closing this because of some background work that will resolve this.
