### ISSUE TITLE
New BTP vehicles 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#180]
_## Issue created anonymously for a user ##_
https://elitejaguar.net/product/btp-ford-kuga
https://elitejaguar.net/product/btp-cell-van-pack
https://www.9mods.net/mod/2016-btp-ford-focus-estate-marked-unmarked-els-replace
https://www.gta5-mods.com/vehicles/thames-valley-police-astra-mk7-2018-response
https://www.gta5-mods.com/paintjobs/2019-btp-vauxhall-astra-livery

**Comment by Dale1987** [comment]
BTP being worked on some vehicles have been added to dev
