### ISSUE TITLE
Small needed feature

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#181]
Right now in game, during the night your lights look bright on the vehicle but it lacks atmosphere as the light seems to just stop there, can just see a hint of blue around the vehicle. Not sure if this mod works for FiveM but I'm sure looking into this you can find out how to do something similar.
https://www.lcpdfr.com/downloads/gta5mods/datafile/31320-better-els-reflections/

I hope this screenshot helps visualise what I'm talking about.
![image](https://user-images.githubusercontent.com/100094183/165653479-4ab0e1ac-cc49-4884-bb58-50f09bee0fc1.png)

**Comment by JamStonedScones** [comment]
https://www.lcpdfr.com/downloads/gta5mods/datafile/9357-radiance-v/

**Comment by jxckUK** [comment]
Couldn't agree more with the suggestion - we've already begun work _something_ and I believe we're a few days off a fairly major release so I'm going to close this out as we're tracking internally! 

Will reopen after the release if we still feel it's an issue.
