### ISSUE TITLE
fix turn off/on engine 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#182]
_## Issue created anonymously for a user ##_
the engine on the /vehcontrol does not work and the /engine doesn't work either. it is useful for saving petrol,when no one is online or no calls

**Comment by jxckUK** [comment]
> I believe the 'HOME' vehicle menu already contains an option to enable/disable your engine.

I think that is the one that isn't functioning at the moment which is odd - possibly conflicting with the fuel script?

**Comment by Dale1987** [comment]
bug fixed
