### ISSUE TITLE
Change the uniforms for LFB turnout and BA

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#183]
Is there any chance we could get gloves for our LFB uniforms. The uniforms we would like gloves on is the RTC Turnout Gear, BA Ready and BA On. Hands are 142 and texture 4.

**Comment by Dale1987** [comment]
this is one for @telboycafc

**Comment by jxckUK** [comment]
Vidal is going to put these together, I'll QC afterwards.

**Comment by telboycafc** [comment]
This has been completed, and tested in DEV and shown to Viidal. Ready for @jxckUK to merge.
