### ISSUE TITLE
NPAS Uniform and beacon lights

### ISSUE THREAD

**Issue by Crazycallum** [LondonsBlueLine/tracker#189]
Can you change the NPAS Helmets to ID: 191 with no Mask

**Comment by Dale1987** [comment]
That is the hems helmet is it not?

**Comment by Crazycallum** [comment]
aww how are they getting the cool ones

**Comment by Dale1987** [comment]
Because this was bought in a hems pack by someone in LAS

**Comment by Dale1987** [comment]
![Uploading Screenshot_20220502-171528_Discord.jpg…]()

**Comment by Dale1987** [comment]
![Screenshot_20220502-171528_Discord](https://user-images.githubusercontent.com/95533432/166268857-88b9ecb9-cc73-4897-ac44-476a48a6a7b8.jpg)

**Comment by Dale1987** [comment]
Dont worry got my eyes on something for NPAS too

**Comment by Crazycallum** [comment]
YES I BEG

**Comment by Crazycallum** [comment]
Hello Lads
 

Could you make the NPAS Supervisor uniform like have the Driver outfit and then copy and paste it but with a Sergeant rank slides and put it in the Bronze Command uniform

**Comment by telboycafc** [comment]
Does this have approval from silver command and Gold ?

**Comment by CalLBLRP** [comment]
Affirm on my end - @jxckUK and Ryan?

**Comment by telboycafc** [comment]
An NPAS uniform has been purchased. Any other request are denied at this time.
