### ISSUE TITLE
Panther vehicles ANPR

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#191]
Hello, I made a thing on here a while back on adding ANPR script to some of the panther vehicles and it seems to be gone and not added, i cant find any response to in anywhere? I might be wrong but this was all I could find. 
![image](https://user-images.githubusercontent.com/100094183/166393651-34796e2a-b1ce-4b1f-bd58-f930cf64fd76.png)

**Comment by jxckUK** [comment]
This was done mate, I closed it and pushed it.

https://github.com/ProjectHyde/ProjectHyde/commit/870abf62a2fae67cba2e806eea55c9413e50f815
