### ISSUE TITLE
Collision investigation locker (hello tel)

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#192]
Crazy Callum has kindly gone onto the dev and created a uniform for the CIU to use, utilising the new vest added.

Please can I have a locker added with the uniform attached to the CIU role.

Thank you.

**Comment by Crazycallum** [comment]
Hello! 

Collision investigation officer (CIU)

**Clothes:**

Mask: 121 | Texture: 0

Hands: 0 |  Texture: 0

Legs: 152 |  Texture: 0

Bags and parachute: 0 |  Texture: 0

Shoes: 25 |  Texture: 0

Scarf and Chais: 183 |  Texture: 0

Shirt: 208 |  Texture: 0

Body armor: 71 |  Texture:  0

Decals: 134 |  Texture: 0

Jackets: 397 |  Texture:  0

**Props:**

Hats and Helmets: 174 |  Texture:  0


**Pics**

![image](https://user-images.githubusercontent.com/101276141/166478053-9afa889b-860f-4cfa-bfb2-9c2b8eaa75af.png)

![image](https://user-images.githubusercontent.com/101276141/166478078-a41e201b-544e-4a38-863d-77fea31c8e3a.png)

**Comment by telboycafc** [comment]
done and tested in dev ready for merging. @jxckUK
