### ISSUE TITLE
ANPR SFC

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#194]
Can we add anpr so some of the SFC vechiles that have/say ANPR so we can look out for weapon markers on vechiles

**Comment by jxckUK** [comment]
@JamStonedScones

**Comment by JamStonedScones** [comment]
I believe the view of leadership team is to keep ANPR as an RTPC only thing to help increase the uniqueness and maintain solid boundaries between divisions. There will be an announcement in a couple of days time reviling a new sub-division that will bridge the gap a little allowing, in some way, for this to me possible.

**Comment by telboycafc** [comment]
Thanks Jam. 

So to cap it off, The ANPR system is unique to RTPC and thats how we do like to keep it. Same as SFC are unique to the use of firearms, and DSU are unique to the use of the dogs. 

However keep ya ears pealed for jams announcement.
