### ISSUE TITLE
[FEAT] British Police Handbook

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#196]
https://forum.cfx.re/t/british-police-handbook-uk-legislation-gowisely-ipp-arrest-more-server-side-script/1156326

> This can then cater towards new players as well.

thank you! :)

**Comment by telboycafc** [comment]
Hello, so we have some things coming in that we are working on, a lot of this sounds like it can come from in house divisional training like initial pursuit phase ect which would come from RTPC. This won't also tie in with the work that is currently being done. This could and should in some cases come under PC training when a player joins BCU to help new players at the beginning. So at the moment we are going to decline this suggestion, but thanks for bringing it up. 

Please continue to suggest ideas. 

The leadership team.
