### ISSUE TITLE
BMW G20 INTERCEPTOR

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#198]
_## Issue created anonymously for a user ##_
Car is bugged, chassis seems to start coming out of the car whilst driving 

 https://medal.tv/games/gta-v/clips/k0x2fNbwqDkLB/d1337VLmutPe?invite=cr-MSxtN1MsMTk3OTU2Njgs

link to watch what happens

**Comment by Dale1987** [comment]
Yeah noticed this yesterday, it only happens when you crash the car. Will be removing this vehicle

**Comment by telboycafc** [comment]
Done and will be reinstated back in to the main Build. New model has been added. Will close this out now.
