### ISSUE TITLE
SRCT Uniform

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#203]
Hello fellas.

Please may I have this uniform placed into the lockers. 

Category "Serious Roads Crime Team"
Uniform name "SRCT Officer"
Roles needed "SRCT"

![image](https://user-images.githubusercontent.com/100094183/168093826-5294cc2f-af42-4f17-ad9f-899d6bca9653.png)
![image](https://user-images.githubusercontent.com/100094183/168093858-dd443a0e-41f4-43be-92e8-a7e7bc7362d5.png)

**Comment by Dale1987** [comment]
this needs to be done and then sent with the save eup command, this has been done through Vmenu, which the numbers are all different

**Comment by JamStonedScones** [comment]
This has been done and sent with the eup command now.

**Comment by jxckUK** [comment]
> This has been done and sent with the eup command now.

Sorry buddy - I don't see this in the export of runned commands. Could you confirm you followed the instructions for the command in Bronze?

**Comment by JamStonedScones** [comment]
I can confirm it was done with the command

**Comment by jxckUK** [comment]
{ "SRCT", "SRCT Passenger", "mps", 52, 0, 58, 0, 152, 0, 0, 0, 25, 0, 176, 0, 153, 0, 66, 0, 0, 0, 424, 0, 170, 0}
{ "SRCT", "SRCT Driver", "mps", 35, 0, 171, 0, 152, 0, 0, 0, 25, 0, 168, 0, 206, 0, 66, 0, 134, 0, 426, 0, 174, 0}

Needs to be added to dev lockers and QC'ed

**Comment by jxckUK** [comment]
MPS25 and MPS19 to be moved to SRCT

**Comment by Dale1987** [comment]
Still have the proper raptor vehicle to go in this garage, and can make  a copy of 25 & 19 with raptor skin

**Comment by Dale1987** [comment]
Lockers & garages done awaiting push to main
