### ISSUE TITLE
Discord "Other games" role react.

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#204]
A role react message in other games for roles similar to "@pro clubs" that a lot of the community play like Rainbow six and Ready or not?

**Comment by CalLBLRP** [comment]
Hiya @JamStonedScones, 

Unfortunately, this suggestion has been denied when speaking with a member of the Leadership Team. They stated that we will only be doing for any games where you can setup a clan or a team. 

Keep the suggestions coming, 

Kind Regards,
Cal.
