### ISSUE TITLE
BMW G20 ANPR Camera

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#205]
Please can I have the ANPR camera added to the Interceptor G20, spawn code is MPS163.

Thank you x

**Comment by Dale1987** [comment]
Will sort it later mate

**Comment by JamStonedScones** [comment]
Nice one mate, another thing that i just noticed, not big and wont bother me but I know there is some people that will bring it up, only one of the exhausts work ahaa
![image](https://user-images.githubusercontent.com/100094183/168269291-bafea1f6-d531-4840-a21d-0d4f88af2664.png)

**Comment by Dale1987** [comment]
Lol thats the model mate. Didnt realise that. I can have a look for another model to see if i can replace it

**Comment by JamStonedScones** [comment]
Its not a massive issue and the model is a great addition, I suggest overlooking it for now but keeping in mind if it comes up in the future we could look at replacing it?
