### ISSUE TITLE
FRU Fire Truck

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#206]
Hey there I was wondering if we could get a firetruck added for the FRU sub-division. For some reason I cant post the link so i will have to say the steps of finding it. 1) Search up Gta5mod.net. 2) In the search bar for the gta5mod website which should be located on the right sand side, type in London Fire Brigade MK1/MK2. Than it should appear with the firetruck

**Comment by telboycafc** [comment]
Vehicle requests will have to be on hold at the moment. There is a mammoth task of doing the ELS at the moment which is taking a lot of time up.

**Comment by Dale1987** [comment]
Already have this downloaded on my PC, wil be added to dev at some point to test
