### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RASHYTHEGOAT** [LondonsBlueLine/tracker#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [PC WINDOWS 10
 - Browser [in Game 
 - Version [ Dont know 

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.Hi there is a glitch to get armory out it happens like every day to me and then it does it sometimes it took me 25 mins to get my armory on

**Comment by Dale1987** [comment]
Please describe the bug through the template, this isnt enough information for us to help you

**Comment by RASHYTHEGOAT** [comment]
When I go into a station go to armory it doesn’t spawn I had this for like 2 weeks an other people had had it aswell



On 19 May 2022, at 8:12 am, Dale1987 ***@***.***> wrote:

﻿

Please describe the bug through the template, this isnt enough information for us to help you

**Comment by jxckUK** [comment]
Still not enough information - please resubmit with more information.
