### ISSUE TITLE
LFB Helicopter 

### ISSUE THREAD

**Issue by Ttvshadow21** [LondonsBlueLine/tracker#212]
We could possible have a LFB helicopter so we can also join Search and Rescues with NPAS, we could fly over fires and inform firefighters on ground whats going on and if its spreading and if anyone is down either inside or outside the building. I believe this could help fire with its missions on search and rescues and those big fires which we cant get inside and see if anyone is inside so that's why we have the helicopter to see if anyone is inside and to find the best exit firefighters can go in and come out.
Here is the link if you consider it
https://www.unionmods.com/?p=viewfile&file=468

**Comment by jxckUK** [comment]
This is not going to be implemented as we believe at this time the LFB do not operate a helicopter.
