### ISSUE TITLE
Safer Transport Teams

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#217]
_## Issue created anonymously for a user ##_
So a few people want BTP but I understand there isn't much to do with them so how about instead of BTP we integrate them with STT. If you haven't seen them here is the link. its an option to maybe think about as BTP can be put with this division. 

https://www.met.police.uk/a/your-area/safer-transport-teams/

**Comment by Dale1987** [comment]
BTP is going to be coming in the future, we just need to finish ELS. Alpha101 is currently making docs etc for the division. we have EUP and some vehicles for BTP but not yet ready to be opened up
