### ISSUE TITLE
AA HIGHWAYS ENGLAND 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#219]
_## Issue created anonymously for a user ##_
Me and my friend Lewis was thinking last night about adding like highways England and aa to the server I think it will increase more people to join the server and It will increase people to join because it has more roles and people will apply for then and I know people will because they ask all time

**Comment by Dale1987** [comment]
Hello so we already have National Highways in game its just not out for apps yet as we want to get more things ready for it.

AA is not something we will be looking at adding.
