### ISSUE TITLE
Not able to pull over vehicles

### ISSUE THREAD

**Issue by ttvkenzjohGC** [LondonsBlueLine/tracker#221]
When I go to initiate a traffic stop it shows a pop up saying "turn on your sirens to initiate a traffic stop , so I turn on my sirens and try again but another pop up shows up and says the same thing.
Not able to put the link to the clip.

**Comment by Kyymather** [comment]
This happened to me before going into F11 menu and going off duty and back on it worked again just a suggestion

**Comment by jxckUK** [comment]
I would follow Kyy's advice for the time being whilst we're still on FivePD.
