### ISSUE TITLE
bug on SRCT car BMW330d

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#223]
_## Issue created anonymously for a user ##_
Will not load the car if more than 20m away. shows in video

https://medal.tv/games/gta-v/clips/nnH9zhuqOQFKR/d1337HyW3wZ6?invite=cr-MSxWT0wsMTk3OTU2Njgs

**Comment by Dale1987** [comment]
Easy fix will sort this later today

**Comment by jxckUK** [comment]
Fixed in https://github.com/LondonsBlueLine/assets/commit/4767d8e821ea5359f9a1ddc5285d3737bcdcc2f1
