### ISSUE TITLE
New ELS issues with AI reactions.

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#226]
**Describe the bug**
There seems to be an issue where when driving around with no lights on, all the AI are pulling over as if you are responding.

**To Reproduce**
1. Play for 5/10 minutes.
2. Turn all ELS off and drive around the city.
3. Observe all the AI vehicles pull to the side as if your lights are on.
4. Press shift on a vehicle and it will be pulled over/fts instantaneously without any input.

https://streamable.com/mw7slt

**Comment by jxckUK** [comment]
Note to self - Vehicles without a matrix board retain ELS pullover logic

**Comment by jxckUK** [comment]
Takedown/Spotlight is causing this, will aim to fix

**Comment by jxckUK** [comment]
https://github.com/ProjectHyde/ProjectHyde/commit/007bd2fb4ecd3b34b0324825908da3b847a45d39 attempts to address this.
