### ISSUE TITLE
[FEAT] New Motorbike Police Uniform

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#23]
From This
![20220203093006_1](https://user-images.githubusercontent.com/75227401/152317335-54a6bbdb-f18d-476b-a625-ebfb8e021e86.jpg)

To This
![20220203093321_1](https://user-images.githubusercontent.com/75227401/152317341-e4e79073-cdb9-4e2e-9657-97283ec7ab54.jpg)

The only changes are to shirt, jacket and shoes

**Comment by jxckUK** [comment]
@MrP3n9u1n - Approved from both an MPS and Development perspective.

I'll ask Tel to see if he can amend this to get it as it doesn't require new EUP.

**Comment by telboycafc** [comment]
This has been completed and pushed on github.
