### ISSUE TITLE
have events and arrests affect crimes seen[FEAT]

### ISSUE THREAD

**Issue by Atatrax** [LondonsBlueLine/tracker#232]
a feature arrests and events affect the crimes seen such as knife crimes may be higher if knife crimes are unanswered etc i think this could add a higher level of immersion

**Comment by WolfRanger88** [comment]
Hi, Thank you for your suggestion and I think it is in interesting one but at the current time we are operating with fivepd which would not facilitate this but our own callout system is in heavy development so it may be something we can incorporate. 

I have tagged @jxckUK in as he will know if this is possible in the future and subsequently would be able to add to the road map etc.

**Comment by jxckUK** [comment]
Approved - nice idea but a roadmap item and as such I'll be tracking it there.

https://github.com/ProjectHyde/ProjectHyde/issues/80
