### ISSUE TITLE
[BUG] Vintage Pistol for civ

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#24]
Vintage pistol is a speed gun/radar
![20220203113526_1](https://user-images.githubusercontent.com/75227401/152337124-6f33fbdb-22f7-4ba6-996c-d6add673bb93.jpg)
![20220203113548_1](https://user-images.githubusercontent.com/75227401/152337130-6fcfe6fe-7db8-449d-bc15-b87fac8c073a.jpg)
![20220203113555_1](https://user-images.githubusercontent.com/75227401/152337134-be3a3989-cda5-427b-ba0c-67a352dc257f.jpg)

**Comment by jxckUK** [comment]
haha fantastic bug, I will replace with a combat pistol.
