### ISSUE TITLE
Officer Down Callout

### ISSUE THREAD

**Issue by ItzDunley** [LondonsBlueLine/tracker#240]
When you go to this call the officer spawns in an American unmarked car
![image](https://user-images.githubusercontent.com/107349992/173232054-b05a64c1-ca95-4900-8e8c-edf96dccd607.png)

**Comment by WolfRanger88** [comment]
This is an asset issue as previous team managing assets removed all replacement vehicles and therefore American style still exist. Unfortunately this call out will need to be removed until assets reviewed. 

Issue closed through removal of callout.
