### ISSUE TITLE
New improvement suggestion for vehicles 

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#245]
Would it be possible to write a script where if a vehicle encounters a collision of a certain amount of force it will shut off the engine and require a fix for police to start there engine again This would make people be extra cautious when driving especially in pursuits and also improve effectiveness of manoeuvres like hard sops, interceptor rams and ones demonstrated in the video below.
https://www.youtube.com/watch?v=7MeilIHGuGQ

**Comment by jxckUK** [comment]
Transferring to https://github.com/ProjectHyde/ProjectHyde/issues/82
