### ISSUE TITLE
BTP DOG UNIT

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#251]
Morning!

My suggestion for DSU & BTP.

- A discord tag for DSU which unlocks BTP dog vehicles and uniform.
- These vehicles and uniforms categorised in DSU Advanced sub category in garage and same for locker room.
- Only DSU officers out of basic/probation can apply for BTP DSU.

**Comment by JamStonedScones** [comment]
Love the idea, have you guys spoken with Alpha or Gibby to ensure they are also happy with this. What do you have ready for the sub division and what do you need from us guys to get started.

You will need, uniforms created in dev and sent using the command pinned in #bronze-command.
Training docs created.
A realistic name chosen for the division and a name for the role.
What vehicles you want in the garage.
