### ISSUE TITLE
BRP (Brittish River Police0

### ISSUE THREAD

**Issue by therealJiko** [LondonsBlueLine/tracker#253]
Forces with large rivers or coastal waters within their area will have a river police section to assist in the policing the following situations:

•  assisting boats in difficulties
•  inspecting docks, riverside premises and landing places
•  dealing with thefts from ships, houseboats and riverside warehouses
•  rescuing people (sometimes retrieving bodies) from the water
•  making safe drifting boats, or other objects which can cause hazards on the water
•  monitoring water pollution
•  working with HM Revenue and Customs to counter smuggling
•  searching for suspects and criminals

**Comment by jxckUK** [comment]
This was dissolved in 1839 so not really applicable to the time period the server is set in (2022).
