### ISSUE TITLE
EUP panther and SRCT

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#254]
I have put 2 commands in DEV for SRCT driver and a Panther unit, SRCT just needs swapping out and the panther is for a new uniform entirely

**Comment by jxckUK** [comment]
{ "SRCT", "SRCT PASSENGER", "mps", 52, 0, 171, 0, 152, 0, 0, 0, 25, 0, 168, 0, 130, 0, 66, 0, 134, 0, 434, 0, 164, 0},
{ "SRCT", "SRCT DRIVER", "mps", 121, 0, 92, 0, 152, 0, 0, 0, 25, 0, 177, 0, 210, 0, 58, 0, 0, 0, 449, 0, 170, 0}

**Comment by WolfRanger88** [comment]
Completed and waiting merge to main
