### ISSUE TITLE
bomb diffusers division

### ISSUE THREAD

**Issue by therealJiko** [LondonsBlueLine/tracker#255]
The first professional civilian bomb squad was established by Sir [Vivian Dering Majendie](https://en.wikipedia.org/wiki/Vivian_Dering_Majendie).[[2]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-Brodie-2) As a [Major](https://en.wikipedia.org/wiki/Major) in the [Royal Artillery](https://en.wikipedia.org/wiki/Royal_Artillery), Majendie investigated an explosion on 2 October 1874 in the [Regent's Canal](https://en.wikipedia.org/wiki/Regent%27s_Canal), when the [barge](https://en.wikipedia.org/wiki/Barge) 'Tilbury', carrying six barrels of petroleum and five tons of gunpowder, blew up, killing the crew and destroying Macclesfield Bridge and cages at nearby [London Zoo](https://en.wikipedia.org/wiki/London_Zoo). In 1875, he framed The Explosives [Act](https://en.wikipedia.org/wiki/Bill_(proposed_law)), the first modern legislation for explosives control.[[3]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-3) He also pioneered many bomb disposal techniques, including remote methods for the handling and dismantling of explosives.[[2]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-Brodie-2) His advice during the [Fenian dynamite campaign](https://en.wikipedia.org/wiki/Fenian_dynamite_campaign) of 1881–85[[4]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-4) was officially recognised as having contributed to the saving of lives. After [Victoria Station](https://en.wikipedia.org/wiki/London_Victoria_station) was bombed on 26 February 1884 he defused a bomb built with a [clockwork](https://en.wikipedia.org/wiki/Clockwork) mechanism which might have gone off at any moment.[[5]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-Obit-5)

The [New York City Police Department](https://en.wikipedia.org/wiki/New_York_City_Police_Department) established its first bomb squad in 1903. Known as the "Italian Squad", its primary mission was to deal with [dynamite](https://en.wikipedia.org/wiki/Dynamite) bombs used by the [Mafia](https://en.wikipedia.org/wiki/Italian-American_Mafia) to intimidate immigrant Italian merchants and residents. It would later be known as the "[Anarchist](https://en.wikipedia.org/wiki/1919_United_States_anarchist_bombings) Squad" and the "Radical Squad".[[6]](https://en.wikipedia.org/wiki/Bomb_disposal#cite_note-6)

WWI: Military bomb disposal units

A British NCO prepares to dispose of an unexploded bomb, during the First World War.
Bomb Disposal became a formalized practice in the First World War. The swift mass production of munitions led to many manufacturing defects, and a large proportion of shells fired by both sides were found to be "duds".[7] These were hazardous to attacker and defender alike. In response, the British dedicated a section of Ordnance Examiners from the [Royal Army Ordnance Corps](https://en.wikipedia.org/wiki/Royal_Army_Ordnance_Corps) to handle the growing problem.

In 1918, the Germans developed [delayed-action fuzes](https://en.wikipedia.org/wiki/Delayed-action_fuze) that would later develop into more sophisticated versions during the 1930s, as [Nazi Germany](https://en.wikipedia.org/wiki/Nazi_Germany) began its secret course of arms development. These tests led to the development of UXBs ([unexploded bombs](https://en.wikipedia.org/wiki/Unexploded_bombs)), pioneered by Herbert Ruehlemann of [Rheinmetall](https://en.wikipedia.org/wiki/Rheinmetall), and first employed during the [Spanish Civil War](https://en.wikipedia.org/wiki/Spanish_Civil_War) of 1936–37. Such delayed-action bombs provoked terror in the civilian population because of the uncertainty of time, and also complicated the task of disarming them. The Germans saw that unexploded bombs caused far more chaos and disruption than bombs that exploded immediately. This caused them to increase their usage of delayed-action bombs in [World War II](https://en.wikipedia.org/wiki/World_War_II).

Initially there were no specialized tools, training, or core knowledge available, and as Ammunition Technicians learned how to safely neutralize one variant of munition, the enemy would add or change parts to make neutralization efforts more hazardous. This trend of cat-and-mouse extends even to the present day, and the various techniques used to disarm munitions are not publicized.

WWII: Modern techniques

A bomb disposal team in 1940.
Modern EOD Technicians across the world can trace their heritage to the Blitz, when the United Kingdom's cities were subjected to extensive bombing raids by Nazi Germany. In addition to conventional air raids, unexploded bombs (UXBs) took their toll on population and morale, paralyzing vital services and communications. Bombs fitted with delayed-action fuzes provoked fear and uncertainty in the civilian population.

The first UXBs were encountered in the autumn of 1939 before the Blitz and were for the most part easily dealt with, mostly by Royal Air Force or Air Raid Precautions personnel. In the spring of 1940, when the Phony War ended, the British realized that they were going to need professionals in numbers to deal with the coming problem. 25 sections were authorized for the Royal Engineers in May 1940, another 109 in June, and 220 by August. Organization was needed, and as the Blitz began, 25 "Bomb Disposal Companies" were created between August 1940 and January 1941. Each company had ten sections, each section having a bomb disposal officer and 14 other ranks to assist. Six companies were deployed in London by January 1941.

The problem of UXBs was further complicated when Royal Engineer bomb disposal personnel began to encounter munitions fitted with anti-handling devices e.g. the Luftwaffe's ZUS40 anti-removal bomb fuze of 1940. Bomb fuzes incorporating anti-handling devices were specifically designed to kill bomb disposal personnel. Scientists and technical staff responded by devising methods and equipment to render them safe, including the work of Eric Moxey.[8]

The United States War Department felt the British Bomb Disposal experience could be a valuable asset, based on reports from U.S. Army, Navy, and Marine Corps observers at RAF Melksham in Wiltshire, England in 1940. The next year, the Office of Civilian Defense (OCD) and War Department both sponsored a bomb disposal program. After the attack on Pearl Harbor, the British sent instructors to Aberdeen Proving Ground, where the U.S. Army would inaugurate a formal bomb disposal school under the Ordnance Corps. Col. Thomas J. Kane became the U.S. Army Ordnance Bomb Disposal School commandant, and later served as ETO Director of Bomb Disposal under Dwight D. Eisenhower.[9] In May 1941, British colleagues helped establish the Naval Mine Disposal School at the Naval Gun Factory, Washington, D.C. Concurrently, the U.S. Navy, under the command of Lt. Draper L. Kauffman (who would go on to found the Underwater Demolition Teams – better known as UDTs or the U.S. Navy Frogmen), created the Naval Bomb Disposal School at University Campus, Washington, D.C.

The first US Army Bomb Disposal companies were deployed in North Africa and Sicily, but proved cumbersome and were replaced with mobile seven-man squads in 1943. Wartime errors were rectified in 1947 when Army personnel started attending a new school at Indian Head, Maryland, under U.S. Navy direction. That same year, the forerunner of the EOD Technology Center, the USN Bureau of Naval Weapons, charged with research, development, test, and evaluation of EOD tools, tactics and procedures, was born.

Northern Ireland
The Ammunition Technicians of the Royal Logistic Corps (formerly RAOC) became highly experienced in bomb disposal, after many years of dealing with bombs planted by the Provisional Irish Republican Army (PIRA) and other groups. The bombs employed by the PIRA ranged from simple pipe bombs to sophisticated victim-triggered devices and infrared switches. The roadside bomb was in use by PIRA from the early 1970s onwards, evolving over time with different types of explosives and triggers. Improvised mortars were also developed by the IRA, usually placed in static vehicles, with self-destruct mechanisms.[10] During the 38-year campaign in Northern Ireland, 23 British ATO bomb disposal specialists were killed in action.[11]

A specialist Army unit, 321 EOD Unit (later 321 EOD Company, and now 321 EOD & Search Squadron RLC part of 11 Explosive Ordnance Disposal and Search Regiment RLC), was deployed to tackle increased IRA violence and willingness to use bombs against both economic and military targets. The unit's radio call-sign was Felix. All units in Northern Ireland had a callsign to be used over the radios. 321 Company, a newly formed unit, didn't have such a callsign, so a young signaller was sent to the OC of 321 Coy. The OC, having lost two technicians that morning, decided on "Phoenix". This was misheard as "Felix" by the signaller and was never changed. The other possible reason is that the callsign for RAOC was "Rickshaw"; however, the 321 EOD felt it needed its own callsign, hence the deliberate choice of "Felix the Cat with nine lives". 321 Coy RAOC (now 321 EOD & Seach Sqn RLC) is the most decorated unit (in peacetime) in the British Army with over 200 gallantry awards, notably for acts of great bravery during Operation Banner (1969–2007) in Northern Ireland.[12]

British Ammunition Technicians of 11 EOD & Search Regiment RLC were requested by the US Forces commanders to operate in support of the US Marine Corps in clearing the Iraqi oilfields of booby traps and were among the first British service personnel sent into Iraq in 2003 prior to the actual ground invasion.

Low intensity conflicts

Marines conducting a controlled detonation of improvised explosive devices in Afghanistan.
The eruption of low intensity conflicts and terrorism waves at the beginning of the 21st century caused further development in the techniques and methods of bomb disposal. EOD Operators and Technicians had to adapt to rapidly evolving methods of constructing improvised explosive devices ranging from shrapnel-filled explosive belts to 100 kg bombs. Since improvised explosives are generally unreliable and very unstable they pose great risk to the public and especially to the EOD Operator trying to render them safe. Therefore, new methods like greater reliance on remote techniques such as advanced remotely operated vehicles similar to the British Wheelbarrow or armored bulldozers evolved. Many nations have developed their own versions such as the D7 MCAP and the armored D9R.

U.S. Navy explosive ordnance disposal (EOD) divers.
Besides large mine-clearing vehicles such as the Trojan, the British Army also uses small remote controlled vehicles such as the Dragon Runner and the Chevette.[13][clarification needed]

During the al-Aqsa Intifada, Israeli EOD forces have disarmed and detonated thousands of explosive charges, lab bombs and explosive ammunition (such as rockets). Two Israeli EOD teams gained high reputation for leading the efforts in that area: the Army's Israeli Engineering Corps' Sayeret Yahalom and the Israeli Border Guard Gaza-area EOD team.

In the Iraq War, the International coalition multinational force in Iraq forces have faced many bombs on travel routes. Such charges can easily destroy light vehicles such as the Humvee, and large ones can even destroy main battle tanks. Such charges caused many casualties and along with car bombs and suicide bombers were a major cause of casualties in Iraq.

In Spain's autonomous Basque Country, where bombings by Basque separatist groups were common during the 1980s and 1990s, there are three corps in charge of bomb disposal: Policia Nacional, Guardia Civil, and Ertzaintza. The Ertzaintza handle general civilian threats, while the Policia Nacional and Guardia Civil maintain capabilities mainly to defend their own assets and personnel. In other parts of the country, the Guardia Civil and Policia Nacional develop their tasks within their own abilities).

Fields of operations
EOD

Disposal of a British 4,000 pound blockbuster bomb dropped by the RAF during World War II. Found in the Rhine near Koblenz, 4 December 2011. A linear shaped charge has been placed on top of the casing
In the United States, Explosive Ordnance Disposal (EOD) is a specialized technical area in military and law enforcement.[14][15][16]

In the United Kingdom, EOD Operators are held within all three Services. Each Service has differing responsibilities for UXO, however they will often work closely on operations.

Ammunition Technical Officers and Ammunition Technicians of the Royal Logistic Corps deal with many aspects of EOD, including conventional munitions and homemade bombs.[17] They are also trained in chemical, biological, incendiary, radiological ("dirty bombs"), and nuclear weapons. They provide support to VIPs, help civilian authorities with bomb problems, teach personnel from all three services about bomb safety, and a variety of other tasks.

The Royal Engineers of 33 Engineer Regiment (EOD) provide EOD expertise for air dropped munitions in peacetime and conventional munitions on operations, as well as battle area clearance and High Risk Search in support of improvised explosive device disposal.[18]

Royal Engineers provide search advice and assets, Ammunition Technicians and Ammunition Technical Officers of 11 Explosive Ordnance Disposal and Search Regiment RLC provide Improvised Explosive Device Disposal (IEDD), Conventional Munitions Disposal (CMD) and Biological, Chemical Munitions Disposal (BCMD). They also provide expertise in Advanced IEDD and in the investigation of accidents and incidents involving ammunition and explosives, where they are seen as Subject Matter Experts (SMEs).

Bomb suit of Bomb Disposal Squad of the Indian Army
Weapons Intelligence is supplied by Royal Military Police, Intelligence Corps and Ammunition Technical Personnel who tap into the CEXC units of the US.

All prospective Ammunition Technicians attend a gruelling course of instruction at The Army School of Ammunition and the Felix Centre, United Kingdom. The time frame for an RLC Ammunition Technician to complete all necessary courses prior to finally being placed on an EOD team is around 36 months. Whereas the Engineer EOD training period although shorter in total is spread over a number of years and interspersed with operational experience, RE personnel may be posted to core trades such as carpentry or bridge building within their time as engineers.

Royal Navy clearance divers also deploy teams both in the UK and on operations working on both IEDD (Improvised Explosive Device Disposal) teams as well as the disposal of conventional munitions. Royal Navy personnel spend their entire service working with and around explosives, and associated sciences. As such are given responsibilities relevant to their roles when it comes to conventional weapons;

Royal Navy: Anything of an explosive nature found below the high water mark or deemed to be of a naval origin.
PSBT

An FBI agent in a bomb suit performing a training mission
US EOD covers both on- and off-base calls in the US unless there is a local PSBT or "Public Safety Bomb Technician" who can handle the bomb; ordnance should only be handled by the EOD experts. Also called a "Hazardous Devices Technician", PSBTs are usually members of a police department, although teams are also formed by fire departments or emergency management agencies.

To be certified, a PSBT must attend the FBI Hazardous Devices School at Redstone Arsenal, Alabama which is modeled on the International IEDD Training school at The Army School of Ammunition, known as the Felix Centre. This school helps them to become knowledgeable in the detection, diagnosis, and disposal of hazardous devices. They are further trained to collect evidence in hazardous devices, and present expert-witness testimony in court on bombing cases.

UXO
Main article: Unexploded ordnance
Before bombing ranges can be reutilized for other purposes, these ranges must be cleared of all unexploded ordnance. This is usually performed by civilian specialists trained in the field, often with prior military service in explosive ordnance disposal. These technicians use specialized tools for subsurface examination of the sites. When munitions are found, they safely neutralize them and remove them from the site.

Other (training, mining, fireworks)
In addition to neutralizing munitions or bombs, conducting training and presenting evidence, EOD Technicians and Engineers also respond to other problems.

EOD Technicians help dispose old or unstable explosives, such as ones used in quarrying, mining, or old/unstable fireworks and ammunition. They also assist specialist police units, raid and entry teams with boobytrap detection and avoidance, and they help in conducting post-blast investigations.

The EOD technician's training and experience with bombs make them an integral part of any bombing investigation. Another part of an EOD technician's job involves supporting the government intelligence units. This involves searching all places that the high ranking government officers or other protected dignitaries travel, stay or visit.

Bomb disposal vehicle demonstration in Tokyo, 2016
Techniques
Generally, EOD render safe procedures (RSP) are a type of tradecraft protected from public dissemination in order to limit access and knowledge, depriving the enemy of specific technical procedures used to render safe ordnance or an improvised device. Another reason for keeping tradecraft secret is to hinder the development of new anti-handling devices by their opponents: if the enemy has thorough knowledge of specific EOD techniques, it can develop fuze designs which are more resistant to existing render-safe procedures.

Many techniques exist for the making safe of a bomb or munition. Selection of a technique depends on several variables. The greatest variable is the proximity of the munition or device to people or critical facilities. Explosives in remote localities are handled very differently from those in densely populated areas. Contrary to the image portrayed in modern-day movies, the role of modern bomb disposal operators is to accomplish their task as remotely as possible. Actually laying hands on a bomb is only done in an extremely life-threatening situation, where the hazards to people and critical structures cannot be reduced.

Wheelbarrow remotely controlled bomb disposal tool
EOD technicians have many tools for remote operations, one of which is the RCV, or remotely controlled vehicle, also known as the "Wheelbarrow". Outfitted with cameras, microphones, and sensors for chemical, biological, or nuclear agents, the Wheelbarrow can help the technician get an excellent idea of what the munition or device is. Many of these robots even have hand-like manipulators in case a door needs to be opened, or a munition or bomb requires handling or moving. The first ever Wheelbarrow was conceived by Major Robert John Wilson 'Pat' Patterson RAOC and his team at the Bomb Disposal School, CAD Kineton in 1972 and used by ammunition technicians in the battle against Provisional Irish Republican Army bombs.

Placing a disruption charge (a counter-charge[19]) while wearing a protective suit
Also of great use are items that allow ammunition technicians to remotely diagnose the innards of a munition or bomb. These include devices similar to the X-ray used by medical personnel, and high-performance sensors that can detect and help interpret sounds, odors, or even images from within the munition or bomb. Once the technicians determine what the munition or device is, and what state it is in, they will formulate a procedure to disarm it. This may include things as simple as replacing safety features, or as difficult as using high-powered explosive-actuated devices to shear, jam, bind, or remove parts of the item's firing train. Preferably, this will be accomplished remotely, but there are still circumstances when a robot won't do and technicians must put themself at risk by personally going near the bomb. Technicians will don specialized protective suits, using flame and fragmentation-resistant material similar to bulletproof vests. Some suits have advanced features such as internal cooling, amplified hearing, and communications back to the control area. This suit is designed to increase the odds of survival for technicians should munitions or bombs detonate while they are near it.

Rarely, the specifics of a munition or bomb will allow the technician to first remove it from the area. In these cases, a containment vessel is used. Some are shaped like small water tanks, others like large spheres. Using remote methods, the technician places the item in the container and retires to an uninhabited area to complete the neutralization. Because of the instability and complexity of modern bombs, this is rarely done. After the munition or bomb has been rendered safe, the technicians will assist in the removal of the remaining parts so the area can be returned to normal. All of this, called a Render Safe Procedure, can take a great deal of time. Because of the construction of devices, a waiting period must be taken to ensure that whatever render-safe method was used worked as intended.

Another technique is Trepanation, in which a bore is cut into the sidewall of a bomb and the explosive contents are extracted through a combination of steam and acid bath liquefaction of bomb contents.[20]

Although professional EOD personnel have expert knowledge, skills and equipment, they are not immune to misfortune because of the inherent dangers: in June 2010, construction workers in Göttingen discovered an Allied 500 kilogram bomb dating from World War II buried approximately 7 metres below the ground. German EOD experts were notified and attended the scene. Whilst residents living nearby were being evacuated and the EOD personnel were preparing to disarm the bomb, it detonated, killing three of them and injuring 6 others. The dead and injured each had over 20 years of hands-on experience, and had previously rendered safe between 600 and 700 [unexploded bombs](https://en.wikipedia.org/wiki/Unexploded_ordnance). The bomb which killed and injured the EOD personnel was of a particularly dangerous type because it was fitted with a delayed-action chemical fuze, which had become highly unstable after over 65 years under ground.[21][22][23][24]

EOD equipment
Portable X-ray systems

EOD training and material testing. A 105 mm shell is radiographied with battery powered portable X-ray generator and flat panel detector.
Portable X-ray systems are used to radiograph the bomb before intervention. The purpose is for example to determine if a chemical charge is present or to check the status of the detonator. High steel thickness requires high energy and high power sources.

Projected water disruptors

Boot Banger water charge disrupts simulated bomb

Bottler Lite against a small suspect device
Projected water disruptors use a water-projectile shaped charge to destroy bombs, blasting the device apart and severing any detonating connections faster than any fuse or anti-tampering device on the bomb can react. One example is the BootBanger, deployed under the rear compartment of cars suspected to be carrying bombs.[25] Projected water disruptors can be directional, such as the BootBanger; or omni-directional, an example being the Bottler.[26]

Pigstick
Pigstick is the British Army term for the waterjet disruptor commonly deployed on the Wheelbarrow remotely operated vehicle against IRA bombs in the 1970s. It fires a jet of water driven by a propellent charge to disrupt the circuitry of a bomb and disabling it with a low risk of detonation. The modern pigstick is reliable and can be fired many times with minimal maintenance. It is now used worldwide. It is 485 millimetres (19.1 in) long and weighs 2.95 kilograms (6.5 lb).[27] It is made of hardened steel, and can be mounted on a remotely operated vehicle (ROV). These factors make it an effective way to render IEDs safe. It is not a panacea however, it can not deal with IEDs packed in hard containers like industrial gas bottles or beer kegs, for instance, and other disruptors have been designed to deal with those and a range of other situations including car bombs.

The name pigstick is an odd analogy coming from the verb meaning "to hunt the wild boar on horseback with a spear."

The device was developed by the scientists Mike Barker MBE and Peter Hubbard OBE at RARDE Fort Halstead in late 1971[28] working under great pressure over a period of several weeks after an ATO died in Northern Ireland attempting to render safe the first IED in the theatre to contain anti-handling devices.[29][30]

They started with a prototype equipment designed to disrupt limpet mines attached to a ship's hull and through a process of many trials and error developed a disruptor that could deal with the crop of IEDs with anti-handling devices prevalent at the time. Barker used the device operationally for the first time in Northern Ireland during a visit there to demonstrate their prototype to George Styles and his team.[31] The Pigstick prototype was re-engineered by a member of Hubbard's team, Bob White MBE, down from its original 20 kg to its current 2.95 kg form but its internal ballistic design remained true to the original.

...in the period 1972–1978, and taking into account machines which had been exported, over 400 Wheelbarrows were destroyed while dealing with terrorist devices. In many of these cases, it can be assumed that the loss of a machine represented the saving of an EOD man's life.

— House of Commons Hansard Debates for 21 Oct 1998[32]
ZEUS
The ZEUS-HLONS (HMMWV Laser Ordnance Neutralization System), commonly known as ZEUS, was developed for surface land mines and unexploded ordnance (UXO) neutralization by the U.S. Naval Explosive Ordnance Disposal Technology Division (NAVEODTECHDIV). It uses a moderate-power commercial solid state laser (SSL) and beam control system, integrated onto a Humvee (HMMWV), to clear surface mines, improvised bombs, or unexploded ordnance (UXO) from supply routes and minefields.

Bomb containment chamber

A bomb containment chamber
There are a wide range of containment chambers available. The simplest are sometimes danger suppression vessels that merely contain some of the fragments generated by the explosion. The other end of the spectrum features top-of-the-line gas-tight chambers that can withstand multiple shots while remaining able to contain chemical, biological, or radioactive agents. Containment chambers of all types may be fitted onto towed trailers, or specialised EOD vehicles.

EOD suits
Main article: Bomb suit
There is a long history of IEDD within the UK and protection for this role has evolved over the years. Starting with the Mk1 in 1969, in response to the Maoist Terrorist threat in Hong Kong, through to the Mk 2 in 1974, in response to the IRA threat in Northern Ireland (NI), with further developments of the Mk3 in 1980 to include a new helmet. The Mk4 EOD Suit, introduced into service in 1993, combines fragmentation and blast protection that is prioritised over the most vulnerable parts of the body (head, face and torso). The current system, MKV/VI, was introduced in 2004, and was a combined MOD/NP Aerospace project. The only part of the body that has no protection at all is the hands.[33]

See also
TEDAX are the Spanish organization that organizes the personnel trained in bomb disposal.
52nd Ordnance Group (EOD)
11 Explosive Ordnance Disposal and Search Regiment RLC
Fares Scale of Injuries due to Cluster Munitions
Advanced Bomb Suit
Anti-handling device
Clearance diver
Demining
Explosive Ordnance Disposal Badge
Fuse (explosives)
Gegana a special police unit of Indonesia specializing in the field of bomb disposal in the country.
Naval mine
Navy EOD
EOD CoE
Overpressure
Vivian Dering Majendie, one of the first experts on bomb disposal
Charles Howard, 20th Earl of Suffolk, an early expert of the Ministry of Supply Experimental Squad charged with defuzing German bombs with unknown (new) [fuzes](https://en.wikipedia.org/wiki/Fuze)
Bluestone 42, a U.K. Television series about a bomb disposal team in Afghanistan.
Danger UXB, a 1979 UK television series about British sappers during the Second World War
The Hurt Locker, a 2009 film about [U.S. Army](https://en.wikipedia.org/wiki/United_States_Army) bomb-disposal experts in Iraq. It was directed by Katherine Bigelow, and won the Academy Award for Best Picture.
Ten Seconds to Hell, a.k.a. The [Phoenix](https://en.wikipedia.org/wiki/Phoenix_(mythology)), a 1959 film about a German [bomb](https://en.wikipedia.org/wiki/Bomb) disposal team in post-war Berlin.

**Comment by jxckUK** [comment]
Expo is coming soon.
