### ISSUE TITLE
[BUG] These RTPC Cars Dont Have ANPR 

### ISSUE THREAD

**Issue by ItzDunley** [LondonsBlueLine/tracker#259]
Volvo V90
Volvo V60
Vauxhall Astra Mk7 
Mitsubishi Shogun

**Comment by telboycafc** [comment]
Hello, so the astra does not have an ANPR camera fitted to the vehicle, so technically it is not an ANPR car. This also applies to the V60. The other 2 have had ANPR now put on them. 

Thanks for bringing this to our attention. If the are any more vehicles with ANPR cameras fitted to the car that don't have ANPR then please let us know via here again.
