### ISSUE TITLE
Spawn points

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#26]
Give the option when spawning in for what station/location you want to spawn in at also not sure if it has been changed already but when spawning as LAS it puts at Pillbox when the uniforms are at the Ambulance Station

**Comment by Dale1987** [comment]
@Kyymather spawn points are randomised between the stations we have interiors at the moment. This is to split up everyone so not everyone spawns at the same place.

I believe LAS now only spawns at the ambulance station to retrieve their vehicles and uniforms.

**Comment by jxckUK** [comment]
@KyHewitt / @WolfRanger88 - Please could you review existing spawn points in the configuration and ensure they're correct then close this one up?

**Comment by WolfRanger88** [comment]
Pillbox hospital has now been removed from spawn location until interiors have been added.
