### ISSUE TITLE
New civilian addon vehicle registration

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#265]
Probably already crossed your mind but being able register the new custom civ vehicles in the cad system.

**Comment by CalLBLRP** [comment]
@jxckUK

**Comment by jxckUK** [comment]
- [ ] Add civilian vehicles into the naming logic
- [ ] Add civilian vehicles to server vehicles spreadsheet - @WolfRanger88
- [ ] Add new values to the CAD
