### ISSUE TITLE
Improved Health System

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#267]
It would be great to have a script that would allow you to bleed out.
Example: You get Stabbed at legion square and you try to make your escape by walking along. This leaves a trail of blood behind you. Your walking is slow. By the time you make MRPD you would have bled to death. If stabbed multiple times then obviously you go down as you do now.
This requires police to have good response time, LAS response also.
This can then allow DSU to make use of a blood dog that can search for blood trails.

**Comment by jxckUK** [comment]
I like it, approved - but its a big task so I'm going to migrate it to our internal roadmap.
