### ISSUE TITLE
New dog models

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#268]
_## Issue created anonymously for a user ##_
I would like the husky replaced with a more suitable dog. I have looked for models like a spaniel etc but was unable to find any available and the models are expensive. I found this pack with has different colours which imitate belgian malinous and a Shepard. Potentially being able to replace the husky with this or making the Shepard atm changeable skins to give a bit variety.

**Comment by jxckUK** [comment]
https://www.lcpdfr.com/downloads/gta5mods/character/19996-german-shepherd-malinois-k9-dog/

**Comment by jxckUK** [comment]
@WolfRanger88 - Pretty sure you had a look at this, what was the outcome?

**Comment by WolfRanger88** [comment]
@jxckUK For some reason I cannot get the german shepherd to spawn different skins. I have not been able to find alternative models.

**Comment by BA98x** [comment]
Can only of the skins preferably the black or black faced dog replace the husky and have the best say police firearms support
