### ISSUE TITLE
DSU EUP - SGT/INSP Uniforms

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#271]
_## Issue created anonymously for a user ##_
Currently there is no inspector or sgt dsu uniforms. Could they be created please

**Comment by jxckUK** [comment]
@CalLBLRP - In the absence of new DSU EUP, could you see if we can provision versions with epaulettes?

**Comment by telboycafc** [comment]
@CalLBLRP @jxckUK not sure where or how this one is going. Does this need an external Modder to do ?

**Comment by jxckUK** [comment]
Not sure - we just need to review possible options on it

**Comment by CalLBLRP** [comment]
Hi there @lucane1999, 

Unfortunately, the current vest doesn't allow us to adjust the vest to put ranks on. However, we have found a vest that will allow us to add ranks to it which can be found at - https://sinnersmodshop.com/collections/dsu/products/south-yorkshire-style-dog-vest.

Thanks!

**Comment by jxckUK** [comment]
Switching this to requires funding, will need to wait until next months funding round.

**Comment by jxckUK** [comment]
Archiving - stale request.
