### ISSUE TITLE
Rope Rescue & Decom Tent

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#272]
_## Issue created anonymously for a user ##_
I think we could possibly add the rope rescue and the Decontamination Tent because for the tent we do have a chemical fire in game which would be for chemicals and i think this could go further with the rp on that call they are both on this website https://store.londonstudios.net/category/1704957 and i think the rope rescue could be good for the technical side of things for LFB since we could save people from the top of a building with this feature safely i also think it would be good for the department and server for Roleplays

**Comment by telboycafc** [comment]
Theses are things we have looked at and will want to get. As always with funding, we need to make sure the server costs are covered first and foremost so everyone can continue to enjoy the server. We will then assess the funds left over and give priority funding to what ever has been prioritised first. 

So yes, we do want to get all this in, but a time frame cant be given at the moment as we can not say when we will have the funds as most of it goes towards the server running costs at the moment.

**Comment by jxckUK** [comment]
This has had funding *pending* the appointment of an LFB Commissioner.

**Comment by telboycafc** [comment]
Update - Funding has been granted for this, awaiting LFB commissioner to confirm if this is a resource needed now or not.

**Comment by telboycafc** [comment]
rope and rescue have been purchased. Decom tent will be considered in future budgets, so will close this out for now.
