### ISSUE TITLE
Smart Motorways

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#273]
_## Issue created anonymously for a user ##_
Maybe could add the smart motorways from London studios to help with the addition of highways England https://store.londonstudios.net/

**Comment by jxckUK** [comment]
As with other suggestions at the moment we do not have the funding required for this.

**Comment by jxckUK** [comment]
This has not had funding approved this round.

**Comment by telboycafc** [comment]
Something for the future for sure. At the moment it's not a priority as NHW is not server wide released yet. So will close this for now, but is something we are aware of.
