### ISSUE TITLE
Police medic bag

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#277]
_## Issue created anonymously for a user ##_
https://store.state-zero.com/products/ems-kit

**Comment by SplendidBrit** [comment]
need this pack for some LAS items aswell!

**Comment by jxckUK** [comment]
This has received funding and will be purchased shortly.

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/180414735-997c241f-d98b-4400-989f-c828eade85c9.png)

In development ready for a merge.
