### ISSUE TITLE
Possible LAS Kit Bag

### ISSUE THREAD

**Issue by SplendidBrit** [LondonsBlueLine/tracker#280]
https://store.state-zero.com/products/emas-backpack

A very nice kit bag that comes as a prop and an EUP item. Would need a slight reskin to remove the "EMAS" marking which would be easy to do!

Not technically the realistic LAS model but only one available that is prop and EUP (Most are only EUP)

**Comment by jxckUK** [comment]
This has received funding and will be purchased shortly.

**Comment by jxckUK** [comment]
This has not received funding approved this round.

**Comment by jxckUK** [comment]
Cancelled as we have a suitable replacement.
