### ISSUE TITLE
New LAS Ambulance

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#281]
New fiat ambulance with enterable interior from union mods https://unionmods.com/?p=viewfile&file=729

_If approved, to go into Advanced Paramedic please._

**Comment by CalLBLRP** [comment]
Hello @MrJC9, 

Thank you for your request. This has now been added into the Development Server and has indeed **passed** QC. 

The vehicle has been added into the Advanced Paramedic garage and will be seen in main when we push all of the updates on a restart.
