### ISSUE TITLE
BTP Equipment [BUG]

### ISSUE THREAD

**Issue by AAlpha101** [LondonsBlueLine/tracker#283]
Issue with BTP Equipment - nothing is showing when you head to the locker.

**Comment by CalLBLRP** [comment]
@jxckUK 

Could be an issue in locker config when we were changing it all over to it's separated department?

**Comment by jxckUK** [comment]
Already fixed in https://github.com/ProjectHyde/ProjectHyde/commit/eb9cc3c949bc80d9230b01736f3932cef520174c
