### ISSUE TITLE
Btp dogs

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#284]
_## Issue created anonymously for a user ##_
The BTPD role is gone and BTP officers are unable to retrieve a dog

**Comment by Lucane1999** [comment]
Now BTD > officers can retrieve dogs at MRPD.

**Comment by jxckUK** [comment]
> Now BTD > officers can retrieve dogs at MRPD.

BTD is the new role, this is now correctly associated with the vehicles. At this time, there is nowhere at that BTP hub that you *could* access dogs so head over to MRPD once you've collected your vehicle.
