### ISSUE TITLE
RTPC SEG Request 

### ISSUE THREAD

**Issue by StubbsyH** [LondonsBlueLine/tracker#288]
Hello, 

I have had authorisation to move SEG to RTPC and theres a few things that need moving, Firstly there is a few changes to the uniform, to start, just use the scorpion uniform as a template as they are very similar, only changes being shirt number needs to change from 194 to 196, and then hands to 17 on the Civ menu to put gloves on, this will be the SEG Uniform and it would be amazing if this could be put in the locker under SEG tag

![SEG uniform](https://user-images.githubusercontent.com/108938328/178001043-44b19a16-649f-4cda-8526-ab1ba98b0532.png)

The second change that needs making to the garage already attached to the seg tag is the marked BMW Bike (BMW 1200RT) needs removing from the Garage as its not a SEG vehicle,  The other 2 Vehicles (Umrked Bike & Land Rover Disco) can stay as they are in the garage theses 2 vehicles are perfect

Training docs will be developed once these changed have been approved by the dev team (silver are aware of the SEG development) All these changes need to be put onto the Existing SEG Tag on discord , if possible could we prepare to release applications for SEG on the website once docs are developed and approved by Silver and these changes have been made 

Thank you 
RI1 Stubbsy

**Comment by CalLBLRP** [comment]
All done in Dev server -> awaiting to be pushed to main for completion of SEG overhaul.
