### ISSUE TITLE
PTA Callsign

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#295]
My suggestion is to give PTA officers a PA Callsign that would not affect any other Callsign so won't be put in the names or cad however when they are authorising a pursuit they will say pursuit authorised under Callsign PA XX this is so that all officers in the pursuit are aware that the pursuit authorising it is allowed to

**Comment by MrJC9** [comment]
Wouldn’t this cause confusion with LAS callsigns? Callsigns for Paramedics are already P XX with plans to have AP XX (_and further variations of P callsigns for Paramedics_).
Just a suggestion but wouldn’t RT XX be a better solution (Roads Tactical)?

**Comment by Kyymather** [comment]
Yeah didn't think of that one but yeah RT XX would be better

**Comment by jxckUK** [comment]
Closing this out as this was put to the RTPC inspector who is responsible for this. Please re-confirm with the RTPC inspector.
