### ISSUE TITLE
Bronze white XC90 ANPR 

### ISSUE THREAD

**Issue by Fleggy123** [LondonsBlueLine/tracker#298]
The bronze Command white XC90 needs to have ANPR on it please and thank you.

**Comment by CalLBLRP** [comment]
Hiya @Fleggy123, 

Just a quick question, is it **both** the XC90s or just 1 of them? 

Thanks!

**Comment by Fleggy123** [comment]
Hiya @CalLBLRP 

Its just the white one the other one has it mate :)

Thanks!
