### ISSUE TITLE
Early access

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#3]
Add a early access for donators so they can try out the new things being added before they are released

**Comment by jxckUK** [comment]
@Kyymather - This is something we really want to do and is on my planned agenda. We'll be moving our development to a custom server and once that frees up the existing one we can open it up to whitelisted donators.

I'll put a timeframe on this to keep me honest! Planned to release by: **12th Feb**

**Comment by jxckUK** [comment]
@Kyymather - Little update on this one as we've made a change of decision. At this time, while updates are coming fast and we don't want to drag players from the main server. We're not going to add an EA server.

We're going to moving to two new servers in the next week with automatic pipeline updates so we should be able to increase the frequency of updates pushed.

When we're a bit larger and have more scope we'll review again.
