### ISSUE TITLE
New BTP vehicles

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#304]
https://discord.com/channels/743957820906668103/935650399229181962/939324950433660988 Marked S mas 
https://discord.com/channels/743957820906668103/935650399229181962/935661041864540270 Ford Mondeo marked 
https://discord.com/channels/743957820906668103/935650399229181962/935670835841224735  Unmarked S max
https://discord.com/channels/743957820906668103/779700298260021258/827983520524795904  Insignia unmarked 
Me and Alpha are willing to fund.

**Comment by jxckUK** [comment]
What servers are these from bud I can't click any of the links

**Comment by jxckUK** [comment]
Requested - pending funding.

**Comment by telboycafc** [comment]
@jxckUK where are we at with this suggestion ?

**Comment by jxckUK** [comment]
Just awaiting a response and funding which has been pending for a while - Alpha has kindly agreed to contribute the cost of the vehicles so once we have that we can close this item out.
