### ISSUE TITLE
New Civ Cars

### ISSUE THREAD

**Issue by DunleyS** [LondonsBlueLine/tracker#305]
- Tesla https://www.gta5-mods.com/vehicles/tesla-model-x-p90d
- Tesco Truck https://www.gta5-mods.com/paintjobs/uk-british-tesco-groceries-delivery-van-iveco
- Ford Focus https://www.gta5-mods.com/vehicles/ford-focus-rs-2017-add-on-replace-tuning-template-multi-livery

I Think these would be good and make better more realistic rps for civs and police

**Comment by WolfRanger88** [comment]
Tesco truck is a no go as the model is not to standard. We will review the tesla and focus.
