### ISSUE TITLE
Btp medic bag

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#307]
Make this a prop or something that can be carried for btp medics

https://www.unionmods.com/?p=viewfile&file=567

**Comment by jxckUK** [comment]
This is a zModeller asset and not something that is plug and play into the server. However Antony might be able to assist on his return.

**Comment by BA98x** [comment]
The medic bag that has been purchased is fine if we could get access to the kit

**Comment by SplendidBrit** [comment]
As above, new police medic bag is now available
