### ISSUE TITLE
Backup 

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#31]
_## Issue created anonymously for a user ##_
When you go to a knife call and the main officer has been stabbed and other officers get on sence the ai gose after the other officer not the mian officer who accept the call becuse its just boring when the dead officer get healed and we are not on the same call then we get more out of the calls.

**Comment by WolfRanger88** [comment]
This is something that will need to be scripted within callouts in fivepd and therefore requires C# knowledge to get around it.

**Comment by jxckUK** [comment]
As above - this will be resolved in our interaction / callout replacement project.
