### ISSUE TITLE
[BUG]cant load the sig with ammo as BTP

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#312]
BTP primary firearm is the SIG and atm we are unable to load ammo into it, Jack reckons its because its locked to CTSFO, can BTP AFO have it to them please

**Comment by jxckUK** [comment]
Had to replace the weapon, seems to be an issue with that particular model.

Fixed in https://github.com/ProjectHyde/ProjectHyde/commit/723935b06d8030bbf887a3149aeae272439b4947
