### ISSUE TITLE
RNLI LifeBoats

### ISSUE THREAD

**Issue by therealJiko** [LondonsBlueLine/tracker#313]
Every day of every year, people of all backgrounds get into danger in the water. It’s a problem that we’re here to tackle.

Today, with [your support](https://rnli.org/support-us), we are working harder than ever to end preventable drowning. In addition to our 24/7 search and rescue lifeboat service, we operate a seasonal lifeguard service. Every year, our volunteer lifeboat crews and lifeguards help and rescue thousands of people and have saved over 143,900 lives since 1824. Countless more lives are saved through our youth education and water safety work.

In an ideal world, no one would suffer the devastating loss of a loved one to drowning. We’d reach everyone with our water safety advice. If anyone got into trouble, they’d know what to do until help arrived. And our lifesavers would always have everything they need to reach them in time and save lives. #

**Comment by jxckUK** [comment]
RNLI is something we'd very much like to introduce *in the future* and at the moment there are too many things ahead of this in the schedule including National Highways.

As such this item is closed until we reach a point where we can tackle it.
