### ISSUE TITLE
New Vehicle Requests

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#320]
https://www.gta5-mods.com/vehicles/met-police-volvo-xc90-els

https://www.gta5-mods.com/paintjobs/2017-metropolitan-police-volvo-xc90

https://unionmods.com/?p=viewfile&file=756

From Char5

**Comment by CalLBLRP** [comment]
This will be looked into in 72 hours.

**Comment by CalLBLRP** [comment]
Hi Char, 

Thank you for your suggestion, please view the below on how your suggestion went: 

**Suggestion Outcome**
Your suggestion was considered. However, I could only get 1 of the vehicles in the game and working as it should be. The vehicle that I got working was the Volvo V90. The other 2 vehicles which were the Volvo XC90 doesn't work and is unable to be loaded into the server. 

We thank you for your suggestion, sorry that the XC90 didn't end up working. 

- Cal
