### ISSUE TITLE
[FEAT]BTP Volvo

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#321]
Can this be added to btp garage :)

https://www.gta5-mods.com/vehicles/2010-volvo-v70-british-transport-police-arv-els

**Comment by CalLBLRP** [comment]
This will be looked into 72 hours.

**Comment by CalLBLRP** [comment]
Hi Gibby, 

Thanks for your suggestion. The vehicle has now been added into the dev server and has been added to the garage. This will be pushed to main when possible. 

Thank you again, 
Cal.
