### ISSUE TITLE
BTP ranks 

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#322]
Add more ranks to the BTP vests

**Comment by CalLBLRP** [comment]
This will be looked into within 72 hours.

**Comment by telboycafc** [comment]
@CalLBLRP any update on this please ?

**Comment by jxckUK** [comment]
We're working on this in conjunction with Tramter's patches to see if we can come up with a permeant solution to these requests.

**Comment by BA98x** [comment]
This been done yet?

**Comment by jxckUK** [comment]
Our current BTP vest does not support this - we would need a new vest to do so. Closing this out, if you find an alternative vest open another issue and we can look into it.
