### ISSUE TITLE
RCT Uniforms 

### ISSUE THREAD

**Issue by DunleyS** [LondonsBlueLine/tracker#323]
Hello,
Jack Said put this on GitHub Can these get added to The BCU Locker Image 1 is RCT Long Sleeve Image 2 Is RCT I also think that the hands need changed as they clip a bit Short Sleeve 
![C63DCA22-75D3-42DB-919D-4029A79AF998](https://user-images.githubusercontent.com/109606660/180616903-4ff027e2-6637-4cb2-ae14-f5d630c668bc.png)

![AA8933CC-1623-419F-919E-E7E4EBCE4854](https://user-images.githubusercontent.com/109606660/180616865-b68fea47-164b-499a-b949-ec36c0d2fbe3.png)

**Comment by CalLBLRP** [comment]
These will be done within 72 hours.

**Comment by CalLBLRP** [comment]
Hi there, 

Thank you for your suggestion. 

However, you have provided the same screenshot twice. Please provide the hats downwards configuration. 

Thanks,
Cal.

**Comment by CalLBLRP** [comment]
Hello There,

Thank you for your suggestion. 

This has now been added to dev server and will be pushed to main server when ready.

Keep the suggestions coming.

Cal.
