### ISSUE TITLE
CAD clocks users off after in game action

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#327]
> Every time i use the F7 menu to change state, its putting me off duty on the cad every time. I was running as LFB.
> I have to go on the cad site and put me back state 2 otherwise it wont spawn any fires.
> also does this when accepting call through the game, attaches me to the call but also takes me off duty on the cad.

**Comment by telboycafc** [comment]
@jxckUK any update on this ?

**Comment by jxckUK** [comment]
> @jxckUK any update on this ?

Yes - I think I've triaged this to "inactivity" after 15 minutes the CAD clocks someone off if they haven't updated their status using F7 etc.

I'll add something in on every update tick to do *something* to the user so it keeps them active.
