### ISSUE TITLE
Armed Dog Unit - DSU 

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#329]
I would like to open ADU.
I am aware it was implemented or was going to be implemented before.
I believe I will need a ADU role on discord with weapons and a uniform to suit.

Please can this be created as I am keen to push this application live.
I have created three uniforms (have used the command in dev). I made two and S3 made one.
I think ADU should receive glock 17 only.

**Comment by Lucane1999** [comment]
I have sent commands for EUP. I submitted one and S3 did.

**Comment by Lucane1999** [comment]
3 uniforms in total for now. thanks.

**Comment by jxckUK** [comment]
{ "ADU", "ADU 1", "mps", 121, 0, 92, 0, 152, 0, 0, 0, 25, 0, 0, 0, 130, 0, 57, 0, 0, 0, 437, 0, 170, 0}
{ "ADU", "ADU 2", "mps", 121, 0, 188, 0, 152, 2, 0, 0, 25, 0, 0, 0, 130, 0, 57, 0, 0, 0, 434, 2, 170, 0}
{ "ADU", "ADU 3", "mps", 121, 0, 188, 0, 152, 2, 0, 0, 25, 0, 152, 0, 213, 0, 69, 1, 133, 0, 435, 3, 170, 0}

**Comment by Lucane1999** [comment]
Change CTD > ADU and provide that role with only a Glock 17 as long as there is a SFC role present.

**Comment by CalLBLRP** [comment]
Hi @Lucane1999, 

This has been added to the dev server, all works fine. Should be pushed to main on the next update.

Keep the suggestions coming!
