### ISSUE TITLE
[FEAT] Garage Modification 

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#33]
Any chance for the SEG garage to come out of the SFC garage and become a primary garage like BCU, SFC, RTPC, CPU etc. Due to the recent changes that is happening with SEG which have been authorised by Jack and the other Execs in the meeting a few weeks ago. 

Within this garage could you please put a marked and unmarked bike with the unmarked land rover from SFC garage please.

Love you <3 :)

**Comment by jxckUK** [comment]
Fixed by @KyHewitt
