### ISSUE TITLE
Garage organisation for DSU

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#331]
Please can the garages be as follows?

DSU BASIC
Ford Mondeo, VW T6,

ADVANCED
Ford Focus Marked, BMW 530D, SKODA SUPERB, SKODA OCTAVIA VRS, Ford Transit

EXPO SUPPORT
UNMARKED FOCUS, FORD TRANSIT UNMARKED,

FSD
VOLVO V90 UNMARKED, Skoda KAROQ Unmarked, Mercedes VITO

ADU
Skoda Kodiaq VRS MARKED, Skoda Superb UNMARKED, Volvo V90 Marked, BMW 530D UNMARKED

**Comment by Lucane1999** [comment]
Push live once CTD changed to ADU.

CTD has been abolished.

**Comment by CalLBLRP** [comment]
This has been completed.
