### ISSUE TITLE
Vehicles NEW

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#332]
Would these pass and be able to be put into the game? 

https://www.gta5-mods.com/paintjobs/british-police-dog-k9-unit-ford-connect-van-arv-regular

https://www.gta5-mods.com/vehicles/british-police-vw-touran-anpr-dog-unit-els

thanks

**Comment by CalLBLRP** [comment]
Unfortunately, none of these links pass QC. Please view your Discord Direct Messages for the reasoning behind it. 

Keep the suggestions coming!
