### ISSUE TITLE
LAS Vehicles 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#336]
Can I request the following LAS vehicles (some are skins): 

**HART**
https://www.gta5-mods.com/paintjobs/las-land-rover-discovery-4

**HEMS**
https://www.gta5-mods.com/paintjobs/air-ambulance-skin-for-bmw-2-series

**Doctor**
https://www.gta5-mods.com/vehicles/volvo-xc70-ambulance-rrv

**Clinical Team Manager**
https://www.gta5-mods.com/paintjobs/bmw-2-series-ambulance-grand-tourer

**Comment by CalLBLRP** [comment]
Hi there @MrJC9, 

All of these vehicles have been tested in the Development Server. However, they do not pass Quality Check. The models are dodgy with the lightbar or the skin isn't to what we aim towards to have for the server. 

Keep the suggestions coming!
