### ISSUE TITLE
New btp car

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#338]
Could this be added to the btp garage please :) https://unionmods.com/?p=viewfile&file=772

in real life we have this vehicle as part of our electric fleet review so would be cool to replicate that in game.

**Comment by CalLBLRP** [comment]
Hi there @Gibby543, 

The vehicle has been added to dev and passes QC. The vehicle has been added to the garage config as well. 

Thanks for the suggestion, keep them coming!
