### ISSUE TITLE
[BUG] NPAS Helicopter

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#34]
**Describe the bug**
You cannot enter the NPAS Helicopter, there is an error from 'ph-garages' when you spawn the helicopter in too. Please check below

**To Reproduce**
1. Go to 'Sinner Street Police Station Helicopter Spawnpoint'
2. Click on 'Police National Air Service'
3. Go onto 'NPAS'
4. Press 'Yes'
5. See error

**Expected behaviour**
You should be able to enter the helicopter and the error shouldn't appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/98986766/153062780-ac7afaf3-3845-47e7-8517-8db451cd29e8.png)

**Additional context**
Nothing important other than.. god sake jack ;)

**Comment by jxckUK** [comment]
Fixed in be9a646!
