### ISSUE TITLE
New interceptor cars

### ISSUE THREAD

**Issue by Fleggy123** [LondonsBlueLine/tracker#340]
Hi,

Can the new cars also get added to the ANPR script as well.

Many Thanks 
Rhys

**Comment by CalLBLRP** [comment]
Hi There @Fleggy123, 

Please specify which vehicles need ANPR because Antony went through all of the new vehicles and added ANPR to them. Make sure that the camera is visible on the car in order to get the ANPR fitted. 

Thanks

**Comment by Fleggy123** [comment]
Hey,

I was told that they didnt have them ive checked my self and they do actually have them so you can delete this ticket now. 

Many thanks 

Rhys
