### ISSUE TITLE
LFB Prime Movers

### ISSUE THREAD

**Issue by SplendidBrit** [LondonsBlueLine/tracker#345]
https://www.alienmodding.co.uk/catalogue/bundle-listings/man-prime-mover-s

Here are the two LFB Prime movers. Nice high-quality models and would be a good addition to LFB.

There are loads of good fire vehicles on here but they are all VERY pricey.

**Comment by telboycafc** [comment]
Nice vehicles, hefty price... Can be kept open for the future once we get millions in donations. Not something we can afford to allocate the budget to at the moment.

**Comment by jxckUK** [comment]
Purchased, added, closing.
