### ISSUE TITLE
LMT Defender - Updated Model

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#346]
https://www.alienmodding.co.uk/catalogue/weapon-listings/lmt-defender

This is the best one and most accurate for btp.

**Comment by telboycafc** [comment]
Will keep this open for future consideration. At the moment, no budget prioritised for it at the moment as a matter of urgency.

**Comment by BA98x** [comment]
i can provide cash

**Comment by jxckUK** [comment]
Ordered

**Comment by jxckUK** [comment]
Purchased, added, closing.
