### ISSUE TITLE
[FEAT] Postal Tracker

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#35]
**Is your feature request related to a problem? Please describe.**
When there are civs online, it is a bit hard to track a postal down that they have given intel for us to go and see. An example would be: "Clown van @ 8934".. it would be helpful for a /postal or /p command that will get the postal from the map and provide you a waypoint.

**Describe the solution you'd like**
/postal or /p command that will get the postal from the map and provide you a waypoint.

**Describe alternatives you've considered**
Finding the postal on the map, doing this way takes a long time as you have to look really hard for the postal. 

**Additional context**
Nothing :)

**Comment by jxckUK** [comment]
Approved - I will add to the roadmap as a P1 item.

Transferring to Project Hyde.
