### ISSUE TITLE
TSG CAD

### ISSUE THREAD

**Issue by DunleyS** [LondonsBlueLine/tracker#350]
So I was thinking as the TSG callsigns irl is U 
 then 3 numbers I was wondering if you merged people on cad as TSG it would generate a random 3 number callsign for them to use as TSG would this be possible

**Comment by jxckUK** [comment]
Possible - yes

Practical - no, at the moment until we have everyone in the game "check in" what division they are running this isn't something we can do. But, I'll track it on our internal roadmap and we'll add it in.
