### ISSUE TITLE
TSG EUP

### ISSUE THREAD

**Issue by DunleyS** [LondonsBlueLine/tracker#351]
This is some new TSG EUP that looks good and i know it requires alot of funding just as its on sale at the moment and all of the helmets and things are corresponding for what TSG have ie: Red Command, Blue Normal officer so on and so forth 

I know its expensive so it could just be on the waiting list i just put it up as its on sale for £65 to £30. Or maybe something like this if it could be found 

https://sinnersmodshop.com/products/public-order-3d-eup-pack?_pos=1&_sid=98bd35f16&_ss=r

Or Maybe This but it is £25 just for the helmet 
https://mirrorparkstudios.co.uk/products/metropolitan-police-nato-riot-helmet-public-order?_pos=2&_sid=c427d5519&_ss=r

Enjoy Your Day,
Dunley

**Comment by telboycafc** [comment]
Very expensive, it's not declined just at the moment it's a lot for what can be allocated budget wise. So will keep this open to be looked at in the future.

**Comment by jxckUK** [comment]
Archiving - stale request.
