### ISSUE TITLE
DSU Spawner

### ISSUE THREAD

**Issue by DunleyS** [LondonsBlueLine/tracker#352]
Can we get a DSU Spawner  at every station as we cant get our dogs unless we spawn at MRPD

**Comment by telboycafc** [comment]
I will look at this time and work permitting.

**Comment by jxckUK** [comment]
@telboycafc / @WolfRanger88 - Can you YMAP in the same building we've put at BTP hub for the other stations?

**Comment by Lucane1999** [comment]
+1

**Comment by telboycafc** [comment]
being worked on, davis and heathrow are done and ready for dogs to spawn there.

**Comment by telboycafc** [comment]
la masa has spare doors that could be used.

**Comment by colossalengineer** [comment]
> being worked on, davis and heathrow are done and ready for dogs to spawn there.

- [ ] Davis PD
- [ ] Heathrow
- [ ] La masa
- [ ] Paleto
- [ ] Sandy

**Comment by telboycafc** [comment]
DSU spawn has been placed at every station now. Some will have portacabins in place, La Mesa will be a door in a seating area. All pictures have been provided in DSU chat.
