### ISSUE TITLE
Training venue additions

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#354]
I think Antony was onto it but could a car spawner be put inside the training building and a couple train carriages be added

**Comment by telboycafc** [comment]
Wolf is currently on holiday. I'm sure he will pick this up when he is back.

**Comment by WolfRanger88** [comment]
I will take a look over this week and see what is available. I will also add a garage function in the building once I have added carriages etc.

**Comment by WolfRanger88** [comment]
Car spawn location is outside the building for driving back to location after training.
