### ISSUE TITLE
Desync 

### ISSUE THREAD

**Issue by Fleggy123** [LondonsBlueLine/tracker#355]
Hi,

The desync on the sever recently has gotten very bad and I don't know what is it but alot of people have said it the last few days. 

Many thanks

Rhys

**Comment by jxckUK** [comment]
We'll see if we can triage this as a priority.

**Comment by jxckUK** [comment]
This is not resolved - we're looking into it as a priority.

**Comment by WolfRanger88** [comment]
@Fleggy123 Closing this one following our discussion in VC and your mention that Desync had been resolved. Please let us know if any issues re-occurs.
