### ISSUE TITLE
Btp guns locked to AFO tag and cars locked to the tags

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#356]
Can the BTP AFO weapons be locked out to the tag along with the unmarked vito and xc70.

Osu uniform and carrier to the OSU tag too

**Comment by jxckUK** [comment]
The weapons are locked out no?

**Comment by Gibby543** [comment]
Not actually sure?  Could the Mach E get added to a BTP Sliver command garage?

**Comment by jxckUK** [comment]
Moved to SRU as discussed
