### ISSUE TITLE
EUP additions

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#360]
new response vest and long sleeve shirt. A more tidy hi vis vest in my opinion with no clipping issues(compared to current) and a long sleeve black police shirt, something we don't have anything like currently. 

vest- £12.50
shirt- £5.00

https://sinnersmodshop.com/collections/response/products/south-yorkshire-style-high-visibility-vest-sc20-d5

https://sinnersmodshop.com/collections/police-shirts/products/long-sleeve-wicking-polo-shirt

**Comment by telboycafc** [comment]
Needs to be reviewed in the Budget. One to keep open, It's not a no. Just no time frame at the moment.

**Comment by jxckUK** [comment]
Will need to wait until next months funding round.

**Comment by Bettercal** [comment]
Brilliant thank you

**Comment by Bettercal** [comment]
Hi guys just wondered if there is an update on getting this in? If the funding required has submerged I can fund it 👍🏼

**Comment by CalLBLRP** [comment]
Hiya bud, 

I'll speak to the rest of the team and come up with a plan. We will get back to you soon!

**Comment by jxckUK** [comment]
@telboycafc - Can you order these when you're next around, we have funding available.

**Comment by telboycafc** [comment]
ordered, just waiting for them to send files...they don't rush.

**Comment by telboycafc** [comment]
done .
