### ISSUE TITLE
Speed Gun

### ISSUE THREAD

**Issue by Fleggy123** [LondonsBlueLine/tracker#362]
Good morning,

I think adding this will allow for some good RP for the RTPC guys as its something that would be done in real life and its another thing that they could do in some of the divisions where they don't do a lot of chases or for the IPT guys that can only start pursuits but cant do the tactical phase.

https://forum.cfx.re/t/release-radargun-laser-gun-v1-1-huge-improvements-and-new-ui/179682

Many thanks 
Rhys

**Comment by Lucane1999** [comment]
+1 would like to see this.

**Comment by telboycafc** [comment]
I personally like this. Good for setting up speed trap operations that can be done with a small team at any time.

**Comment by jxckUK** [comment]
Yeah nice idea - tracking internally at P2.

https://github.com/ProjectHyde/ProjectHyde/issues/111
