### ISSUE TITLE
[FEAT] NEW LFB COMMAND VEHICLE

### ISSUE THREAD

**Issue by StubbsyH** [LondonsBlueLine/tracker#364]
Hello there, 

We have had a heated discussion with Jack regarding unmarked officer Vehicles for LFB, He has said he is happy for these 2 vehicles linked bellow to go in, (providing they pass QC) we are yet to decide which garage they are too go in , so please could they just be put in and be made ready to be moved into the correct garage once roles have been decided by LFB command. 

https://www.gta5-mods.com/vehicles/audi-q7-police-politie-unmarked-els-replace

https://www.gta5-mods.com/vehicles/volkswagen-polo-r-line-police-politie-unmarked-els-replace

Kind Regards,
Stubbsy

**Comment by jxckUK** [comment]
Only factor I hadn't considered is driving side but frankly at this point it's _probably_ fine.

**Comment by CalLBLRP** [comment]
Hi there, 

1/2 cars passed QC, the car that passed QC was the Audi. The golf failed QC due to a dodgy model. This should be added to the main next update.

Keep the suggestions coming!
