### ISSUE TITLE
[FEAT] New Vehicles / Garage Changes for LFB

### ISSUE THREAD

**Issue by StubbsyH** [LondonsBlueLine/tracker#365]
Hello there, 

We have yet a few more requests for you, 
-Firstly , we would like to have the old ategos added to the game and potentially used as a donator perk for LFB, If this idea isnt accepted , we like them putting under the 'BA' tag, once created (pack is bellow)

https://www.gta5-mods.com/vehicles/london-fire-brigade-mk1-mk2-atego-pack

-Secondly, we would like to  create garages attached to all three of the Command tags (Operational Command, Tactical Command, Strategic Command) and have some vehicles  added in, all the vehicles ,where they need to go and the Spawn Codes are following

Operational Command- 
Vauxaul Zaffiera- LFB15  
BMW X5- LFB11 

Tactical Command- 
BMW- LFB13
Skoda- LFB14

Strategic Command- 
Audi Q7- LFB16
Mercedes Sprinter- LFB02

Thank you very much 
F1 , F2

**Comment by telboycafc** [comment]
with the exception of the donator vehicle. The rest has been done.

**Comment by telboycafc** [comment]
@CalLBLRP has all of this been completed ?

**Comment by CalLBLRP** [comment]
almost @telboycafc

**Comment by CalLBLRP** [comment]
This has been completed, the donator vehicles will be in at another time due to the fact we are needing to do get a new handling line for them otherwise it will not pass QC. We will keep you updated. 

Thanks!
