### ISSUE TITLE
[FEAT] Custody alarm

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#366]
Custody alarm at the police stations

**Comment by colossalengineer** [comment]
A button on a wall that locks the cell doors and sounds an alarm

**Comment by telboycafc** [comment]
To be reviewed by LT/ dev team. This could get abused and messed around with but i like the idea. @leadershipteam

**Comment by jxckUK** [comment]
Yeah fine as a concept, decent idea - moved to internal roadmap. Low Priority.
