### ISSUE TITLE
Bels script

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#369]
This Ballistic Emergency Life Support Script & EUP is a brilliant way to create in-depth roleplay and enhance it. This script provides Ballistic Emergency Life Support bag (Useable without the script).  

This script also allows the bag to be removed from vehicles (of your choice in the config file) and placed on the ground / picked up with relevant animations.

The Config file allows you to change the bags Slot (Bags and Parachutes, Shirt Overlay etc) and the number within that category (1,2,3, etc). You can also add vehicles allowed for the BELS kit to be removed. Example - ARV1. 

Video of Release:
https://streamable.com/udfnlf

It's from officer Galvin mods. Could be added to all the cars bit better than the current bag

**Comment by jxckUK** [comment]
We'll extend the bag internally to support boot retrieval and placement but one to track on our internal roadmap.
