### ISSUE TITLE
[FEAT] SFC EUP Update

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#37]
**SFC 1** - NEW NAME
https://prnt.sc/26sf8q2 - WHAT IT SHOULD LOOK LIKE
__CONFIG__
- https://prnt.sc/26rln3g
- https://prnt.sc/26rlnf8

**SFC 2** - NEW NAME
https://prnt.sc/26sfayn - WHAT IT SHOULD LOOK LIKE
__CONFIG__
- https://prnt.sc/26rlw2i
- https://prnt.sc/26rlwae

**SFC 3** - NEW NAME
https://prnt.sc/26sffec - WHAT IT SHOULD LOOK LIKE
__CONFIG__
- https://prnt.sc/26rm1ur
- https://prnt.sc/26rm2dk

**SFC 4** - NEW NAME
https://prnt.sc/26sfhyg - WHAT IT SHOULD LOOK LIKE
__CONFIG:__ 
- https://prnt.sc/26rmifc 
- https://prnt.sc/26rmiqr

> Love you tel <3

**Comment by jxckUK** [comment]
@telboycafc - Can you review this see if you can put it into config?

**Comment by telboycafc** [comment]
This has been completed.
