### ISSUE TITLE
Trains [BUG]

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#370]
Trains always stop when you approach them. They cannot pass through when a player is nearby to them.

train in sandy shore was rubber banding into same position and blocked the track indefinitely

**Comment by WolfRanger88** [comment]
This has been tested today on an RP in game and train did not stop on tracks when players on tracks. To stop train, Cones were needed to be put on track by BTP so as yet we have been unable to replicate the issue. Train continued journey on removal of cones.

**Comment by BA98x** [comment]
You are only able to stop the underground tube trains. The actual trains will continue and not stop for people and/or signs or another obstacles
