### ISSUE TITLE
BTP Uniforms

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#372]
{ "BTPConstable", "plain clothes", "mps", 121, 0, 1, 0, 1, 5, 0, 0, 31, 1, 185, 0, 0, 2, 75, 0, 0, 0, 167, 11, 170, 0}
{ "BTPConstable", "plain clothes 2", "mps", 121, 0, 1, 0, 4, 2, 0, 0, 31, 0, 185, 0, 0, 0, 75, 0, 0, 0, 191, 0, 170, 0}

**Comment by jxckUK** [comment]
{ "Operational Support", "Level 1 PSU", "mps", 169, 0, 17, 0, 165, 0, 0, 0, 24, 0, 184, 0, 210, 0, 74, 1, 135, 0, 454, 0, 126, 0}
{ "Operational Support", "Level 2 PSU", "mps", 0, 0, 17, 0, 165, 0, 0, 0, 24, 0, 184, 0, 210, 0, 74, 1, 135, 0, 454, 0, 170, 0}
{ "Dog Section", "Short Shirt", "mps", 0, 0, 0, 0, 165, 0, 0, 0, 24, 0, 184, 0, 211, 0, 74, 1, 135, 0, 449, 0, 170, 0}
{ "Firearms", "Firearms Tactical", "mps", 199, 0, 4, 0, 166, 0, 0, 0, 25, 0, 188, 0, 213, 0, 78, 0, 138, 0, 454, 0, 196, 0}
{ "Response", "County Lines and DRU", "mps", 121, 0, 0, 0, 4, 0, 0, 0, 9, 0, 184, 0, 211, 0, 74, 1, 135, 0, 132, 0, 170, 0}
{ "Response", "Disruption 2", "mps", 121, 0, 0, 0, 0, 0, 0, 0, 31, 1, 184, 0, 211, 0, 74, 1, 135, 0, 242, 0, 170, 0}

**Comment by BA98x** [comment]
Why these got MPS on the ends should it not be BTP?

**Comment by Gibby543** [comment]
Ignore the Firearms Tactical

**Comment by BA98x** [comment]
Created new Firearms tactical and other Firearms uniforms. Gibby has created OSU and DRU uniforms

**Comment by colossalengineer** [comment]
{ "Firearms", "Firearms Tactical", "mps", 169, 0, 17, 0, 166, 0, 0, 0, 25, 0, 188, 0, 213, 0, 78, 0, 0, 0, 456, 0, 196, 0}
{ "Response", "PCSO", "mps", 121, 0, 0, 0, 35, 0, 0, 0, 25, 0, 184, 0, 15, 0, 73, 1, 135, 0, 412, 1, 198, 0}
{ "Firearms", "Firearms 3", "mps", 121, 0, 11, 0, 166, 0, 0, 0, 25, 0, 0, 0, 213, 0, 78, 0, 0, 0, 435, 0, 170, 0}

**Comment by colossalengineer** [comment]
{ "Firearms", "Firearms 2", "mps", 121, 0, 16, 0, 166, 0, 0, 0, 25, 0, 188, 0, 213, 0, 78, 0, 0, 0, 454, 0, 170, 0}

**Comment by WolfRanger88** [comment]
Now pushed to development server for QC check in lockers

**Comment by WolfRanger88** [comment]
QC Checked and pushed
