### ISSUE TITLE
BOMB vest for civ

### ISSUE THREAD

**Issue by Bettercal** [LondonsBlueLine/tracker#373]
https://mirror-park-studios-scripts.tebex.io/package/5149300

£9.59

good Civ RP could come from this instead of having to use proximity mines

**Comment by telboycafc** [comment]
I actually like the idea of this, cheap too. Big old back log of things to be done though. Will let the others chip in too.

**Comment by jxckUK** [comment]
This is just a script and to be honest, £10 for something that executes an explosion is pretty steep.

I've got an EUP vest and appropriate code to put this in, I just need some time - I'll move this to the internal roadmap.
