### ISSUE TITLE
SFC Uniforms

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#374]
{ "", "covertctsfo1", "mps", 169, 0, 197, 0, 4, 0, 0, 0, 51, 0, 177, 0, 0, 1, 0, 0, 0, 0, 7, 1, 189, 0}
{ "", "covertctsfo1", "mps", 169, 0, 197, 0, 4, 0, 0, 0, 51, 0, 177, 0, 0, 1, 0, 0, 0, 0, 7, 1, 189, 0}
{ "", "afo1", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 0, 0, 0, 455, 1, 190, 0}
{ "armed response vehicle arv", "afo1", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 0, 0, 0, 455, 1, 190, 0}

**Comment by colossalengineer** [comment]
{ "close protection officer cpo", "DPG1", "mps", 0, 0, 4, 0, 152, 0, 0, 0, 97, 0, 0, 0, 213, 0, 58, 0, 0, 0, 393, 0, 167, 0}

**Comment by colossalengineer** [comment]
{ "counter terrorism ctsfo", "ctsfo blue band", "mps", 52, 0, 197, 0, 166, 4, 0, 0, 102, 0, 188, 2, 213, 0, 76, 0, 0, 0, 454, 4, 194, 0}
{ "armed response vehicle arv", "OFC1", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 0, 0, 0, 455, 6, 190, 0}
{ "counter terrorism ctsfo", "ctsfo covert 2", "mps", 0, 0, 15, 0, 63, 0, 0, 0, 24, 0, 0, 0, 38, 0, 0, 0, 0, 0, 167, 7, 170, 0}

**Comment by colossalengineer** [comment]
{ "counter terrorism ctsfo", "ctsfo covert 3", "mps", 121, 0, 14, 0, 4, 2, 0, 0, 97, 0, 0, 0, 213, 0, 76, 0, 0, 0, 332, 18, 170, 0}

**Comment by colossalengineer** [comment]
{ "bronze command arv", "sergeant armed", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 1, 0, 0, 455, 7, 190, 0}
{ "bronze command arv", "sergeant OFC", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 1, 0, 0, 455, 9, 190, 0}
{ "bronze command arv", "inspector", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 2, 0, 0, 455, 10, 190, 0}
{ "bronze command arv", "inspector OFC", "mps", 169, 0, 92, 0, 167, 0, 0, 0, 25, 0, 177, 0, 205, 0, 79, 2, 0, 0, 455, 11, 190, 0}

**Comment by colossalengineer** [comment]
{ "counter terrorism ctsfo", "red band", "mps", 52, 0, 197, 0, 166, 4, 0, 0, 102, 0, 188, 3, 213, 0, 76, 0, 0, 0, 454, 4, 194, 0}

**Comment by WolfRanger88** [comment]
All now in dev awaiting QC

**Comment by jxckUK** [comment]
Moved to QC: https://github.com/LondonsBlueLine/qc/issues/7
