### ISSUE TITLE
Ambulance Suction Unit 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#375]
Portable Suction Unit for LAS to enhance RP 
https://www.lcpdfr.com/downloads/dev-resources/vehicle-parts/40145-boscarol-ob-1000-portable-suction-unit/

**Comment by jxckUK** [comment]
Unfortunately bud this is a dev model and we don't have the ability/skills to bring this model into the game as an object/weapon etc.

I like the idea, and its a good concept but as it stands we can't execute.
