### ISSUE TITLE
Rural Crime Team Uniforms

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#376]
{ "Long Sleeved", "Rural Crime Team", "mps", 0, 0, 14, 0, 35, 0, 0, 0, 25, 0, 179, 0, 195, 0, 61, 0, 0, 0, 409, 0, 170, 0}
{ "Short Sleeved", "Rural Crime Team", "mps", 0, 0, 15, 0, 35, 0, 0, 0, 25, 0, 179, 0, 195, 0, 61, 0, 0, 0, 449, 0, 170, 0}

**Comment by WolfRanger88** [comment]
Added, will be available next restart
