### ISSUE TITLE
CT CARS

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#377]
Land Rover Defender (MPS194) Not found in any garage, Range Rover SVR (Unmkd) (MPS122) SRO vehicle, Kawasaki 1400 GT (MPS83) from RTPC

**Comment by WolfRanger88** [comment]
Above is approved for config change and push. Approved by 1 LT (A2), 1 Gold (Z2) & 1 Silver (S3). @colossalengineer can you please action and close out ticket or post any other vehicle requests into this ticket so we can review and approve/decline. Thanks

**Comment by colossalengineer** [comment]
DONE
