### ISSUE TITLE
window rifle for SFC

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#378]
this allows the AFO's to point there firearm out of the window which helps when performing vehicle tactics and lowering the chance of a suspect getting away . https://unionmods.com/?p=viewfile&file=194

**Comment by jxckUK** [comment]
Thanks for the suggestion - I've reviewed this a few times before:

https://github.com/LondonsBlueLine/tracker/issues/166

Unfortunately that resource isn't a drag and drop, the ability for this to be carried out in a non-GTA style drive-by isn't as simple as it seems.

I took the decision a while ago that this would be knocked off the agenda. We may re-review at a later date but at this time it's not something we're looking to add.
