### ISSUE TITLE
new arv x5 pack 

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#379]
these are different x5's to what we have in the garage already and have been requested my many members https://www.gta5-mods.com/vehicles/metropolitan-police-bmw-x5-f15-arv-pack

**Comment by jxckUK** [comment]
There is almost certainly a *reason* why they aren't in already as these have likely been QC'ed already. However I don't recall so happy for them to be re-QC'ed if they have been through already.

Worth mentioning that you have far too many X5s at the moment so is this request to replace existing ones?

**Comment by CalLBLRP** [comment]
moved to https://github.com/LondonsBlueLine/qc/issues/2 and https://github.com/LondonsBlueLine/qc/issues/3
