### ISSUE TITLE
[FEAT] Content Creator perks 

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#38]
As a content creator there is a few things we cannot do in the server unless there is a moderator online. The things that can help us are: 
- Recording Options.
- Spawn in cars to setup for scenes that we can record or take pictures of. 

These 2 things will be able to help us massively to create good videos and pictures of the server for Social Media.

**Comment by Dale1987** [comment]
This will be a negative to the cars spawning as youd need to have access to TX admin. You will also be able to use rockstar editor for recording videos

**Comment by Dale1987** [comment]
Oh plus you have your own modding menu

**Comment by jxckUK** [comment]
Closing this issue as I've transferred Rockstar Editor to the roadmap.
