### ISSUE TITLE
BTP uniform lockers

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#380]
Hello, 
can these uniforms please be added to these lockers where are the tags Response DRU OSU and firearms please

**Response - Constable tag**

Standard
Sgt
Jacket

**DRU** 

County line and DRU
Disruption 2

**OSU** 

OSU jacket
OSU shirt
Level 1 PSU
Level 2 PSU
Plain clothes 
Plain clothes 2

**Dog Section - BTD**
Jacket 
Shirt

**Firearms - AFO**

Firearms uniform (can it be renames Firearms 1)
Firearms 2
Firearms 3
Firearms Tactical 1
Firearms Tactical 2

and could the tags reflect the vehicle lockers if they already do not thanks.

**Comment by CalLBLRP** [comment]
moved over to https://github.com/LondonsBlueLine/qc/issues/15
