### ISSUE TITLE
Wont allow me to select force on main server

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#381]
wont allow me to select a force on the main, works fine in dev,
https://gyazo.com/d5dd30c102866c7ebf8ea796584d6cbf

**Comment by jxckUK** [comment]
This is due to the new role that needed to be created for BTP command members, the servers errored out because it isn't aware of this role. This is patched in the latest version but the only fix for now is to await the restart at 14:30 or remove the role until then.

**Comment by jxckUK** [comment]
xToolkit updated on live to: [45028d1](https://github.com/jxckUK/xToolkit/commit/45028d1d199c8fd3b3d9ed997a9ed4941e585386)
