### ISSUE TITLE
LAS Motorbike

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#384]
LAS Motorbike https://unionmods.com/?p=viewfile&file=373

If this gets approved it will form part of an MRU or Motorcycle Response Unit so please could this get added into a new MRU Garage with an associated MRU tag. In addition (if the above bike is approved), can the Motorbike Paramedic Uniform (Biker) and current Motorbike (LAS07) be moved from Advanced Paramedic into this MRU garage/locker. 

Thanks.

**Comment by CalLBLRP** [comment]
This has been added to the Development Server, awaiting QC. This may take a while as we are currently updating a few things which affect the QC process. 

Thanks!

**Comment by jxckUK** [comment]
Moving to QC: https://github.com/LondonsBlueLine/qc/issues/4
