### ISSUE TITLE
LAS Advanced Paramedic Defib 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#385]
There’s an issue with the advanced paramedic defib where it won’t attach to the player when retrieved from a vehicle. It seems to be predominantly in areas where there are lots of players/vehicles so it means in RP scenes the defib is unusable. In these situations when you go to any LAS vehicle to retrieve the defib it will not attach to the player but upon leaving the area or returning to the LAS station when you exit the vehicle it will then attach to the player but you will be unable to place it back in a vehicle so it’s stuck on the player. 

In areas where there are little to no players/vehicles the defib is retrievable most of the time, but when arriving on scene in these high traffic areas it’s unable to be retrieved. 

I can provide a video if needed, but Colossal has also seen the bug happen while playing as LAS.

If there isn’t a straightforward fix may I suggest allowing all divisions to access the basic Paramedic Defib **_alongside_** the Advanced Defib. So the basic defib could be called ‘defibrillator’ and the advanced called ‘LifePak’ but both together only retrievable by Advanced Paramedic or higher. (Only as a temporary measure so AP and above can access a defib)

**Comment by colossalengineer** [comment]
I'm going to make the defib load in memory on load up. Hopefully this with fix the issue

**Comment by jxckUK** [comment]
> I'm going to make the defib load in memory on load up. Hopefully this with fix the issue

Did this work?

**Comment by telboycafc** [comment]
@colossalengineer was this fixed ?
