### ISSUE TITLE
New LAS Station 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#388]
A new station for LAS. This is a new station in a new location to be added alongside the current LAS station.

This is coming from Her Majesty's Studios: https://discord.gg/mFVkqTz7

A link to the page that shows the station: https://discord.com/channels/759466471985905665/976613161836879932

This Station is on Sale currently for £15 for an unknown amount of time. Me and J. Oatway are willing to cover the costs of this splitting it £5 from me, and £10 from Oatway as he is halving that with Davis Mikey.

The below screenshot shows the sale price:
![bandicam 2022-08-30 19-45-05-157](https://user-images.githubusercontent.com/102492709/187518129-5532e2db-3c01-4d75-bea2-94fbee075748.jpg)

**Comment by jxckUK** [comment]
I've ordered as funding is being provided externally, just let me know once they've been funded in the communitys PayPal and I'll get it purchased.

**Comment by MrJC9** [comment]
Both amounts for this have been paid into the community PayPal - transaction confirmation below:

My Amount of £5
![bandicam 2022-08-30 21-15-07-562](https://user-images.githubusercontent.com/102492709/187534958-fb6b6ef0-ab2d-4604-8f98-d565417b1c5e.jpg)

J. Oatway's Amount of £10
![bandicam 2022-08-30 21-16-41-856](https://user-images.githubusercontent.com/102492709/187534984-50048442-830f-4a2e-be6a-6bcd7b52393d.jpg)
(_He accidentally made it a monthly donation in error, he is aware_)

**Comment by jxckUK** [comment]
Thanks guys!

Pending tasks:

- [ ] QC
- [ ] Spawn Configuration
- [ ] Fast Travel Configuration
- [ ] Garages / Parking Spaces
- [ ] Lockers & Armoury

**Comment by jxckUK** [comment]
This item will now be moved to QC:

https://github.com/LondonsBlueLine/qc/issues/1
