### ISSUE TITLE
New LAS HART Vehicle - **Limited Time offer 24 hours**

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#389]
2022 Toyota Hilux [Hazardous Area Response Team]

Currently on sale on United Modifications for £10 for the next 24 hours. I'm willing to cover the cost on this as we need more vehicles in the HART garage. 

United Modifications Discord: https://discord.gg/zscYbMgm

Link to the listings page: https://discord.com/channels/970769255073198100/971462081784213514

Link to vehicle listing: https://discord.com/channels/970769255073198100/971462081784213514/1014237485217370112

If you guys can review and let me know what you guys think, like I say happy to cover the cost of it.

**Comment by CalLBLRP** [comment]
Hiya @MrJC9, 

If you are able to cover the costs, we are happy for you to do so. Let us know the transaction id, I also agree that we are needing HART vehicles. 

Thanks!

**Comment by MrJC9** [comment]
@CalLBLRP All done! I've sent the funds into the community PayPal, transaction reference as below:

![bandicam 2022-08-30 22-24-46-380](https://user-images.githubusercontent.com/102492709/187546285-1a8c23aa-d007-4dd3-9172-44c777014fdf.jpg)

**Comment by CalLBLRP** [comment]
Hiya @MrJC9, 

Thank you for doing that, we have put in the request for the vehicle. Will give you an update when we have got the files!

**Comment by CalLBLRP** [comment]
Hi there, this has passed QC. Amendments have also been added to the building like the locker and garage followed by the parking spaces. 

Enjoy, this will be added to main soon!

**Comment by CalLBLRP** [comment]
Quick update, 

We are getting sent the files later on today. 

Will keep you updated when we have recieved them!

**Comment by jxckUK** [comment]
Moving to QC: https://github.com/LondonsBlueLine/qc/issues/5
