### ISSUE TITLE
BMW X5 GO5 Merit

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#394]
(https://discord.gg/kPrCA9Kn)

(https://discord.com/channels/808483775448481812/907706188274229359/928392215007490049)

I'm willing to pay for this and jack has told me he wants this for doctor.

**Comment by CalLBLRP** [comment]
Hi there,

We have now recieved this vehicle, we will add it to the server as soon as I have the files for it. 

Sorry for the long wait.

**Comment by CalLBLRP** [comment]
moved over to https://github.com/LondonsBlueLine/qc/issues/17
