### ISSUE TITLE
LAS Unmarked XC90

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#395]
(https://discord.com/channels/808483775448481812/907706188274229359/1006295196784398367)

I'll Pay again for this

**Comment by CalLBLRP** [comment]
Hi there, 

If you wish to purchase this vehicle, you are more than welcome to. As normal, send us the exact amount of money through to our paypal which can be found [here](https://tinyurl.com/yckvunus).

Please let us know the transaction ID when sent OR attach a screenshot of the transaction.

Thank you!

**Comment by colossalengineer** [comment]
![image](https://user-images.githubusercontent.com/81814321/187728224-876bb2ea-4b44-4b4c-ab63-2c2f3152ed76.png)

**Comment by CalLBLRP** [comment]
Thank you, we will try and get your request processed as quickly as we can. Please make yourself known our request times for vehicle requests; we ask that you give us an estimated time of **1 week** to get your request processed and qcd. 

We will keep you updated on the progress.
