### ISSUE TITLE
Content Server

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#396]
Can you add both of the new weapons and new eup please

**Comment by jxckUK** [comment]
Issue with the pipelines, resolved now. Weapons and EUP should be live.

**Comment by viiidal** [comment]
> Issue with the pipelines, resolved now. Weapons and EUP should be live
there in no eup in the server now apart from the basic

**Comment by viiidal** [comment]
@jxckUK ^^

**Comment by jxckUK** [comment]
Waiting for it to finish uploading

**Comment by viiidal** [comment]
ah ok no problem
