### ISSUE TITLE
Underground and overground station markers and labels for map.

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#398]
It was previously spoke about getting blips and names on the map for each of the stations as they have been named but unless you have it written down they are difficult to locate.
Stations are;
 
Knightsbridge station - 8175

9051 on Olympic freeway (unsure name)

Hammersmith station - 8254 and 8246 

Hatton Cross - 10037 and 10038 

Heathrow Terminal 4 - 10026 and Heathrow 10025

There is additional that have been named and I sent a map ages ago to jack and collosal.

Can these be added to the map please to assist people looking for them 🙂

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/187888602-a2bcc99b-3a1e-4098-ad09-1771edeef0fe.png)
