### ISSUE TITLE
Depot and siding locations

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#400]
Evening,

The blips for the underground is ace. one was missing it was at 9127 and its called Davis but I'm sure it got named something else.

could blips be added for the following may like the station sign as these are the normal stations.

8041 mirror park rail depot

3062 palmer Taylor power station 

3053 Davis quartz (quarry)

2050 union road sidings 

1023 - 1025 paleto bay sidings

8189 - Popular street Depot

10110 - Jet sam cargo Terminal

10057 - Port of South LS sidings

thanks :)

![image](https://user-images.githubusercontent.com/108870150/188018680-8d317c83-d721-49dd-9162-a4bb4299de98.png)
like that

**Comment by jxckUK** [comment]
https://docs.fivem.net/docs/game-references/blips/

Can you pick a blip for these, I would use the image attached but it won't fit in with the game style and I cannot find a suitable replacement.
