### ISSUE TITLE
No access to BTP command cars

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#401]
at the minute BTP command cant access the command cars for us, could this be looked into.

**Comment by CalLBLRP** [comment]
Hello, 

The reason for this was due to the separation of roles, this will be looked move to our low priority list for now.

Thanks.

**Comment by CalLBLRP** [comment]
Good Evening, 

We are aware that some perms are missing, we will look into this when we can. 

The reason for this was due to the separation of roles.

Thanks!

**Comment by jxckUK** [comment]
Access has been granted for now via the SLT tag whilst inheritance is amended.

**Comment by CalLBLRP** [comment]
This has now been fixed in the inheritance now as well, please be patient for the new inheritance to be pushed into the main server.
