### ISSUE TITLE
LFB Spreaders [BUG]

### ISSUE THREAD

**Issue by StubbsyH** [LondonsBlueLine/tracker#402]
Hello,

Im not sure if its meant to be like this, but the spreaders have changed on main, have collisions and dont put away and get stuck in the users hands causing a forced relog, please could this bug be looked at 

Thanks
Stubbsy

**Comment by jxckUK** [comment]
Hm, this shouldn't have happened as LondonStudios resolved this issue and I pushed them yesterday in: https://github.com/LondonsBlueLine/resources/commit/aea35e8a5fdfeec93284ca83c846979ba91019cc

I'll need to review.

**Comment by jxckUK** [comment]
Looks like they didn't properly fix it when updated. I've reverted the update until we've confirmed its properly fixed.
