### ISSUE TITLE
[FEAT] New things / Changes for LFB

### ISSUE THREAD

**Issue by StubbsyH** [LondonsBlueLine/tracker#403]
Hello (again)

First of all, a request for BA being put in the new trucks, please could it be put in LFB22 and LFB23 

Secondly , can the new equiptment we have in game be added to the E menu inside the truck (the one that was used to replace the boot) the following equiptment is what we were hoping to get in there; 
Throwbag
Water Monitor 
BA Board
Thermal Imaging Camera

Next, The fires on LS customs script need tweaking to make them easier to put out, and it needs doing for all types of fires, as some of them are near impossible to put out,  which isnt realistic

Finally , please could we have All the fire start/stop perms etc put onto the stragic command role (aka LFB gold) so we can do other things to enhance RP

Thank you and sorry for bombarding you
Stubbs

**Comment by jxckUK** [comment]
Water Monitor & BA Board are slightly more complex than face value. As it stands they place the object where you're standing at any one time and they aren't carried, so collecting them from a vehicle requires additional thinking and development. I'm knocking these items back into the internal roadmap.

All the remaining items have been complete, awaiting testing.
