### ISSUE TITLE
Traffic Warden

### ISSUE THREAD

**Issue by therealJiko** [LondonsBlueLine/tracker#404]
Traffic wardens are employees of police forces and are primarily responsible for controlling traffic in general using powers available to authorised persons defined in the Road Traffic Act 1988.

**Comment by jxckUK** [comment]
Every 3 months I look forward to the random Jiko request that contains nothing except from a brief copypasta from wikipedia about some random division he wants to see.

RTPC serve most traffic policing in LBL RP and National Highways is on our agenda.
