### ISSUE TITLE
SDU EUP

### ISSUE THREAD

**Issue by Dunley0** [LondonsBlueLine/tracker#405]
Hello,
I was wondering if its possible for jacket 406 get reskined on just the blue part to say "Police Drone Operator" as this is what it is irl
![Screenshot 2022-09-02 190121](https://user-images.githubusercontent.com/112723501/188212536-8ad37b6b-62a9-4c59-bfc5-19cd2b88105a.png)
![R](https://user-images.githubusercontent.com/112723501/188212580-d4be95aa-47fa-4348-aacb-514c46cd92eb.jpg)

Kind Regards, 
Dunley

**Comment by jxckUK** [comment]
We would need to seek authorisation for this from the creator - if we can achieve that we may be able to do something yes.
