### ISSUE TITLE
DSU Cars

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#406]
https://rellent.co.uk/product/2018-volkswagen-caddy-dog-unit-unmarked

**Comment by colossalengineer** [comment]
If you buy it

**Comment by Lucane1999** [comment]
https://www.gtainside.com/en/gta5/cars/96345-metropolitan-police-mercedes-sprinter-dog-section

**Comment by CalLBLRP** [comment]
Hi there,

Unfortunately, the sprinter automatically fails QC. The vehicle doesn't have any extras which means that it has no ELS installed on the vehicle. 

Keep the suggestions coming! PS: IF you wish to purchase the first vehicle, please let us know!
