### ISSUE TITLE
DSU Ford Focus Unmarked

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#407]
I think the unmarked Focus for DSU has either had an update or got bugged when adding into LBL.
https://www.gta5-mods.com/vehicles/2019-ford-focus-pack-marked-unmarked-dog-cars-generic-els

It does not change colour, however the model was tested and it does in fact change colour so may need repairing/looking at/updating.

**Comment by CalLBLRP** [comment]
Unfortunately, we are unable to proceed with this vehicle. We aren't able to seek the permission of using the vehicles as the creator requires us to seek permission before using in any communities. The creator no longer has a Discord server and cannot be found on Discord anymore. 

Sorry.
