### ISSUE TITLE
TFO EUP

### ISSUE THREAD

**Issue by Dunley0** [LondonsBlueLine/tracker#408]
Hello,
Myself and kenz are wondering if the NPAS TFO Eup could be changed to this 
![unknown](https://user-images.githubusercontent.com/112723501/188231150-7fbc3013-764c-4994-ab02-0993cca69801.png)
![Screenshot 2022-09-02 213051](https://user-images.githubusercontent.com/112723501/188231215-fbe4998c-17f8-41ec-ac56-0f9641076de6.png)
Many Thanks,
Dunley & Kenz

**Comment by CalLBLRP** [comment]
Hiya @Dunley0, 

With EUP update it will be a lot easier if you did "saveeup" when one of us are around so all we have to do is copy a line of code. I will be around at some point later on tomorrow morning (3rd September) so you can catch me in the morning or in the afternoon. 

Thanks,
Cal.

**Comment by jxckUK** [comment]
It also saves in a file that I can retrieve for whoever is working on it!

**Comment by Dunley0** [comment]
@CalLBLRP i have done /saveeup but idk what else to do is that of any help

**Comment by Dunley0** [comment]
@CalLBLRP Put it in saveeup in F8 thanks to better cal helping me and also put in the one of the SDU Uniforms :)

**Comment by CalLBLRP** [comment]
This has been moved over to https://github.com/LondonsBlueLine/qc/issues/16
