### ISSUE TITLE
New MO19 unmarked vehicle 

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#411]
I recently suggested a BMW X5 f15 unmarked that did not pass QC but I believe I have found a much better model this vehicle is also used commonly by mo19 and in well known community’s I few links for you guys to choose from https://unionmods.com/?p=viewfile&file=719  https://unionmods.com/?p=viewfile&file=624

**Comment by CalLBLRP** [comment]
Hi there, 

1 of 2 vehicles were able to be put in for QC, https://unionmods.com/?p=viewfile&file=719 was the vehicle that has been placed upon for QC. The other vehicle auto failed QC due to the rear reds. 

This issue has now moved over to: https://github.com/LondonsBlueLine/qc/issues/9
