### ISSUE TITLE
ADU uniform

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#413]
I have just submitted the saveeup command for KI1 Lucane on a ADU uniform.

**Comment by jxckUK** [comment]
{ "ADU", "Firearms Dogs", "mps", 0, 0, 8, 0, 167, 0, 0, 0, 25, 0, 0, 0, 122, 0, 57, 0, 0, 0, 455, 1, 194, 0}

**Comment by CalLBLRP** [comment]
This has been moved over to https://github.com/LondonsBlueLine/qc/issues/14
