### ISSUE TITLE
Chat Tags

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#414]
The CAD doesn't seem to update chat tags when in game. Seems it could be a potential bug or hasn't been created, however, as we have with MPS. Allow other departments command roles to have their role shown in the chat. 

Preview:
![image](https://user-images.githubusercontent.com/98986766/188675919-67192302-a4f1-4d07-873c-e5002258eba8.png)

**Comment by jxckUK** [comment]
This is resolved in the latest development build; it now pulls rank information from the CAD for the current spawned in force. Eg. I will be Commissioner if I am running as MPS but Police Constable if I am running as BTP.

These are now colour coded to match blip colours.
