### ISSUE TITLE
Hostage and Crisis Negotiator

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#415]
I had a green light from Jack for this and have been hard at work this morning to create.

SAVEEUP command is done, can we have this either as a standalone locker or under BCU

Can i have HCN role created Aswell as a garage with vehicles- MPS04 MPS08 MPS58

I have created training documents and an exam. This role will not require an application and will be handpicked by myself through a vote of interest. I would like to invite you to take a look at the training if required and will be sat in mr1 most of the day.

**Comment by jxckUK** [comment]
Moved to QC: https://github.com/LondonsBlueLine/qc/issues/12
