### ISSUE TITLE
New Silver vehicle

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#422]
**Describe the bug**
There's a small issue I don't know if your aware, when turning your lights off, it removes the beacon model but the light remains.

**To Reproduce**
1. Spawn from silver garage.
2. Hit Q 3 times and it will vanish.
3. Hit Q once more and the light will turn on.

**Comment by colossalengineer** [comment]
@JamStonedScones can you try it in dev for me i believe it might be fixed in there

**Comment by JamStonedScones** [comment]
@colossalengineer I would love to made but I dont have access

**Comment by colossalengineer** [comment]
@JamStonedScones Bug fixed on dev waiting for it to be pushed to main.

**Comment by JamStonedScones** [comment]
Thank you!
