### ISSUE TITLE
**On sale until 5pm** LAS Vehicles - *Limited time sale*

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#430]
Blue Light Modifications has the following 4 vehicles on sale until **5pm** for £5 each

Blue Light Modifications Discord:
https://discord.gg/a9gdy9Sk

Vehicles:
**Band A** - BMW G21 https://discord.com/channels/989567274350436382/1002364921360699525/1022448319877890060

**Doctor** - Mitsubishi Shogun (Doctor Lightbar) https://discord.com/channels/989567274350436382/1002364921360699525/1022448783822442546

**Band C** - Audi S4 https://discord.com/channels/989567274350436382/1002364921360699525/1022447909817561158

**Band C** - Volvo V60
https://discord.com/channels/989567274350436382/1002364921360699525/1022449359599714335

Happy to cover the costs for the above vehicles, I believe me and Jack Laity (Oatway) are both contributing for these, just let me know if we can get them in time.

**Comment by jxckUK** [comment]
All ordered and purchased, feel free to donate/contribute whenever you can if you want to! 

@CalLBLRP will pop them in shortly for QC.

**Comment by jxckUK** [comment]
This modding community closed down and we are unable to retrieve our purchase. Not a lot we can do here as we already paid for the resources, Cal is following up but, in the meantime, closing this out.
