### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Lucane1999** [LondonsBlueLine/tracker#431]
Crashing into the Telephone box at 8173 (Legion Sq/Strawberry Ave) causes a crash for any players nearby.

Tested multiple times and it causes crashes to players around the area as well as the player that has crashed into object.

https://medal.tv/games/gta-v/clips/CoiRXEF3L-aaE/d1337v7MXT3b?invite=cr-MSxvdzIsMTk3OTU2Njgs

**Comment by Lucane1999** [comment]
The one at 8166 does the same

**Comment by jxckUK** [comment]
Good work lads, great debugging and a concise video helps me nail the issue without drama.

Pushed attempted fix for testing to development branch.

**Comment by jxckUK** [comment]
Absolutely lamped one of these phone boxes and seems to be resolved. Re-open if it occurs again.

![image](https://user-images.githubusercontent.com/48030374/197336162-b2cac501-87ca-46c8-810b-0492d5f307c5.png)
