### ISSUE TITLE
EUP

### ISSUE THREAD

**Issue by MI1Kxnz** [LondonsBlueLine/tracker#432]
A couple weeks ago I was in the development server and created uniforms for RCT , I haven’t yet heard back and was just wondering whether you have an update or if they weren’t allowed

**Comment by CalLBLRP** [comment]
Good Afternoon @MI1Kxnz, 

Please bare with us in order to find the saved uniforms. 

We will respond back to you when we have located and them, if we cannot find them we will also contact you if you could provide screenshots of the uniforms you would like added to the locker.

**Comment by jxckUK** [comment]
{ "RCT", "Short Sleeved (Black vest)", "mps", 0, 0, 0, 0, 35, 0, 0, 0, 25, 0, 168, 0, 196, 0, 62, 0, 0, 0, 397, 0, 170, 0}
{ "RCT", "Long Sleeved (Black vest)", "mps", 0, 0, 0, 0, 35, 0, 0, 0, 25, 0, 168, 0, 196, 0, 62, 0, 0, 0, 409, 0, 170, 0}

**Comment by CalLBLRP** [comment]
This has now been added to the lockers, will be pushed to main on the next minor/major update.
