### ISSUE TITLE
LAS Tactical Commander Tabard 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#433]
London Ambulance Incident Tactical Commander Tabard from Sinners 

https://sinnersmodshop.com/collections/tabards/products/las-style-command-tabard-3d-eup-model

For plans to use this with the GM’s and Command Team to allow clear identification of who is ground command for LAS on large scenes and show who is the point of contact when other services wish to liaise with LAS

Uniform setups for this with existing uniforms to be discussed as and when this gets purchased

**Comment by jxckUK** [comment]
We can no longer accept suggestions relating to SMS due to their systems for encryption not be compatible with our internal EUP systems.
