### ISSUE TITLE
LAS Vauxhall Zafira

### ISSUE THREAD

**Issue by AP38Leon-cal** [LondonsBlueLine/tracker#435]
i would like this vehicle added to the London Ambulance service Advanced paramedic garage please

**Comment by Lucane1999** [comment]
Which vehicle @AP38Leon-cal as the link goes to a page with several.

**Comment by AP38Leon-cal** [comment]
the LAS vauxhall zafira

**Comment by Lucane1999** [comment]
https://shoppy.gg/product/Ente4p1

Thanks.

will need to pass funding by the bosses. They will update here.

**Comment by CalLBLRP** [comment]
Good Afternoon @Lucane1999,

If you are happy to fund for this vehicle, you are more than welcome to send it over via the paypal. 

The paypal can be found [here](https://www.paypal.com/donate/?hosted_button_id=XG35B88BLGMMN).

Kind Regards,
Cal.

**Comment by jxckUK** [comment]
Purchased pending addition.

**Comment by jxckUK** [comment]
Moving to https://github.com/LondonsBlueLine/tracker/issues/435
