### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by IOJJ10** [LondonsBlueLine/tracker#437]
**College of Policing:**
All trainers to be added at the moment BCU 
COP VC for trainers to speak in 
A chat for them all to speak in 
Information for me to put things in 
Later on when there for a section for Advance & basic trainer also for specilasit trainers so private chat channel not voice
Only people with either basic advanced or specialist can talk in the COP 
Header for the bit will be College (for civ its content)

**Comment by jxckUK** [comment]
Passed to Bronze Command as it is neither development nor asset based.
