### ISSUE TITLE
Mall MLO (Roleplay)

### ISSUE THREAD

**Issue by ttvkenzjohGC** [LondonsBlueLine/tracker#439]
I was just browsing earlier on and came across a nice looking mlo which I think would be good to enhance rp abilities and widen the range of calls that civs can do.

Preview/Showcase: https://www.youtube.com/watch?v=E8BFUzH-0dE
Discord: https://discord.gg/x73uRqMC

I know funding may not be there, but it is £15 which I believe is decent for the price

**Comment by jxckUK** [comment]
Closing this as funding is problematic at the moment and this isn't a good use of funds.
