### ISSUE TITLE
Limited Vmenu for civs.

### ISSUE THREAD

**Issue by therealJiko** [LondonsBlueLine/tracker#440]
During my honor-full time as a civilian on LBLRP I've come to realize...

Where would i get a green mini for my Mr. Bean RP 🤔

then it hit me...

CIVS NEED VMENU

We as CIVS need VMenu in order to properly stage and give a full illusion when acting as peds, This will be limited to cars only to stop  no-clip and|or gun spawning.

(P.S Jack find yourself lucky not for a wiki copy and paste)

**Comment by jxckUK** [comment]
Not required as you may register *any* vehicle (incl. a mini) in the CAD to your user and it will show up in your garage with your chosen number plate at PDM.
