### ISSUE TITLE
[FEAT] Speed up SFC X5 F15

### ISSUE THREAD

**Issue by Rellentless** [LondonsBlueLine/tracker#441]
**Is your feature request related to a problem? Please describe.**
Could we please make the X5 F15 in the ARV garage have a higher top speed and acceleration as it is currently so underpowered it decelerates uphill and cannot keep up with other Advanced/ARV vehicles.

**Describe the solution you'd like**
Increase top speed and acceleration

**Comment by telboycafc** [comment]
@CalLBLRP has this been completed yet ?

**Comment by CalLBLRP** [comment]
Good Evening @Rellentless, 

Your request has been confirmed and has been fixed. 

The update will be pushed to the main server at a later date and will be posted in our news-and-updates channel when a minor/major update has came out.

- Cal.
