### ISSUE TITLE
Rifle for SRO, MP5 update and return of the G36

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#443]
https://www.gta5-mods.com/weapons/l96a3-awm

This would replace the current marksman rifle in game and only be available to tags; CTSFO and SRO

https://www.gta5-mods.com/weapons/hk-mp5-from-eft-animated-replace

Current swap for the MP5 now. attachments would need adding before placing in locker if thats possible. Would be available to CTSFO and DPG

I would also like to ask to have a return of the G36 as this is still a widely used weapon in all police forces including the MET. Im not sure why this was removed.

**Comment by jxckUK** [comment]
I've added the new MP5 and rifle, but in relation to the G36 this was removed as the LMT Defender for BTP replaces that model. It no longer exists in the game hence its removal.
