### ISSUE TITLE
DRU ford ranger inverting unit

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#444]
https://www.gta5-mods.com/paintjobs/btp-ford-ranger-emergency-intervention-unit

Can this been added into the game for the DRU locker and attached to the DRU tag please.

**Comment by CalLBLRP** [comment]
Hello @BA98x, 

Unfortunately, we are unable to go ahead with this vehicle due to the model being unavailable/taken down from the site. 

Keep them suggestions coming through.

**Comment by BA98x** [comment]
https://www.gta5-mods.com/paintjobs/norwegian-ford-ranger-police-car would this work? It's the model

**Comment by CalLBLRP** [comment]
Unfortunately, the texture was created on a specific model. Feel free to view the attachment below:
![image](https://user-images.githubusercontent.com/98986766/195991095-f2d2b8e8-550a-4c7e-b11e-befa10612d11.png)

**Comment by BA98x** [comment]
The NPAS ranger is the same model

**Comment by CalLBLRP** [comment]
Yes, the model may look the same but it was done by a different modifications.
