### ISSUE TITLE
DPG Car

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#446]
(https://shoppy.gg/product/llDNDPj)

I will pay for this

DPG Car

**Comment by jxckUK** [comment]
Purchased and sent to Cal.

**Comment by CalLBLRP** [comment]
All retro vehicles have been added to development, QC is currently in progress. If QC is successful, the vehicles will be added to the Donator Premium garage. 

Issue moved to - https://github.com/LondonsBlueLine/qc/issues/31 and https://github.com/LondonsBlueLine/qc/issues/32
