### ISSUE TITLE
[BUG] Tram Train - DAVIS

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#448]
**Describe the bug**
When the tram spawns in near to DAVIS Police Station it causes FPS drop and sometimes the game freezes. This only happens when in the area of DAVIS. 

The tram does not improve any roleplay or impact the server so is not required as a resource intensive script. 

**To Reproduce**
1. be in the davis area
2. wait for tram to spawn

**Desktop (please complete the following information):**
 - Windows 10

**Comment by jxckUK** [comment]
> **Describe the bug** When the tram spawns in near to DAVIS Police Station it causes FPS drop and sometimes the game freezes. This only happens when in the area of DAVIS.
> 
I'll review this in detail, but at this time it can't be confirmed that the train causes those FPS drops. The train spawns around the map and continues its normal travel through the route so I would expect to see consistent frame rate declines wherever a train is if that were the case.
 
 > The tram does not improve any roleplay or impact the server so is not required as a resource intensive script.

The train/tube is quite critical to roleplay elements for BTP and is a fundamental requirement for their operation. The script isn't intensive at all, as all the script does is spawn the trains. The behaviour is natively done by GTAs engine.

**Comment by BA98x** [comment]
This is a client side issue as the trains/trams have been in before you joined the community and no one has brought up this issue.

**Comment by jxckUK** [comment]
I'm unable to replicate this.

However, I am aware of the wider spread issues with hitching especially when entering proximity of other players and it's on my radar. I'll capture this within that workload.
