### ISSUE TITLE
Volvo XC90 R Design

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#45]
Is there any chance of getting this added for OFCs that have been trained for the responsibility. I'm happy for it to be in the SFC garage named to be "OFC - Volvo XC90" || Only if this can be added. 

Link: https://www.gta5-mods.com/vehicles/volvo-xc90-r-design-arv-british-generic-fictional-alexthelion

Many Thanks!

**Comment by Dale1987** [comment]
will have a look over the next couple of days

**Comment by Dale1987** [comment]
Added to dev but has an issue with matrix board,
 matrix is linked to Y key message "police stop" appears
 Once reds are turned on it overwrites matrix and puts up "thank you"
The way the rear reds flash makes the message impossible to read
