### ISSUE TITLE
Suggestion - Car cleanliness

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#452]
**Is your feature request related to a problem? Please describe.**
Certain vehicles get dirty extremely quick and cause random sections to be dirty and thus looking horrible.
The BCU carrier and Donator Ford Focus RS (basic) are two examples I know of that get dirty rather quickly. 

**Describe the solution you'd like**
An option to enable 'always keep clean' or enable in the settings for all vehicles.

**Comment by jxckUK** [comment]
Fair request - I'll get this added.

**Comment by jxckUK** [comment]
Added in [26ec339](https://github.com/ProjectHyde/ProjectHyde/commit/26ec33975a72ce579de1e5b0b4520fdc5536a46d) and merged to live for next restart.
