### ISSUE TITLE
New LAS Vehicle

### ISSUE THREAD

**Issue by Jack2Oatway** [LondonsBlueLine/tracker#454]
I want to buy this Volvo V90 for LAS 
https://discord.com/channels/898263579021676644/964804029085536276/1001115387779354664

It’s sold by Blues ‘N’ Twos Modding link to the Discord https://discord.gg/gs3Z2MVr

The vehicle is £10, which I’m happy to pay for if this is approved.

**Comment by MrJC9** [comment]
If Approved - to go into Band C please :)

**Comment by Jack2Oatway** [comment]
Payment Has been made

**Comment by jxckUK** [comment]
Purchased - awaiting files.

**Comment by CalLBLRP** [comment]
Purchased -> In Development -> Going through QC -> Issue closed and moved to https://github.com/LondonsBlueLine/qc/issues/33.
