### ISSUE TITLE
LAS Tiguan & Sprinter

### ISSUE THREAD

**Issue by AP38Leon-cal** [LondonsBlueLine/tracker#455]
LAS 2015 VW tiguan RRV https://www.gta5-mods.com/vehicles/els-2015-london-ambulance-service-vw-tiguan-rrv 

LAS 2020 Mercedes-Sprinter DCA https://blighty3d.co.uk/products/2020-london-ambulance?_pos=1&_sid=6451a8668&_ss=r

**Comment by AP38Leon-cal** [comment]
If added VW tiguan - AP garage 
if addedd DCA- AP/Paramedic

**Comment by AP38Leon-cal** [comment]
sorry, the DCA to the AP/CTM garage

**Comment by CalLBLRP** [comment]
I will pass this over to the Band C and Band A for discussion. 

Please be patient while we do this.

**Comment by telboycafc** [comment]
I'm sure these vehicles are already added, no?

**Comment by CalLBLRP** [comment]
After reviewing, we have already got these vehicles in our server. 

Keep the suggestions coming though!
