### ISSUE TITLE
New BTP station

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#456]
With the new lease of life and influx in activity us btp lot can't all fit in the port-a-cabin at the airport parking so we should sell it and buy the airport station from you met lot: 

https://unionmods.com/?p=viewfile&file=848
(It's free)

**Comment by jxckUK** [comment]
This would replace the MPS station that is there so we can't do that. 

However, you do have a new full-fledged station opposite the casino.
