### ISSUE TITLE
[BUG] Rockstar Editor / MLO issue

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#457]
**Describe the bug**

Unable to use Rockstar Editor. 

If I go via the FiveM screen it crashes due to to an MLO (message states 'HeathrowAirportPoliceStation' error occurred in data file mounter classs CfxCacheMounter) and if I go via in-game menu it just endlessly loads on a black screen.
Others have confirmed to have the same issue. 

**To Reproduce**
See above

**Additional context**

From knowledge this is usually an MLO issue or the server being on the wrong version (on previous servers we have got around this by using the rockstar editor via the FiveM menu screen but believed this required a later server version).

**Comment by jxckUK** [comment]
Morning,

Unfortunately, this is an issue we're all too aware of. We're on the latest build for both FX (which is the system that runs our FiveM server) and the second to latest game build.

There is no current work-around for this and it is the reason we operate a separate content server which does not have potentially problematic assets.

You're welcome to connect to this content server as a content creator, you can reach it at content.lblrp.com. You will need to be whitelisted.

**Comment by judgegritter** [comment]
A work around is possibly removing the MLO that is causing issues?
