### ISSUE TITLE
[BUG] Spikes/Stop sticks do not affect AI

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#458]
**Describe the bug**
Spikes/stop sticks that are accessed by the boot of vehicles do not impact the AI and are also only one set length.

There appears to be a different spike script which can be accessed if in a certain spot near to the vehicle by pressing shift-e I believe which others have been able to access and this is the script that allows you to set the length. I personally have not tested this one as the boot E option gets in the way.

**To Reproduce**
Use spikes

**Comment by jxckUK** [comment]
I'm unable to replicate/reproduce this in testing, could you provide a supporting video?

![image](https://user-images.githubusercontent.com/48030374/197335479-a426d98f-37e0-44df-932b-5ea8160cdaf6.png)

**Comment by judgegritter** [comment]
Myself and another person tried this yesterday - it did not effect them. I will try again.

**Comment by jxckUK** [comment]
After reviewing clips, potential issue identified as lack of entity ownership. Addressed in latest build.
