### ISSUE TITLE
PaDP(close protection)

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#459]
SFC are now near release of PaDP. The current role name for this is DPG, can this be changed to PaDP Aswell as the in-game locker and garage which is currently named close protection. 

I also ask for permissions to be checked for PaDP and SRO. Both should be able to access PaDP permissions with the main weapon being the MP5 for PaDP and the marksman rifle for SRO ONLY. 

**I have sent across eup commands for PaDP if these can be checked. ** 

Contrary to my last issue on here the weapons will replace the current ones if passing QC and implemented.

**Comment by jxckUK** [comment]
Role changed to "PDP" (to follow three letter acronym format) and MPS rifle moved to that tag in configuration.

EUP Configurations:
```lua
{ "static armed protection 1", "diplomatic protection", "mps", 0, 0, 0, 0, 167, 0, 100, 0, 61, 0, 189, 0, 214, 0, 58, 0, 0, 0, 55, 0, 199, 0}
{ "static armed protection 2", "diplomatic protection", "mps", 0, 0, 197, 0, 166, 0, 100, 0, 102, 0, 189, 0, 210, 0, 58, 0, 0, 0, 332, 18, 199, 0}
{ "Mobile armed response officer", "close protection", "mps", 0, 0, 197, 0, 165, 0, 0, 0, 61, 0, 189, 0, 216, 0, 0, 0, 0, 0, 457, 0, 199, 0}
```

**Comment by RI1CAL** [comment]
There should also be a SRO eup command, thanks jack

**Comment by jxckUK** [comment]
> There should also be a SRO eup command, thanks jack

All I have is the above buddy, sorry. Did you do them all the same time?

**Comment by RI1CAL** [comment]
{ "Mobile armed response officer", "diplomatic protection", "mps", 0, 0, 197, 0, 165, 0, 0, 0, 61, 0, 189, 0, 216, 0, 0, 0, 0, 0, 457, 0, 199, 0}

**Comment by jxckUK** [comment]
```lua
{ "SRO", "Specialist rifle officer", "mps", 0, 0, 177, 0, 167, 0, 0, 0, 61, 0, 189, 0, 214, 0, 79, 0, 0, 0, 455, 23, 190, 0}
{ "Specialist Rifle officer", "Specialist rifle officer", "mps", 0, 0, 177, 0, 167, 0, 0, 0, 61, 0, 189, 0, 214, 0, 79, 0, 0, 0, 455, 23, 190, 0}
```

**Comment by RI1CAL** [comment]
the specialist rifle officer in lockers is spelt incorrectly too ;)

**Comment by jxckUK** [comment]
I'll let someone else handle configs

**Comment by colossalengineer** [comment]
@jxckUK do you want me to do the configs?

**Comment by RI1CAL** [comment]
can you change close protection name in garage to PaDP

**Comment by RI1CAL** [comment]
Can we also move the range rover SVR from probation to PaDP and the volvo xc90 in arv to probation

**Comment by colossalengineer** [comment]
All ready to push to main @jxckUK

**Comment by CalLBLRP** [comment]
Everything will be pushed at a later date as we have got quite a few stuff to push. Shouldn't be too long.
