### ISSUE TITLE
[BUG] - Player Blips disappearing

### ISSUE THREAD

**Issue by WolfRanger88** [LondonsBlueLine/tracker#46]
**Describe the bug**
Blips disappear when using garages.

**To Reproduce**
1. Spawn as MPS'
2. Get clothing in lockers
3. Get weapons in armoury
4. Get vehicle
5. Blips now disappeared but no F8 faults
6. If respawn while like this, you will spawn back into game but in wrong bucket with no players online in your bucket
7. fixed by going back into garage and back out again. Blips reappear and players back in game

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
Other player reported same issue in game and how to resolve.

**Comment by Dale1987** [comment]
I also had an issue with blips disappearing, went into garage came out, blips disappeared also made text chat stop working for me. i could see other players messages but mine were not sending.

**Comment by jxckUK** [comment]
Fixed in https://github.com/ProjectHyde/ProjectHyde/commit/bc9294bf098225474a1c9f70a9a967e5f333c7b1
