### ISSUE TITLE
LAS Fiat Dicanto (2nd Slot)

### ISSUE THREAD

**Issue by Jack2Oatway** [LondonsBlueLine/tracker#461]
![Github Issue](https://user-images.githubusercontent.com/116220168/197338132-c90f227f-1989-45f8-8595-00d725b73530.png)
![Github Issue 2](https://user-images.githubusercontent.com/116220168/197338222-65469651-2efa-48e3-9656-5e259ff159df.png)
As you can see the stretcher in the back of this ambulance isn't in the right place and goes through into the cockpit/driving area of the ambulance.
Can we get this sorted please.

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/197348587-fa571dc2-7e68-4d5e-b61f-41abf4f09622.png)

All fixed - awaiting merge.
