### ISSUE TITLE
[BUG] Matrix command for RTPC

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#462]
**Describe the bug**
Command /matrix install - does not appear to be enabled for the RTPC vehicles at least the ones available to PCs. I know some vehicles have a set display board using L however would still be cool to set our own messages especially for screenshots.

**Comment by jxckUK** [comment]
Matrix boards are exclusively added to Donator vehicles at this time within the advanced and premium garages. Hence the lack of matrix boards in the RTPC vehicles.

This may be extended in the future but at this time is limited to these vehicles.

(Check this post out for more information: https://discord.com/channels/948318430501699694/951106672082976838/1010122744677007400)
