### ISSUE TITLE
PaDP Vehicle and skin. (FREE)

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#464]
https://www.gta5-mods.com/vehicles/metropolitan-police-bmw-x5-f15-els-pack

https://www.gta5-mods.com/paintjobs/metropolitan-police-bmw-x5-f15-dpg

Top link im not sure if we have this already but if we can get it then all it qould require is replacing the skin to the second link on one of those x15s and placing into PaDP garage. 

Please :)

**Comment by CalLBLRP** [comment]
Unfortunately, this vehicle has failed QC automatically due to a dodgy model. 

Sorry, please keep the suggestions and ideas coming through though!
