### ISSUE TITLE
[BUG] LS Customs

### ISSUE THREAD

**Issue by Mighty-Jay** [LondonsBlueLine/tracker#469]
**Describe the bug**
When in LS Customs, if the driver goes into the LS Customs menu, the passenger also gets the menu open on their screen, but the passenger is unable to get rid of the menu. 

**To Reproduce**
1. Go to LS Customs with a passenger
2. Go into the menu to customise a vehicle
3. When you exit the menu, the passenger is unable to close the menu. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48175432/197400067-88f6dcd2-df45-48bc-aafa-e34edfff3fb7.png)

**Comment by judgegritter** [comment]
To add to this - 
The 'marker' at the main LS customs in the city (original) is quite hard to find and I can only get it to work if I drive in and as I drive out I catch the marker

**Comment by jxckUK** [comment]
Yeah - It's a pretty naff solution but it is temporary at the moment. It's on the back burner for some other stuff and I'm tracking it on our internal roadmap.

https://github.com/ProjectHyde/ProjectHyde/issues/94
