### ISSUE TITLE
ANPR suggestion

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#470]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Add an option for civilians to use an ANPR script. Some servers use it as the civs use commands such as 'setplate' and then commands to allow the script to pick up the plate around the map when hitting ANPR cameras. This will make it that tad more realistic for the officers instead of civs using 999. 
If this is available then apologies but I'not aware.

Additional to this;
A Discord channel that provides all commands for FiveM and what the command does. Will make it that bit easier for newcomers to learn what is available to us.

**Comment by telboycafc** [comment]
Hello, 

I believe civs should be able to register cars in the Cad, so they should flag up on that if they have registered one. This may need more clarifications.

**Comment by jxckUK** [comment]
> Hello,
> 
> I believe civs should be able to register cars in the Cad, so they should flag up on that if they have registered one. This may need more clarifications.

Correct - Civilians should only use vehicles registered to them unless they are RP'ing a stolen vehicle as any plate check will return a different owner and you will subsequently run into trouble when your name doesn't match.
