### ISSUE TITLE
New RTPC vehicle

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#473]
https://www.unionmods.com/?p=viewfile&file=864

New BMW released. Don't think we use 100% realistic fleet. I can easily slap the met logo and text on the livery and probably make the bonnet section black if this is required.

**Comment by jxckUK** [comment]
> https://www.unionmods.com/?p=viewfile&file=864
> 
> New BMW released. Don't think we use 100% realistic fleet. I can easily slap the met logo and text on the livery and probably make the bonnet section black if this is required.

Most marked vehicles in our garages are on the met fleet data lists. 

Most of the time we need express permission to add logos and badging to generic vehicles and we always check in case anyway. Can certainly be looked into, @CalLBLRP.

**Comment by CalLBLRP** [comment]
Moved to https://github.com/LondonsBlueLine/qc/issues/42
