### ISSUE TITLE
Schedule Training Removal

### ISSUE THREAD

**Issue by Jack2Oatway** [LondonsBlueLine/tracker#474]
HI
I would like to propose that the schedule training link to the website be removed as at the start it was a great idea however now hardly anyone uses it. What I am thinking is that this will confuse new players and make it easier for all the trainers as well.
Thanks in advance
J. Oatway

**Comment by jxckUK** [comment]
Requires approval from all three divisions, if it's not used then happy to have it removed.

Awaiting Jack C, Cal & Ryan's input.

**Comment by Jack2Oatway** [comment]
I have done this on behalf of JackC
