### ISSUE TITLE
[BUG] Radio lag since pulling callsigns from CAD

### ISSUE THREAD

**Issue by WolfRanger88** [LondonsBlueLine/tracker#48]
**Describe the bug**
Radio is lagging for all players.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log into server
2. Use radio push to talk
3. Voice transmit is delayed to match time when name and callsign appears in top right
4. Appears to have occurred since pulling callsign from CAD

**Comment by jxckUK** [comment]
This was fixed in https://github.com/ProjectHyde/ProjectHyde/commit/bc9294bf098225474a1c9f70a9a967e5f333c7b1
