### ISSUE TITLE
Teleport is not working -604.8341, 58.9555, 98.2002, 49.2221

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#484]
Just finished a fire at apartment 42 -604.8341, 58.9555, 98.2002, 49.2221. This teleport is not working, there is no prompt to change the level you are on. Had to no clip out, but other players will not have this option. Teleport worked getting in the place, not out.

**Comment by CalLBLRP** [comment]
This "bug" has been looked into and it's working perfectly fine, if you can try and get a clip of what has happened when you are next on. That is perfect, thank you!
