### ISSUE TITLE
BTP sirens

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#487]
Evening,

Some of the BTP are bugged in that's they no longer have the bullhorn and it's just a manual siren wail and 0 bullhorn. 

Some cars have bullhorn others dont

**Comment by colossalengineer** [comment]
@BA98x This is fixed in Dev Just need a push to Main

**Comment by telboycafc** [comment]
This has been pushed to main.  Any more issues, let us know.
