### ISSUE TITLE
Give NIRT access to some medical props and kit

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#489]
With the increase in people being in BTP in general and taking up specialist roles. I believe the NIRT should now have access to medical equipment as there role is mainly medical and stopping disruption on the UG. 

A brief description - The NIRT is a specialist joint response unit between BTP & TfL London Underground.

Designed to deal with a wide range of incidents, crime, medical and infrastructure failures with the focus to keep London moving. I have also attached a photo of their kit.

LAS are always primary but sometimes they are busy or not on so this would help on all fronts.

A pre requisite to joining would be that you would have to be a Paramedic in LAS and out of probation.
![20221031_115016](https://user-images.githubusercontent.com/108870150/199002960-fe20806c-8b24-4ae7-b794-2da2383db529.jpg)

This contains a full kit list also https://www.whatdotheyknow.com/request/network_incident_response_team_k

**Comment by BA98x** [comment]
https://www.whatdotheyknow.com/request/network_incident_response_team_k this also contains a kit list for the vehicle

**Comment by MrJC9** [comment]
I understand the premise of this and the fact that’s how they operate irl but we’ve had this discussion before with leadership and the LAS script and assets are what makes LAS unique so giving that access to other services would take away from this, this was said when you originally voiced this idea. We have to balance realism with game limitations. 
If you’re requiring them to be trained to Paramedic level they could just as easily go active as LAS and have access to all the kit and additionally be able to transport the patient to hospital in an ambulance without requiring any further LAS resources. 

I’ll leave to leadership to comment, but that’s my view.

**Comment by BA98x** [comment]
Even Access to backboard would be fine.

**Comment by jxckUK** [comment]
> I’ll leave to leadership to comment, but that’s my view.

I agree with the statement prior; we do unfortunately need to follow gameplay and not realism direction on this. It's in our interest to ensure we have separation of functionality and benefits between the divisions.

You should have access to a police medic bag from the armoury and you can of course RP scenarios. When we add a collectable backboard for LAS I would also be open to giving access to yourselves but in the case of the AED at this time that is to remain with LAS.
