### ISSUE TITLE
ELS [BUG]

### ISSUE THREAD

**Issue by Dale1987** [LondonsBlueLine/tracker#49]
**Describe the bug**
Unsure what starts this off, happens randomly, now happened to at least 3 players. ELS somehow has extra cycles making it difficult to get sirens working, or turning sirens back off. sometimes sirens will stay on but it looks like lights are off, different combinations happening.

**To Reproduce**
Really unsure what is causing this nothing showing in F8, occurs totally randomly to random players, other players cant see or hear it

**Expected behaviour**
should be the normal 3 cycles. sirens only work on stage1

**Screenshots**
I will try to record what happens when it next occurs

**Desktop (please complete the following information):**

**Additional context**

**Comment by jxckUK** [comment]
This was fixed in https://github.com/ProjectHyde/ProjectHyde/commit/bc9294bf098225474a1c9f70a9a967e5f333c7b1
