### ISSUE TITLE
drone unit 

### ISSUE THREAD

**Issue by BriannRI1** [LondonsBlueLine/tracker#490]
It would be nice to have a RTPC(RPU) owned its own drone unit car as it dose make sence that IRL a traffic unit does have a drone so they don't have to keep calling NPAS out when they have more important thing to do.. the drone unit would be a good tool to have in the RPU so if any driver decamped the drone would be up right away

**Comment by telboycafc** [comment]
@BriannRI1 this is going to be declined I'm afraid. Whilst we try to keep to realism of the met, we have to bring in the aspect that it's also a game so not everything will be met with IRL all the time. 
The other fact is, NPAS has just been moved to donator, and within NPAS, is the drone unit as a subdivision. Putting the drone in RTPC takes it away as a donator perk. This has been discussed with gold command.
