### ISSUE TITLE
Medic response vest 

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#492]
On behalf of Hornet. His friend is willing to make a medic response vest for NIRT. Cost would be around £10.
![Eo9HZMQWMAIILhA](https://user-images.githubusercontent.com/108870150/199547092-94f32d21-69b2-4e2e-baee-92dbcac63558.jpeg)
![IMG_20221102_163008](https://user-images.githubusercontent.com/108870150/199547109-97ac7ed3-2328-4fbc-99a8-214c494e97b9.jpg)

**Comment by jxckUK** [comment]
Could we get some contact information for the proposed modder? We'd need to do some vetting etc.

**Comment by BA98x** [comment]
It's in hand

**Comment by telboycafc** [comment]
Hornet has been shown the door, we will not liaise with his friends regarding this asset. So we will have to decline I'm afraid.
