### ISSUE TITLE
More Police Signs 

### ISSUE THREAD

**Issue by Hornet8221** [LondonsBlueLine/tracker#493]
Could we get additional Police signs for MPS so that we can make scenes more realistic and not have just Police Road closed signs and a few cones. The Images for the pack I suggest is £20 from UKOH

![image](https://user-images.githubusercontent.com/117306543/199564297-456ac4c4-3645-4054-9e04-8b9b65f3eafb.png)

![image](https://user-images.githubusercontent.com/117306543/199564467-c8f08d2d-62d3-4fc4-bf4b-480ec5640377.png)

**Comment by Hornet8221** [comment]
^ The above pack would also allow RTPC to have more from the collision's investigations unit and utilise it to its fullest capabilities

**Comment by Hornet8221** [comment]
If we could fund this today how quickly would we be able to get this ingame ?

**Comment by jxckUK** [comment]
No need to fund - we already own these assets as well as additionals from Kaiw. We just need to add them to existing scene menus.

**Comment by Hornet8221** [comment]
Can this be done ?

**Comment by jxckUK** [comment]
> Can this be done ?

Yes - but as with most things it requires someones development time. @colossalengineer - Is this something you can look at adding to existing scene menu?

**Comment by telboycafc** [comment]
@colossalengineer

**Comment by jxckUK** [comment]
Added to the minus menu scene options, all items are listed and can be placed.
