### ISSUE TITLE
LAS Subdivision

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#494]
As discussed with Z2 Cal, the possible addition of HM Coastguard as an LAS subdivision. This is being put forward for consideration as a division that can be mobilised for all sorts of search and rescue activities including rescues that wouldn't be possible without the services of the coastguard helicopter (e.g., remote water rescue, supporting water rescue, rescue from water vessels, rescues from difficult to reach areas such as cliffs/mountains and much more). This division would work really well with pending divisions for other services and bridge the gap where there is no water rescue services or search and rescue services at the moment. 

The following vehicle would be the startup for this division, with more vehicles available in the modding community. (EUP and MLO is also available)

***LIMITED TIME VEHICLE SALE UNTIL 9TH NOVEMBER***
Coastguard Helicopter
Supplied by Nexon - Discord: https://discord.gg/9x7wY4mP
Link to vehicle - https://discord.com/channels/813897754832404570/983795697478402098/983802052608163960

_J. Oatway has expressed that he wishes to cover the costs for the above vehicle._ 

**If we could look at moving forward with this as soon as possible while the vehicle is on a sale price. Work will start immediately on the training for the division as soon as this vehicle is purchased.** 

**If any meetings or discussions are required surrounding this, please reach out in Band C chat.**

**Comment by jxckUK** [comment]
Moved to QC: https://github.com/LondonsBlueLine/qc/issues/37
