### ISSUE TITLE
LAS HART Kit 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#495]
To begin preparing the Hazardous Area Response Team division for opening, I would like to ask for and assess the possibility of these tools being added for HART's use. 

The first 2 tools I would like to see about is Thermal Image Cameras and Night Vision Goggles. As you can see from the below tweet, they are used by the HART service in LAS. 
![HART Tweet](https://user-images.githubusercontent.com/102492709/199808059-33d82941-90a5-4441-b555-80ca4cc7cb11.png)

The next tool would be a Drone for HART. For reference this link will take you to EMAS HART to show all HART teams nationwide have a Drone, as they all work very similar. https://www.emas.nhs.uk/news/latest-news/2017-news/three-new-vehicles-for-our-hazardous-area-response-team/ - to quote this article **_These will include remote cameras and a drone to allow crews to look for patients in a contaminated or hostile environment before entering the area_**

**If any resources need to be found from the modding community to facilitate any of the above, please let me know.**

**Comment by jxckUK** [comment]
As discussed in a previous ticket I think we need to take a gameplay-based decision on drones. Whilst you absolutely have some claim to use them, we need to ensure we make divisions like NPAS & the police drones substantially appealing to players. 

The same applies to the TIC which at the moment is an LFB exclusive. 

We may change our approach in the future as and when we give more unique features and functions to divisions but at this time, I think we should leave as is.
