### ISSUE TITLE
Additional civilian EUP

### ISSUE THREAD

**Issue by IOJJ10** [LondonsBlueLine/tracker#498]
So basically i like do roadman scenes and gangster scenes and i know alot of others do so i found some things to be added and want to know your opinions 💯 

https://www.gta5-mods.com/player/nike-techfleece-sweatsuit-pack
https://www.gta5-mods.com/player/jordan-3-knick-s
https://unionmods.com/?p=viewfile&file=829
https://unionmods.com/?p=viewfile&file=820
https://unionmods.com/?p=viewfile&file=649

**Comment by jxckUK** [comment]
Oh god

**Comment by WolfRanger88** [comment]
The EUP items within these ticket have been flagged as leaked assets and the content uploader banned from 5Mods so we are unable to use these. 

Halfords texture conflicts with existing.

We will review the tyre slash script.

**Comment by jxckUK** [comment]
I've added a slash tyres function, very basic. You need to be on as CIV and have a knife in your weapon wheel, then use the ALT key eye to interact and slash the front tyres.
