### ISSUE TITLE
Electric cars make noise of petrol car

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#500]
The mache e in command and the Tesla in Dru make a hybrid petrol sound so once above 30mph engine noise can this be fixed.

**Comment by CalLBLRP** [comment]
Hi there, 

I will take a look into this.. all of our electric cars are set to the Hybrid audio has which is the default hash for hybrid vehicles, I will take a look but please do not expect it to be changed as it's already been set to the default hash.

**Comment by jxckUK** [comment]
I think the issue is that the Tesla is not a hybrid so needs a fully electric audio hash.

Imorgon, Cyclone, Neon, Raiden, Tezeract, Khameleon, Voltic are all full electric base game vehicles.
