### ISSUE TITLE
BTP fleet changes

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#501]
Evening,

Can the following changes be made;

Ford Sax marked moved from Disruption to NIRT
Ford focus hatchback moved from Command to Response.

Also can the old vivaro be added back in?

**Comment by telboycafc** [comment]
these changes have been done, with the exception of the vivaro as I don't know where it is.

**Comment by BA98x** [comment]
https://www.lcpdfr.com/downloads/gta5mods/vehiclestextures/16907-btp-vauxhall-vivaro-2015/ tel that's the vivaro comes with model

**Comment by telboycafc** [comment]
@CalLBLRP i have done the other vehicles, but this vivaro i have no idea about.

**Comment by jxckUK** [comment]
Moved to QC: https://github.com/LondonsBlueLine/qc/issues/39
