### ISSUE TITLE
Add a tranquilizer

### ISSUE THREAD

**Issue by JoshLBLRP** [LondonsBlueLine/tracker#502]
Hola so idea for rhe rural crime team because there mountain lions and they bite you for a tranquility gun 

https://www.gta5-mods.com/scripts/tranquilizer-gun

**Comment by jxckUK** [comment]
Unfortunately, this particular one is ScriptHook based and won't transfer to FiveM.

Closing this but if you can find an alternative and Gold Command approve we can re-open.
