### ISSUE TITLE
BCU Uniform Updates

### ISSUE THREAD

**Issue by ttvkenzjohGC** [LondonsBlueLine/tracker#504]
I have created a couple new uniforms for BCU as well as replacing most but keeping 1/2 uniforms the same below are what I have done

BCU Fleece to replace BCU Uniform 5
BCU Beat Uniform to replace BCU Beat Uniform
BCU Uniform 1 to replace BCU Uniform 1
BCU Uniform 3 to replace BCU Uniform 3
BCU Uniform 4 to replace BCU Uniform 4

BCU Uniform 2 to stay the same
Also BCU Beat (Jacket) to be a new one

I hope these work, took me some time trying to find the right things and look at the clipping

**Comment by colossalengineer** [comment]
{ "BCU", "BCU Uniform 1", "mps", 121, 0, 0, 0, 168, 1, 109, 0, 25, 0, 0, 0, 221, 0, 0, 0, 141, 0, 467, 0, 199, 0}
{ "BCU", "BCU Fleece", "mps", 121, 0, 1, 0, 168, 1, 114, 0, 25, 0, 194, 0, 229, 0, 0, 0, 144, 0, 458, 0, 199, 0}

**Comment by ttvkenzjohGC** [comment]
Only just found owt it saves from when the server was restarted, I am going to have to do most of them again today. On the list to do

**Comment by jxckUK** [comment]
> Only just found owt it saves from when the server was restarted, I am going to have to do most of them again today. On the list to do

Who told you that? It's false, I've attached them below:

```lua
{ "BCU", "BCU Uniform 3", "mps", 121, 0, 1, 0, 35, 0, 0, 0, 24, 0, 196, 0, 225, 0, 0, 0, 0, 0, 462, 0, 167, 0}
{ "BCU", "BCU Beat Uniform", "mps", 121, 0, 0, 0, 35, 0, 0, 0, 25, 0, 196, 0, 221, 0, 1, 0, 0, 0, 403, 0, 1, 0}
{ "BCU", "BCU Beat Jacket", "mps", 121, 0, 1, 0, 35, 0, 0, 0, 25, 0, 196, 0, 225, 0, 0, 0, 0, 0, 462, 0, 1, 0}
{ "BCU", "BCU Uniform 3 (closed)", "mps", 0, 0, 1, 0, 35, 0, 0, 0, 25, 0, 194, 0, 234, 0, 0, 0, 0, 0, 460, 0, 215, 0}
{ "BCU", "BCU Uniform 1", "mps", 121, 0, 1, 0, 168, 1, 113, 0, 25, 0, 196, 0, 229, 0, 1, 0, 148, 3, 466, 0, 199, 0}
{ "BCU", "BCU Uniform 1", "mps", 121, 0, 0, 0, 168, 1, 109, 0, 25, 0, 0, 0, 221, 0, 0, 0, 141, 0, 467, 0, 199, 0}
{ "BCU", "BCU Fleece", "mps", 121, 0, 1, 0, 168, 1, 114, 0, 25, 0, 194, 0, 229, 0, 0, 0, 144, 0, 458, 0, 199, 0}
```

**Comment by telboycafc** [comment]
im just confused by this whole thing

**Comment by ttvkenzjohGC** [comment]
what's up tel

**Comment by ttvkenzjohGC** [comment]
Sorry to be a pain, realised one that has not been updated in some time so I decided to change 1-2 things about it, have called it Bicycle Unit as I couldn't remember the name but any chance it can replace the BCU Cyclist Uniform

**Comment by telboycafc** [comment]
I have added these to dev for QC.

**Comment by telboycafc** [comment]
QC passed, to be pushed to main.
