### ISSUE TITLE
2002 Vauxhall Vectra (Donator)

### ISSUE THREAD

**Issue by AP38Leon-cal** [LondonsBlueLine/tracker#505]
i would like for this vehicle to be added to "premium Donator' garage - but i would like it to hhave the same tones as the BMW ( Jam Sandwich Retro) that is in the Premium donator garge 

https://unionmods.com/?p=viewfile&file=115

**Comment by CalLBLRP** [comment]
Thank you for the suggestion, I will look into this tomorrow morning.

**Comment by telboycafc** [comment]
sorry this vehicle failed QC, suggestion is declined.
