### ISSUE TITLE
Underground station map skin

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#506]
Can this be added https://www.gta5-mods.com/misc/london-undeground-stations

**Comment by jxckUK** [comment]
Concerned about the quality of these textures but if they pass QC then they can be added.

If someone from the asset team could add that would be great.

**Comment by telboycafc** [comment]
if this has been added, i can test.

**Comment by WolfRanger88** [comment]
I haven't even looked yet as on a late shift so will look tomo

**Comment by telboycafc** [comment]
anyone added these in yet for QC ?

**Comment by WolfRanger88** [comment]
Not yet and haven't contacted creator yet to ask for perms for use in fivem
server.

We need to ask as he has created it as an openiv single player install
rather than MLO or YMap.

**Comment by telboycafc** [comment]
I don't think we are going to get anywhere with this at the moment, as it needs permission to use in a fiveM server. Also along with the issue wolf raised of how its been created. We don't have the personnel at the moment to sort this out.
