### ISSUE TITLE
RNLI

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#507]
We are now looking at the possibility of adding RNLI as an LAS subdivision. This is being put forward for consideration as a division that can additionally/primarily be mobilised for all sorts of water rescue, flood rescue and coastline search and rescue incidents. This division would work really well with the previously suggested LAS Subdivision as well pending divisions for other services and further bridge and support the gap where there is no water rescue services at the moment.

The following MLO/Pack would be the startup for this division, with a lot of available assets in the modding community. (EUP and further vehicles are also available):
https://blighty3d.co.uk/collections/rnli-vehicles/products/pack-mlo-ymap-rnli-poole-lifeboat-station

_Myself and @colossalengineer are looking at splitting this between us to purchase it, if approved._

If we do look at moving forward with this, work will start immediately on the training for the division. We already have some training drafted and this will tie in really well with the other new subdivision we are looking at.

If any meetings or discussions are required surrounding this, please reach out in Band C chat.

**Comment by jxckUK** [comment]
Moved to QC, multiple.
