### ISSUE TITLE
Weapon Lanyards

### ISSUE THREAD

**Issue by K1453** [LondonsBlueLine/tracker#508]
Could we possibly get the Linyard from London studios for SFC weapons please such as the glock and batton gun and sig ??

**Comment by jxckUK** [comment]
I think the problem with the lanyard from our experience is that it causes more issues than it solves. 

(See: https://github.com/LondonsBlueLine/tracker/issues/282)

But keep suggestions coming, I will archive this for the time being, but it is subject to a re-review if circumstances change.
