### ISSUE TITLE
XC90 Marked supervisor. Bronze garage

### ISSUE THREAD

**Issue by ttvkenzjohGC** [LondonsBlueLine/tracker#509]
I've noticed the strange lightbar and was wondering if it was a feature or an issue on the marked supervisor XC90 in bronze garage if it is an issue is there anyway of fixing it?

Images: 
![image](https://user-images.githubusercontent.com/105547136/202812757-9cd1a9d2-a88a-4dee-ae87-323fab4c90c9.png)
![image](https://user-images.githubusercontent.com/105547136/202812802-94c38575-c623-48e3-8af1-a363dd8ec29f.png)

**Comment by telboycafc** [comment]
this would have been put in before we had our QC process in place. We don't have anyone who can fix it, if it's much of an issue we can just remove it and sack it off?
