### ISSUE TITLE
can we get this vehicle maybe ?

### ISSUE THREAD

**Issue by LegoMasterCam** [LondonsBlueLine/tracker#510]
https://unionmods.com/?p=viewfile&file=887

this is the link to the vehicle it is a very nice, unmarked Mecedes

**Comment by telboycafc** [comment]
number plate is a bit blah, but we can get it in and put it through the QC process. If it doesn't pass, then it will be a no.

**Comment by CalLBLRP** [comment]
This is a duplicate of another suggestion. 

Please view: https://github.com/LondonsBlueLine/tracker/issues/516 for anymore updated.
