### ISSUE TITLE
LAS Marked Volvo in Band C garage headlights [BUG]

### ISSUE THREAD

**Issue by nathanhulme** [LondonsBlueLine/tracker#511]
Marked Volvo in LAS Band C garage has working headlights until you turn ELS on, then the headlights stop working.

**Comment by telboycafc** [comment]
what have you set your ELS button to, to turn them on?

**Comment by nathanhulme** [comment]
Q for ELS as bog standard settings

**Comment by telboycafc** [comment]
fixed, will be pushed to main when ready.
