### ISSUE TITLE
New PT vehicle

### ISSUE THREAD

**Issue by LegoMasterCam** [LondonsBlueLine/tracker#512]
https://unionmods.com/?p=viewfile&file=870

that is the link to the ford transit PT van

**Comment by telboycafc** [comment]
we can certainly have a look, and put it through the QC process

**Comment by CalLBLRP** [comment]
Good Afternoon @LegoMasterCam,

Your suggestion has been **approved**, we thank you for your suggestion and we will keep you updated shortly. 

Kind Regards,
Cal.

**Comment by jxckUK** [comment]
Member no longer resides in the community due to an account ban.
