### ISSUE TITLE
BTP fleet additions

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#515]
https://unionmods.com/?p=viewfile&file=875 can this be added to the OSU garage as the working at height/osu car.

https://unionmods.com/?p=viewfile&file=266 and car this be added to the afo garage as demonstrators.

**Comment by CalLBLRP** [comment]
I will look into this tomorrow morning for you, please allow me time to get this sorted.

**Comment by BA98x** [comment]
have the volvos been approved yet?

**Comment by jxckUK** [comment]
@CalLBLRP - Could you update this one?

**Comment by jxckUK** [comment]
Moved to QC:

https://github.com/LondonsBlueLine/qc/issues/77
https://github.com/LondonsBlueLine/qc/issues/78
https://github.com/LondonsBlueLine/qc/issues/79
