### ISSUE TITLE
Unmarked Mercedes Benz

### ISSUE THREAD

**Issue by IOJJ10** [LondonsBlueLine/tracker#516]
Me again with new suggestions 

https://store.ea-rp.com/package/5100834
https://unionmods.com/?p=viewfile&file=887

Santander bikes from london studios

**Comment by telboycafc** [comment]
Santander bikes have been suggested before, and is not something that fits our server so we will be declining that suggestion I'm afraid.

**Comment by CalLBLRP** [comment]
I will look into the unmarked vehicle for you; please allow me time to get this sorted. Will most likely look at it tomorrow morning!

**Comment by CalLBLRP** [comment]
Good Afternoon @IOJJ10,

Your vehicle has been added to our development server, please view the QC ticket in regards to the vehicle: https://github.com/LondonsBlueLine/qc/issues/59
