### ISSUE TITLE
TSG Uniforms revamp

### ISSUE THREAD

**Issue by Bettercal** [LondonsBlueLine/tracker#517]
TSG eup has been done via commands in main server (all uniforms currently in TSG locker can be removed and replaced with below

TSG- TSG constable and TSG constable 2
TSG- TSG medic
TSG- TSG helmet off
TSG- TSG Taser
TSG- TSG beat
Bronze command- TSG Sergeant and TSG sergeant 2
Bronze command- TSG Inspector and TSG inspector 2

please let me know if any of these commands have not come through.

**Comment by Bettercal** [comment]
This may require a new locker as it’s currently under BCU with 1 uniform. If possible like other divisions have TSG as a sub div locker under the BCU. Linked to role - TSG

**Comment by telboycafc** [comment]
we can create a separate locker under a TSG tag, but not sub lockers at the moment.

**Comment by Bettercal** [comment]
Yeah sound then

**Comment by telboycafc** [comment]
these have been done in dev for you to look at. People will need the TSG role on discord to access the locker.

**Comment by CalLBLRP** [comment]
Tel has concluded this and has given the go ahead.

**Comment by RI1CAL** [comment]
Hi, this is embarrassing the TSG medic must not have gone across properly as the helmet was incorrect. I've done the command again in main for it. My apologies
