### ISSUE TITLE
Automatic siren cutout

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#518]
Is it possible to install automatic siren cut out on the vehicles so if we’re in a pursuit with a decamp we don’t have to worry about turning our sirens off

https://www.lcpdfr.com/downloads/gta5mods/scripts/25758-automatic-siren-cutout/

**Comment by telboycafc** [comment]
So quite a few people are against this idea including myself. Although seen as convenient, it will take away the element of realism and the atmosphere of there being a foot chase on a decamp.

**Comment by Jjones033** [comment]
Ah okay no worries :)

**Comment by telboycafc** [comment]
IRL police have to turn the sirens off them self or they just leave them on when then need to get out the car quick for a chase. Someone else can turn them which is usually the case here anyway.

**Comment by telboycafc** [comment]
thanks for the suggestion though.
