### ISSUE TITLE
BTP fleet issues

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#519]
Evening,

A minor one the new 308 is under as a 208 ok the garage.

More significant issues, the caddy you can't put the dog in and it doesn't allow.

The Vito the grills don't come on with the lightbar can that be sorted out.

Also can the not correct caddy be removed

**Comment by telboycafc** [comment]
@BA98x All been done. Note though, the new caddy already has dog models in it, this isn't something we can remove, it needs to be done by the original Modder. So, when the dog is in the back of the van laying down, you will also have the fixed models in there too.

**Comment by BA98x** [comment]
Not the dog models, you can't put Ur dog in it with the eye menu

**Comment by telboycafc** [comment]
yes you can, ive tested it.

**Comment by telboycafc** [comment]
right I'm closing this again, i have just literally put the dog in the van in main
