### ISSUE TITLE
SEG wardrobe re-configuration

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#52]
Any chance for the motorbike uniform "copied and pasted" to a brand new wardrobe called **Specialist Escort Group**. This should only be shown to those that have the "SEG" discord role. 

Love you ;) <3

**Comment by telboycafc** [comment]
This has been completed, tested, and ready for main. You will find the locker at the bottom of the list in the lockers for officers only with SEG role.
