### ISSUE TITLE
Btp vest pack 

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#521]
https://store.sinnersmodshop.co.uk/package/5396222

https://store.sinnersmodshop.co.uk/package/5396199

Has ranks n all sorts

(Cheaper to buy individual packs also preference hi Vis)

**Comment by jxckUK** [comment]
Purchased - pending addition.

**Comment by jxckUK** [comment]
We can no longer accept suggestions relating to SMS due to their systems for encryption not be compatible with our internal EUP systems.
