### ISSUE TITLE
Volvo xc90 met traffic

### ISSUE THREAD

**Issue by Bettercal** [LondonsBlueLine/tracker#522]
https://nexonworkshop.co.uk/dev/Met_XC90.rar

Free so why not. Good to be in RTPC advanced driver garage

**Comment by CalLBLRP** [comment]
Good Afternoon @Bettercal,

Your suggestion has been **approved**, please view the qc ticket in regards to this vehicle: https://github.com/LondonsBlueLine/qc/issues/58

Kind Regards,
Cal.
