### ISSUE TITLE
Taser

### ISSUE THREAD

**Issue by K1453** [LondonsBlueLine/tracker#524]
I was just wondering if we could get this added for the taser as the body of the taser and the cartages are more realistic
https://thinlinesanctuary.com/products/taser-x26

**Comment by MI1Kxnz** [comment]
Sorry to just sneak in here, if we were to get this there is a free version on lspfr.com which was recently updated to have the extended part with extra cartridges

**Comment by Lucane1999** [comment]
MPS use Taser X2 - X26 is old and outdated.

**Comment by jxckUK** [comment]
Closed due to confirmation from command team that the asset is not applicable.
