### ISSUE TITLE
ANPR

### ISSUE THREAD

**Issue by K1453** [LondonsBlueLine/tracker#525]
Can we have ANPR for firearms cars please??

**Comment by telboycafc** [comment]
So, this has been requested many times before. Will discuss with leadership.

**Comment by telboycafc** [comment]
So, MPS are requesting that RTCP have sole use of the ANPR system. The reason behind this, is we try and give every division some form of uniqueness, so SFC have sole use of firearms, DSU sole use of dogs, RTPC have sole use for the ANPR system. If we gave it to SFC as well, everyone would just run as SFC as a majority do now anyway. So, for those reasons, this has been declined.
