### ISSUE TITLE
ELS [BUG]

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#526]
MPS 84 does not have correct LEDs flashing. The back beacon does not work nor the two fronts.

![image](https://user-images.githubusercontent.com/107463744/205436832-16cdeab2-4671-4a04-8fc4-a59a3a05b4af.png)

**Comment by telboycafc** [comment]
I'll have a look

**Comment by telboycafc** [comment]
Okay, so this vehicle come from gta5 mods, so was a free asset. Those lights on the bike just don't work. Seeing as it is an early MPS number, I would say we didn't have the QC process in at the time, which by our standards now, this wouldn't have passed. So, we can either keep the bike in as it is, or...sack it off. @RI1CAL

**Comment by telboycafc** [comment]
removed from garage due to poor quality.
