### ISSUE TITLE
L200 side doors

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#527]
hello

The side doors on the rear part of the L200 are stuck open cant use the menu to close them etc so must be a config issue. 
![l200](https://user-images.githubusercontent.com/108870150/205514132-eec3b40b-1f05-410b-aaf7-cb508577657d.jpg) the small side roller doors

**Comment by telboycafc** [comment]
@colossalengineer can you have a look please.

**Comment by telboycafc** [comment]
BTP33, its on the vehicle sheet. @colossalengineer

**Comment by colossalengineer** [comment]
pushed to dev

**Comment by BA98x** [comment]
this sosrted out yet?

**Comment by telboycafc** [comment]
yes this has been fixed, waiting for merge to main.

**Comment by CalLBLRP** [comment]
Good Afternoon @BA98x, 

This bug has been fixed and will be pushed to live this evening. 

Thank you for your patience. 

Kind Regards,
Cal.
