### ISSUE TITLE
2 New MPS vehicles (paid)

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#528]
From capital studios - https://discord.gg/xWhEn2KY

https://discord.com/channels/953052736130273371/953053192537636885/994745227753553920 - PaDP 12.50

https://discord.com/channels/953052736130273371/953053192537636885/994743806689804338 - BCU 10.00

I shall pay should you be happy.

**Comment by CalLBLRP** [comment]
Hi there @RI1CAL, 

If you are happy to cover the costs I see no issue why we can't have these vehicles; please send the money the normal way for both vehicles (via PayPal). The link for our PayPal can be found [here](https://www.paypal.com/donate/?hosted_button_id=XG35B88BLGMMN). 

Many Thanks!

**Comment by Bettercal** [comment]
I have placed the money in your PayPal plus some. I will put the transaction in a ticket

**Comment by CalLBLRP** [comment]
Hiya bud, 

Quick update; both vehicles have been added to development - please see the QC tickets below: 

MPS230 - Marked BMW 2 Series - https://github.com/LondonsBlueLine/qc/issues/51
MPS231 - DPG Ford C-Max - https://github.com/LondonsBlueLine/qc/issues/52
