### ISSUE TITLE
[FEAT]Vehicle Blip

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#53]
Can we make the Vehicle blip not disappear when you are to far away from your vehicle as your cant lock/unlock it after

**Comment by jxckUK** [comment]
If your vehicle blip disappears it isn't because you've gone too far, it is because the entity isn't able to be referenced anymore.

I can address this with state bags but it'll take some time.

Closing and transferring to **PH-GARAGES**.
