### ISSUE TITLE
CCTV view for donators in MRPD and Davies

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#530]
When i go to one of the orange blips to view the CCTC i am greeted with this lovely screen 

![CCTV](https://user-images.githubusercontent.com/117676135/208295643-d9e6c916-a2d6-4d03-9dae-21b647fba03e.png)

and gives me no option to exit that screen so will be stuck on it until i relog

**Comment by Jjones033** [comment]
Hey guys I'm wondering if there is any update on this issue yet?

**Comment by Jjones033** [comment]
No worries was just wondering that's all. Hope you've had a good holiday season and have a happy new year :)

**Comment by Jjones033** [comment]
Morning Jack, appreciate you've had the medical script as a priority to work over at the moment just wondering if you've had chance to take a look at this at all.

**Comment by jxckUK** [comment]
No we'll probably remove this script for now.

Will re-release when we have time and it might be of use as it isn't utilised.
