### ISSUE TITLE
LAS skoda 

### ISSUE THREAD

**Issue by AP38Leon-cal** [LondonsBlueLine/tracker#531]
New Suggestion for the LAS Advanced Paramedic Garage 

https://www.gta5-mods.com/paintjobs/london-ambulance-service-skoda-octavia

**Comment by CalLBLRP** [comment]
Good Afternoon @AP38Leon-cal, 

Unfortunately, at this current time your suggestion has been denied due to detail upon such vehicle. The vehicle has extremely poor graphics and will automatically fail our QC (Quality Check) process. 

Keep on suggesting! 

Kind Regards,
Cal.
