### ISSUE TITLE
Met Police Jankel

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#533]
Would it be possible to add this into the game somehow so if there was a high risk firearms operation we could have 2 Trojan units in 2 of these vehicles and other SFC following up behind in other cars. 

https://www.gta5-mods.com/vehicles/met-police-jankel

**Comment by Jjones033** [comment]
Afternoon guys. Wondering if there's an update on this request?

**Comment by jxckUK** [comment]
@CalLBLRP - Could you update this one when you have a chance? May need senior MPS input.

**Comment by CalLBLRP** [comment]
Good Evening, 

I will take a look into this vehicle this evening. I have been trying to find a "good" model for SFC but most of them are useless and unusable. Please bare with me when trying to get this type of vehicle in. 

Thanks!

**Comment by MrJC9** [comment]
> Good Evening,
> 
> I will take a look into this vehicle this evening. I have been trying to find a "good" model for SFC but most of them are useless and unusable. Please bare with me when trying to get this type of vehicle in.
> 
> Thanks!

https://blighty3d.co.uk/collections/new-products/products/jankel-ford-f450-full-version

**Comment by CalLBLRP** [comment]
Good Evening @Jjones033,

This vehicle has been added to the Specialist Firearms Command garage, will be in the main server in the next few days.

Thanks for your suggestion!
