### ISSUE TITLE
CAD data collection not functioning

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#535]
When i joined as MPS It came up saying for me to make a new cad so i logged into my current account and it still didn't change anything,
![image](https://user-images.githubusercontent.com/103907609/210158179-a91d70f5-d835-40f5-b2ef-6dd1fdbd4554.png)
Happy New Year!!!

**Comment by jxckUK** [comment]
Yes as I was very keen to state, I'm aware of this bug and I'm awaiting external dependencies, should be sorted tomorrow morning.

**Comment by MikeyDeann** [comment]
Also if i hold alt you can see the 3rd eye menu but i cannot 
![image](https://user-images.githubusercontent.com/103907609/210158423-76a90d93-3f1d-49d1-81ce-e5ff0f6f04f2.png)

**Comment by MikeyDeann** [comment]
> Yes as I was very keen to state, I'm aware of this bug and I'm awaiting external dependencies, should be sorted tomorrow morning.

Alrighty Thanks Jack

**Comment by jxckUK** [comment]
> Also if i hold alt you can see the 3rd eye menu but i cannot ![image](https://user-images.githubusercontent.com/103907609/210158423-76a90d93-3f1d-49d1-81ce-e5ff0f6f04f2.png)

Thanks, a separate but major issue that I can resolve now.

**Comment by MikeyDeann** [comment]
Works Now Jack Thank you!

**Comment by jxckUK** [comment]
All fixed, CAD data collection should work for all departments. Any other issues please open a new issue.
