### ISSUE TITLE
Bronze Command car

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#536]
I was wondering if we can get this in the brozne command garage https://www.unionmods.com/Uploads/Images/1671490735a2.png.jpeg

**Comment by CalLBLRP** [comment]
Hello @viiidal,

Please provide us the union mods link, pictures of the vehicle do not help us locate where the main files are.

Thanks!

**Comment by Jjones033** [comment]
@CalLBLRP I believe this is the link https://sur.ly/o/unionmods.com/AA000014?pageviewId=desktop-302e3031373035393030203136373333383437343020393533373439303836

**Comment by Jjones033** [comment]
> @CalLBLRP I believe this is the link https://sur.ly/o/unionmods.com/AA000014?pageviewId=desktop-302e3031373035393030203136373333383437343020393533373439303836

Does take you directly to the model strangely enough however in the search bar if you type "Amarok" it should show you the one he is on about

**Comment by CalLBLRP** [comment]
This request has been denied as the vehicle is used for CTSFO. 

Thanks for the suggestion, 
Please keep them coming!
