### ISSUE TITLE
Issue with L200 shutters

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#537]
New sprinter is in Response instead of OSU, it sits face down ass up, something wrong with suspension needs sorted.

L200 now spawns with roller doors on but when you get in it they open and cant bee closed so needs sorting.

ta

**Comment by CalLBLRP** [comment]
I have fixed the garage problem, I will look into the suspension and found out where we got the model from as it appears that it's a model issue which we cannot view from a server point of view. Please allow us some time to get in contact with the modeller. 

Thanks.

**Comment by CalLBLRP** [comment]
I will be reviewing the L200 tomorrow morning.
