### ISSUE TITLE
SGT uniform

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#539]
Would it be possible to get different variations of the sgt uniform to fit with the RTPC unit as the moment I have use of the high vis ones where as if I wanted to go a little bit covert I'd struggle to do so in high vis. So have something like the interceptor uniform but with the sgt epaulets

**Comment by jxckUK** [comment]
> Would it be possible to get different variations of the sgt uniform to fit with the RTPC unit as the moment I have use of the high vis ones where as if I wanted to go a little bit covert I'd struggle to do so in high vis. So have something like the interceptor uniform but with the sgt epaulets

Bronze Command are welcome to use the civilian menu to create uniforms. Once you've created a uniform you can submit it by running the following command:

`/saveeup "{NAME}" "{DISCORD TAG}"` for example `/saveeup "RTPC SGT" "BronzeCommand"`

These uniforms will then get sent to the developers as well as going through a QC process for approval from your divisional leads.
