### ISSUE TITLE
TSG wardrobe re-configuration

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#54]
TSG EUP Helmet is a motorbike helmet, i have found a helmet i would like it changed to if possible 
From This
![20220216214008_1](https://user-images.githubusercontent.com/75227401/154362928-2ea0f7eb-10f6-4b50-ab69-9dfe4e81489e.jpg)
To This
![20220216213940_1](https://user-images.githubusercontent.com/75227401/154363012-1c81f9d6-d7f9-46d8-b4a0-5341ec31f678.jpg)

**Comment by telboycafc** [comment]
This has been completed, tested and ready for main.
