### ISSUE TITLE
ANPR via the number pad

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#541]
Good evening, I have noticed when i go into the RTPC cars that are fitted with ANPR and I know they should have working ANPR when i click the number 3 it doesn't turn on. Is this due to the mini cad under going maintenance at the moment?

**Comment by Jjones033** [comment]
update - since restart it is now working on the first vehicle I have tried, yet to try any of the panther vehicles i was using when the ANPR wouldnt turn on

**Comment by Jjones033** [comment]
Update - works fine in panther cars since restart

**Comment by jxckUK** [comment]
I'll close this out but let me know if it re-occurs.
