### ISSUE TITLE
Garages for new cars

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#544]
MPS230-BCU
MPS231-PaDP
MPS232-Standard RTPC
MPS233-Silver command
MPS234-Bronze command
MPS235-Advanced Driver RTPC
MPS236-Bronze Command(only to be used in special occasions so requires bronze deployment)
MPS237-BCU PT
MPS238-Panther
MPS239-RTPC(Anyway someone can slap a MET logo on? I can pay if it requires)
MPS240-Gold Command

ALL require boot access and ones that are rtpc anpr

**Comment by colossalengineer** [comment]
MPS238-Panther - Failed QC
MPS240-Gold Command - Failed QC
