### ISSUE TITLE
Functions error when not having a civilian set

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#549]
Upon arriving at a vehicle Collison which was spawned from FivePD i attempted to question the peds and ask for a breathalyser. When i pressed the breath test question it took me back to the start and i could no longer do anything else with the 3rd eye on that ped. For example it did not let me press question anymore.   

![image](https://user-images.githubusercontent.com/107463744/212551743-96b8c8ec-351e-4001-8939-b66fbe90e359.png)

**Comment by jxckUK** [comment]
Will get this sorted this afternoon, thanks for adding the F8 screenshot!

**Comment by jxckUK** [comment]
Fixed in c60c8e08b9e4f67585d3539efd358e25fc97fca9
