### ISSUE TITLE
Amend default key binds for dog release and car locking

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#55]
A Couple of keybind issues i have noticed

U to turn on rear light and locks car
E ro horn but also quick release for DSU

**Comment by jxckUK** [comment]
The car locking keybind can be changed already via your own key mapping menu, just trying to think of what to move the DSU one to. Any suggestions? @MrP3n9u1n

**Comment by MrP3n9u1n** [comment]
maybe O or I
