### ISSUE TITLE
BTP spawn menu

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#550]
BTD is missing from the spawn list and can they be made to spawn a the hub and command to there too.

**Comment by jxckUK** [comment]
Yes, can you find an icon from https://fontawesome.com that you want as well as a description. This is not a bug as its not been set up by yourselves.

**Comment by BA98x** [comment]
I gave you all them in the leads chat

**Comment by BA98x** [comment]
But this for dogs e573 shield dog

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/212647597-1a431b56-619e-4c2b-adce-2961f55a55f4.png)
