### ISSUE TITLE
BMW G21 wrong garage assignment

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#551]
Is this car supposed to be RTPC standard or in the interceptor one?
![image](https://user-images.githubusercontent.com/117676135/212692115-4baadc61-300f-455f-bba4-1de8d49baeec.png)

**Comment by CalLBLRP** [comment]
I will deal with this tomorrow, thank you for raising it!

**Comment by Jjones033** [comment]
No worries mate. Sometimes when it's in the garage it shows a white bonnet however when it spawns in it comes out with that black interceptor bonnet and if it's showing the vice versa then it'll come out with the opposite bonnet.

**Comment by CalLBLRP** [comment]
oh no worries bud, I will look into that as well. It could be something to do with the model which is out of my hands but will indeed take a look. However, scrap about dealing with it tomorrow I have just put it back into the Interceptor garage. 

But, I am going to rename this regarding the bonnet so leave that with me.

**Comment by CalLBLRP** [comment]
After 3 tries of getting this to work, it finally has. Should be in main soon!

- Thanks for letting us know about it and keep suggestions/bugs coming through!
