### ISSUE TITLE
Interactions involving vehicle assignments failing

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#552]
Third eye coming up with these types of messages when i attempt to search a vehicle or check its status
![image](https://user-images.githubusercontent.com/117676135/212734001-ce37c7f7-72f3-4dfe-9790-cf7dd9666a86.png)

**Comment by Jjones033** [comment]
The other officer in the picture experienced the same issue, i tried it with another vehicle and still came up with saying i cant do it

**Comment by jxckUK** [comment]
Merging this with https://github.com/LondonsBlueLine/tracker/issues/545 as its a duplicate.
