### ISSUE TITLE
New Props Menu

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#553]
The (-) menu with all the new props in does not function properly. 

When you open the menu, it will open and sometimes may or may not spawn the prop you want. But, once you open the menu and it closes, you cannot open or use the menu again at all.

**Comment by jxckUK** [comment]
Assigned to Colossal to create, moving to internal roadmap.

([PH-TRAFFIC: Version 1#54](https://github.com/ProjectHyde/Roadmap/issues/54))
