### ISSUE TITLE
Defib functionality 

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#555]
As you know already (so just logging it) the defib doesn't work, and i feel this is a vital part of LAS especially with the new interactions in place. 

Most servers do have a working defib now as standard. Hopefully we can reintroduce it as the cherry on top with the new vitals script.

**Comment by jxckUK** [comment]
Agreed - I'll move it up the priority order, but outstanding issues with allocation are taking priority at the moment.

**Comment by jxckUK** [comment]
Merging into https://github.com/LondonsBlueLine/tracker/issues/546
