### ISSUE TITLE
ANPR not present

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#557]
Two cars below are new in RTPC and currently in the standard RTPC garage. Both cars ANPR is not working or turning on when your press 3
![image](https://user-images.githubusercontent.com/117676135/212758429-b6b65ceb-92f1-4694-baaf-506e5e4aeaab.png)
Car 1 - BX19 HDG - Volvo XC90
Car 2 - PJ71 XCK - BMW G21

**Comment by telboycafc** [comment]
this has been done, ready for push to main.

**Comment by Jjones033** [comment]
Thank you telboy. Would it be possible to keep this thread open for now as I will test all RTPC vehicles tonight and for the ones that don't work I'll add them into here. These two were just bought to my attention hence why I bought it up but thought I should test them all.
