### ISSUE TITLE
CVE Mitsubishi L200

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#558]
Morning guys, would it be possible if this vehicle can be added to the Commercial Vehicle Enforcement garage.

https://blighty3d.co.uk/collections/new-products/products/2020-mps-mitsubishi-l200-commercial-vehicle-unit

![image](https://user-images.githubusercontent.com/117676135/212892676-a41fe38f-3e9a-4348-a9ed-5f608d5cb8e6.png)

**Comment by Jjones033** [comment]
Happy to provide funds for this if needs be

**Comment by jxckUK** [comment]
We do have an L200 (same model) in the game but I don't believe its CVE, we can however get this if you still want.

**Comment by Jjones033** [comment]
Yeah if possible mate I would like this part of CVE like I said I'm happy to provide funds.

**Comment by jxckUK** [comment]
> Yeah if possible mate I would like this part of CVE like I said I'm happy to provide funds.

Yeah mate that's fine, feel free to ping a contribution across we'll order it now.

**Comment by Jjones033** [comment]
There you go mate. Thank you muchly. 

![image](https://user-images.githubusercontent.com/117676135/213152816-efbf5fbb-8d0a-4746-b10d-70404d90186b.png)

**Comment by jxckUK** [comment]
Purchased, I'll move this to a QC ticket now.

https://github.com/LondonsBlueLine/qc/issues/80

**Comment by Jjones033** [comment]
@CalLBLRP Is there an update on this vehicle? I know there is a spawn code for it however doesn't seem to be in the main server yet

**Comment by CalLBLRP** [comment]
It's been moved over to a QC ticket - We haven't done a push regarding vehicles yet as none of them have been qcd nor configured yet. We currently have a list of 20-30 vehicles to go through so it will take a while. 

Sorry!
