### ISSUE TITLE
Healing players that are not deceased/downed

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#56]
A way for NHS to heal players & a place at hospital to heal for when no nhs are available

**Comment by Kyymather** [comment]
London studio has just released a public definition that could be helpful for when no Las on

**Comment by jxckUK** [comment]
Closing this as it exists in a version two of LAS, which is a longer term fix. 

At the moment officers should leave the scene and call LAS.
