### ISSUE TITLE
civilian name tags

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#561]
### What division were you running as?

 SFC

### Describe the Bug

Civilian name tags are visible when the player is near. 

### Expected Behavior

no name tag

### To Reproduce

look at a civilian :)

**Comment by RI1CAL** [comment]
as well as this civilian armouries are not working in terms of any equipment showing up except body armour

**Comment by jxckUK** [comment]
> as well as this civilian armouries are not working in terms of any equipment showing up except body armour

I am aware of this issue already, will look to sort once I've fixed ped allocations.
