### ISSUE TITLE
Met Style BMW F750GS Bike Pack

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#566]
### Details

B1 Cal has shown me these bikes that I quite like would it be  possible to whack these in the scorpion garage. I would be able to provide funds but not until some point in February. 

![053C5311-0D1E-4262-BAC3-E02292826241](https://user-images.githubusercontent.com/117676135/213860053-752f3df9-f62a-4623-be28-bfd1710f6ee4.png)

### How did you find the asset?

Other

### Source

https://blighty3d.co.uk/products/met-style-bmw-f750gs-bike-pack

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by jxckUK** [comment]
We've kindly had the funds donated for these bikes by Ste (xBlackout on Discord) so we'll look to purchase them today.

**Comment by Jjones033** [comment]
Ah that's great thank you!!

**Comment by CalLBLRP** [comment]
The bikes have been added to our development server for testing, moving ticket over to: https://github.com/LondonsBlueLine/qc/issues/100
