### ISSUE TITLE
Boot not opening

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#568]
### What division were you running as?

Command

### Describe the Bug

All 3 of the Cupra Aztecas in Silver garage wont open their boot in order for me to rack the rifle 

### Expected Behavior

They should open the boot or at least prompt me to press e to open the boot

### To Reproduce

![image](https://user-images.githubusercontent.com/117676135/213909825-25546b46-c73e-414e-9508-bc9e80c29a80.png)

**Comment by jxckUK** [comment]
This is the modders fault unfortunately, it doesn't have a boot bone or openable boot. 

We usually fail QC for vehicles like this, but in light of the fact they were paid assets and that they are already in the game. I've added a fallback option, it will add a marker to the centre of the vehicle to open the "boot" which is better than no option at all.

Ideally no vehicle should be in without an openable boot.
