### ISSUE TITLE
Boot issue

### ISSUE THREAD

**Issue by pcmatt** [LondonsBlueLine/tracker#569]
### What division were you running as?

SFC

### Describe the Bug

When I rack a gun it sais close/open boot at the same time so it wont let me close the boot.

### Expected Behavior

Fix the issue.

**Comment by jxckUK** [comment]
> ### Expected Behavior
> Fix the issue.

That isn't "expected behaviour" though is it, thats a demand. Already fixed, just waiting to be pushed, no need to be rude.
