### ISSUE TITLE
New uniforms sent off

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#570]
Good evening had a mess around with some of the silver uniforms recently here is a list of them and what I would like them to replace.

"Chief Inspector Patrol (BCU)" - to replace Chief Inspector (Patrol)
Chief Inspector Armed - to replace Chief Inspector Armed
Chief Inspector High Vis Jacket - To replace Chief Inspector High Vis Jacket
Chief Inspector TSG - To replace Chief Inspector TSG

**Comment by Jjones033** [comment]
Just made a new uniform called Chief Inspector ADU

**Comment by Jjones033** [comment]
Evening Cal that is no worries. I'll try again tomorrow when I'm back on.

**Comment by CalLBLRP** [comment]
Hiya, 

This has all been added to our Dev Server. Will be pushed to main soon!
