### ISSUE TITLE
Dropdowns not displaying when using the CAD

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#571]
### What division were you running as?

RTPC

### Describe the Bug

CAD does not display any charges to select when creating an arrest report. The categories are there, but when you click them, the next drop down displays no charges. Also can not add markers to vehicles, i.e drugs marker. Nothing in the list. This was on the first attempt, so the CAD had only just been opened in the browser. This is also the case for the other player james30 on scene with me who initially tried to do the arrest report. 

### Expected Behavior

List to display list of charges in the drop down menu once catagory is selected in the arrest and PFN too, along with list of vehicle markers that should display to attach to a vehicle. 

### To Reproduce

go on to cad, try and put a vehicle marker on a vehicle. Also try and complete an arrest report and select charges.

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/214294596-705ffef4-9827-459b-86e5-dd09e63af795.png)

![image](https://user-images.githubusercontent.com/48030374/214294800-3456faab-1000-4e66-bcc2-ce44db97815d.png)

Need reproduction video or something as I can't replicate this issue.

**Comment by telboycafc** [comment]
well none of that was working last night for me or James, so wasn't just me.

**Comment by jxckUK** [comment]
I'm not saying it didn't happen, I'm saying I can't reproduce so if you can send a video or a repro then I can see what you're doing differently to me.

**Comment by telboycafc** [comment]
its working which is why i closed it, but confirmed with James it did happen to him too which he did. But I've been using it, and it seems to be working fine now, so i don't know what it was doing last night.

**Comment by jxckUK** [comment]
Okay - I'm going to leave it open as it clearly happened and it'll likely happen again if not resolved.

**Comment by telboycafc** [comment]
happens on and off for people. Refresh normally fixes it but not always.
