### ISSUE TITLE
Moveable and minimising CAD windows

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#572]
### Details

when doing a name or vehicle search, can there be an ability to minimise the windows instead of having to close them each time. So when doing a name search, you then have to close that window and then do a vehicle search. You sometimes forget the name and have to ask for ID again then close the vehicle search window and do a new name search. Could there be an ability to have the two open at the same time, and minimise one or the other instead of having to close one or the other on each occasion. 

If you forget to close one of the windows and try to open another one, i.e i have a name search window open and go to open another, a message comes up informing there is already a window open.

**Comment by jxckUK** [comment]
Submitted to CAD feature requests, will close this in favour of tracking over there.
