### ISSUE TITLE
DSU script not assigned to vehicle

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#573]
### What division were you running as?

DSU

### Describe the Bug

Ford Mondeo (BX68 KFL) does not have dog script assigned. 

### Expected Behavior

get dog in and out. 

### To Reproduce

get car out, use eye to get dog out, no options

**Comment by CalLBLRP** [comment]
Hiya @telboycafc,

This has been updated for you, will be pushed to main soon.
