### ISSUE TITLE
fleet issues

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#574]
### What division were you running as?

BTP

### Describe the Bug

ford focus, ford transit, unmarked and marked ford mondeo's, - white grille light doesn't come on with q

unmarked Vauxhall Astra and command ford focus - dash light doesn't come on with q

Vauxhall Movano bumper lights don't come on with q

these should all come on when the 999/response button is pressed on the light controls IRL.

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by CalLBLRP** [comment]
Hiya, 

I will look into this in the morning.

**Comment by CalLBLRP** [comment]
Hiya, 

@telboycafc can you please take a look at this, thanks!

**Comment by telboycafc** [comment]
@CalLBLRP Done....awaiting you or wolf to merge to main.
