### ISSUE TITLE
BTP Large station issues

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#575]
### What division were you running as?

BTP

### Describe the Bug

The taser cabinet is glitched through the wall.

### Expected Behavior

not to be glitched through the wall

### To Reproduce

go look at the wall

**Comment by jxckUK** [comment]
Nothing we can do about this for several reasons:

- [ ] Its an encrypted, purchased asset
- [ ] The asset is no longer sold and no longer updated
- [ ] The files are not editable

Only option would be to remove the asset entirely which seems nuclear.
