### ISSUE TITLE
Shooting through cars

### ISSUE THREAD

**Issue by Polcedg** [LondonsBlueLine/tracker#579]
### What division were you running as?

Sfc

### Describe the Bug

I was on scene of a call and shot someone in a van and it went through the wall of the van and hit my partner because of the slightest mistimed at the back of the van with 0 windows

### Expected Behavior

Not shooting through vans without windows

**Comment by colossalengineer** [comment]
Bullets would normal go though a van

**Comment by WolfRanger88** [comment]
This is something that is model and GTA default related so unable to resolve for particular vehicles.
