### ISSUE TITLE
Downing Street

### ISSUE THREAD

**Issue by colossalengineer** [LondonsBlueLine/tracker#580]
### Details

Downing Street
£100

### How did you find the asset?

Other

### Source

https://store.sinnersmodshop.co.uk/package/5376828

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by Jjones033** [comment]
That looks wicked

**Comment by jxckUK** [comment]
This is just not financially achievable or sensible for us to fund, its an extremely expensive roleplay prop.
