### ISSUE TITLE
Unmarked Landrover Discovery 

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#581]
### Details

Would it be possible to get this Disco added to silver garage?

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/?p=viewfile&file=145

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hello @Jjones033, 

This vehicle is indeed already in the server. It is under the **Special Escort Group** garage. If you wish to move this out of there into the ARV garage. Let me know, since we will have to find a replacement vehicle for the SEG garage. 

> I will keep this open for 1 hour or so!

**Comment by Jjones033** [comment]
Ah yes so it is I remember now. I will try and find the Range Rover that SEG use and see if we can swap them out. You can close it for now mate thank you

**Comment by S-Kahn** [comment]
Please do not move this to ARV :) - FI1

**Comment by Jjones033** [comment]
Sorry @S-Kahn im a bit confused to what you're saying.

**Comment by S-Kahn** [comment]
"If you wish to move this out of there into the ARV garage. Let me know" from what Cal had said

**Comment by Jjones033** [comment]
Ah okay sorry haha

**Comment by Jjones033** [comment]
@CalLBLRP https://gta5mod.net/gta-5-mods/vehicles/cars/2017-metropolitan-police-seg-ranger-rover-vogue-replace-els-1-0/ 

Would it be possible putting that for SEG and then moving the disco to silver?

**Comment by CalLBLRP** [comment]
Shall have a look; if I get a virus.. I am blaming you :D

**Comment by CalLBLRP** [comment]
Moved over to: https://github.com/LondonsBlueLine/qc/issues/104
