### ISSUE TITLE
LAS Handling 

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#583]
### What division were you running as?

LAS

### Describe the Bug

Handling lines for LAS51 & 52 to be looked at please - not the smoothest of drivers.

LAS52 is in backlog due to handling if you can give it the same handling as ‘ambulance’ - not sure if this has already been tried 

### Expected Behavior

Smooth driving 

### To Reproduce

Drive the vehicles 😂

**Comment by CalLBLRP** [comment]
Hiya, 

I will take a look at his for you in the morning.
