### ISSUE TITLE
Eye menu issue - Breathalyser

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#586]
### What division were you running as?

MPS RTPC Scorpion 

### Describe the Bug

When you use the third eye menu to search breathalyze etc and alot of the time it works but the rest of that time it doesn't it 
![image](https://user-images.githubusercontent.com/103907609/217603250-6cc98474-4830-4c59-83a8-6152a0ae411a.png)
Does This in your bottom right corner ^^^ it been doing it since 5:12Pm GMT Today 08/02/23

### Expected Behavior

It Gets Fixed instead of you closing this ticket it Needs **FIXING**

**Comment by CalLBLRP** [comment]
I would rather you be polite towards our development and asset team(s). The expected behaviour is what should be expected not what you wish to expect from us. 

As well as a reproduce method, if you are trying to report something to us, please ensure to answer everything we ask for correctly and in the best possible way. 

> Think of me as a new player and you are trying to explain something to me.

**Comment by colossalengineer** [comment]
> ### What division were you running as?
> MPS RTPC Scorpion
> 
> ### Describe the Bug
> When you use the third eye menu to search breathalyze etc and alot of the time it works but the rest of that time it doesn't it ![image](https://user-images.githubusercontent.com/103907609/217603250-6cc98474-4830-4c59-83a8-6152a0ae411a.png) Does This in your bottom right corner ^^^ it been doing it since 5:12Pm GMT Today 08/02/23
> 
> ### Expected Behavior
> It Gets Fixed instead of you closing this ticket it Needs **FIXING**
> 
> ### To Reproduce
> _No response_

Thanks for the feedback. From looking at the screen shot its a network issue to do with your end. If you look at the bottom right of the screen its states loading. This is because the game is trying to take control of the entity. @MikeyDeann
