### ISSUE TITLE
rockstar editor

### ISSUE THREAD

**Issue by Harry21313124** [LondonsBlueLine/tracker#587]
### What division were you running as?

content sever

### Describe the Bug

i cant use rockstar editor in the main and its a pain i was going to make videos with lights and sirens and it dont work it crashes and say something to do with Heathrow police station  

### Expected Behavior

no sure but just wondering if this could get fixed thx

### To Reproduce

i do not have a clip but it dont work

**Comment by CalLBLRP** [comment]
Please answer each question correctly when filling out a Bug Report. If you are unaware of what some words means like "Reproduce" or "Expected Behaviour". Please contact a member of the support team.
