### ISSUE TITLE
rockstar keeps crashing 

### ISSUE THREAD

**Issue by Harry21313124** [LondonsBlueLine/tracker#589]
### What division were you running as?

nothing

### Describe the Bug

when i try to make a vid it keeps crashing

### Expected Behavior

not sure could fix it thx. 

### To Reproduce

the a screen shot in content chat

**Comment by CalLBLRP** [comment]
This is not how to send a bug report, please fill out the information correctly and to ensure that all questions asked are being detailed so we are able to find out the real issue.
