### ISSUE TITLE
London underground station skin

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#593]
### Details

https://www.gta5-mods.com/misc/london-undeground-stations add some realism

### How did you find the asset?

GTA5Mods

### Source

https://www.gta5-mods.com/misc/london-undeground-stations

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
We wont be adding this in due to the server needing a purge of Assets and scripts to improve performance.
