### ISSUE TITLE
Foot patrol uniform

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#594]
### What division were you running as?

BTP

### Describe the Bug

Can the foot patrol or Station patrol uniform I saved in main be added to response please.

### Expected Behavior

x

### To Reproduce

x

**Comment by CalLBLRP** [comment]
Hiya @BA98x,

I am unable to locate this saved uniform. Could you please do it in the development server and save it in there.

Thanks!

**Comment by CalLBLRP** [comment]
Hello @BA98x,

Any update on this please?

**Comment by BA98x** [comment]
saved on dev
