### ISSUE TITLE
Arv uniforms

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#595]
### What division were you running as?

BTP

### Describe the Bug

![IMG_20230220_162016](https://user-images.githubusercontent.com/108870150/220157682-dd0a153d-59d7-4a72-ac9c-29042182e459.jpg)
Delete the ones scored out and replace the other one with the newly saved ARV with Hat please. All under firearms locker

### Expected Behavior

X

### To Reproduce

X

**Comment by CalLBLRP** [comment]
This has been completed for you, will be pushed to the live server soon.
