### ISSUE TITLE
Can't go unarmed

### ISSUE THREAD

**Issue by James-30lbl** [LondonsBlueLine/tracker#596]
### What division were you running as?

RTPC

### Describe the Bug

Once collecting weapons from the armoury and then selecting one (e.g. taser) i cannot then return the weapon to go unarmed,

### Expected Behavior

Be able to put weapon away and be unarmed.

**Comment by Jjones033** [comment]
I was also just experiencing this issue within the server. On the mele weapons of the weapon wheel there is only 3 options.
1. med bag
2. flashlight
3. Baton

No option to go unarmed and pressing the button which holsters your weapon and brings out your previous one does nothing.

Running as MPS Command and Control

**Comment by WolfRanger88** [comment]
This has now been resolved and revert made to armoury to fix this.
