### ISSUE TITLE
Add a MPS ERPT Peugot 208

### ISSUE THREAD

**Issue by Krisp1124** [LondonsBlueLine/tracker#597]
### Details

Really cool vehicle for ERPT.

### How did you find the asset?

GTA5Mods

### Source

https://uk.gta5-mods.com/vehicles/metropolitan-police-peugeot-308-pack

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by RI1CAL** [comment]
i support this very nice to replace our current 308 models

**Comment by CalLBLRP** [comment]
Hiya @Krisp1124, 

I will take a look at this for you in the morning.

**Comment by CalLBLRP** [comment]
Hiya @Krisp1124,

I wish to not get a virus from this website.. sorry but no can do. If you wish to view vehicles for requesting please look at these websites: 
- https://www.gta5-mods.com/
- https://unionmods.com/?p=home

![image](https://user-images.githubusercontent.com/98986766/222870402-bb10c859-10c5-4169-ac39-7e04f4df50f9.png)

**Comment by RI1CAL** [comment]
https://www.gta5-mods.com/vehicles/metropolitan-police-peugeot-308-pack

This is the link to the proper gta 5 mods page and no virus

**Comment by telboycafc** [comment]
@CalLBLRP proper version found by better cal
