### ISSUE TITLE
Scene guard script

### ISSUE THREAD

**Issue by Bettercal** [LondonsBlueLine/tracker#599]
This script is free and as we are a AI based server this would be perfect in aiding scenes from cordons, RTCs, protection groups and much more. 

https://unionmods.com/?p=viewfile&file=822

**Comment by WolfRanger88** [comment]
@colossalengineer is this something we can bring to an in house script and have this as an eye option or such? Potentially expand it out so we could place a ped, police, fire, NHW, etc with a couple of emotes for that ped that can be selected.

**Comment by WolfRanger88** [comment]
Moved to road map
