### ISSUE TITLE
BMW G30

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#600]
### Details

Unmarked Met BMW G30 for Panther potentially if this vehicle is not already in the garages.

### How did you find the asset?

Modder

### Source

https://moddexdev.co.uk/products/63

https://discord.com/channels/846457583454781512/876639764764307456/1079852611638923380

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by Jjones033** [comment]
https://discord.com/channels/846457583454781512/1005975791907110973/1078629387160793198

**Comment by CalLBLRP** [comment]
Hiya @Jjones033,

We will keep this on the backlog of vehicles that require funds. If individuals are willing to provide funds for the vehicle it will work a lot better. At this current time, we have no funds for assets within the LBL pot. 

Kind Regards,
Cal.

**Comment by Jjones033** [comment]
@CalLBLRP i noticed in game yesterday a car with the same number plate was in the senior constable garage ;))

**Comment by telboycafc** [comment]
Okay, we able to close this out then @Jjones033

**Comment by Jjones033** [comment]
Yeah course mate @telboycafc
