### ISSUE TITLE
ELS Issue

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#601]
### What division were you running as?

Command and Control - MPS

### Describe the Bug

AI doesn't respond to ELS on BTP37 - Volvo XC90 Unmarked in the donator garages.

### Expected Behavior

When ELS turned on for AI to react and pull over to the side to move out the way or to initiate a traffic stop.

### To Reproduce

1. Load into game
2. select MPS
3. Select command and control
4. receive equipment from armoury 
5. Head to mission row garages (station I spawned at)
6. select donator garage and then I think it is the advanced garage may be premium
7. initiate ELS and witness the AI not responding.

**Comment by CalLBLRP** [comment]
Hiya @Jjones033,

Just to confirm, this vehicle is a vehicle for MPS? Most of the vehicles within donator are indeed MPS vehicles or is this a completely different vehicle? 

Kind Regards,
Cal.

**Comment by Jjones033** [comment]
Morning @CalLBLRP 

Yes I was a bit confused by the spawn code as well but it's the unmarked Volvo XC90 found in the basic donator garage which does have that spawn code.

**Comment by Jjones033** [comment]
@CalLBLRP that will be a negative mate. AI are still not responding to ELS on BTP37

**Comment by CalLBLRP** [comment]
@telboycafc you can create one via the assets folder - I will show you during the week, I will get it created for you now though.

**Comment by telboycafc** [comment]
this is fixed, will close
