### ISSUE TITLE
Tactical Dog Unit skin for BMW 2 Series

### ISSUE THREAD

**Issue by MTS-1993** [LondonsBlueLine/tracker#602]
### Details

BMW 2 Series 

If approved - to be placed in DSUA garage

### How did you find the asset?

GTA5Mods

### Source

https://www.gta5-mods.com/paintjobs/ppolice-tactical-dog-unit-skin-for-bmw-2-series

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hiya,

I shall see what I can do.

**Comment by MTS-1993** [comment]
@CalLBLRP Cheers bud. I believe a 2 series is already in the game somewhere 🤔

**Comment by CalLBLRP** [comment]
haha no worries, I shall try and hunt it out.
