### ISSUE TITLE
UK German Shepherd Badges

### ISSUE THREAD

**Issue by MTS-1993** [LondonsBlueLine/tracker#603]
### Details

Realistic UK Police Dog harness with reflective badge

### How did you find the asset?

GTA5Mods

### Source

https://www.gta5-mods.com/misc/uk-german-shepherd-badges 

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hiya bud, 

I will take a look into these for you.

**Comment by MTS-1993** [comment]
Cheers @CalLBLRP 💪🏻

**Comment by telboycafc** [comment]
absolutely !! @CalLBLRP was this any good ?

**Comment by CalLBLRP** [comment]
@telboycafc I need to speak to Wolf in regards to this since it's technically EUP so that's Wolf's department.

**Comment by WolfRanger88** [comment]
To make this modification, customisation will need to be made to dog script by others as currently we cannot apply eup to our dogs as they are not a player model as such.

**Comment by telboycafc** [comment]
Unfortunately, this doesn't look like its going to be possible which is a shame due to the work needed as stated from wolf above. I'll keep the ticket in case there does become a solution and we still have the link as those badges are nice.

**Comment by MTS-1993** [comment]
No problem Tel. Thanks for following this up mate.
