### ISSUE TITLE
FivePD issue 

### ISSUE THREAD

**Issue by Jimcon5** [LondonsBlueLine/tracker#604]
### What division were you running as?

SFC

### Describe the Bug

I was on duty via F11 and there's no calls coming through

### Expected Behavior

to start producing calls

**Comment by telboycafc** [comment]
has this issue been sorted ?

**Comment by WolfRanger88** [comment]
@Jimcon5 have you now been able to use fivepd? Please make sure you join a department in game via the police computer in a car, this will let you then see calls 

I am closing this as you have not since replied. Pop a ticket in discord if you get the same issue and I will take a look.
