### ISSUE TITLE
Ford Focus 2016 - Metropolitan Police - ERPT

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#605]
### Details

Who doesnt love a free vehicle mod.

for BCU

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/?p=viewfile&file=1011

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hiya bud,

This has been added to the selection of vehicles within the big push - It will be added to development soon, already got it bookmarked when I was notified about the model as I have been waiting for this type of model for ages!

**Comment by Jjones033** [comment]
@CalLBLRP great minds think alike ;))
