### ISSUE TITLE
Speedzones M Menu

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#606]
### What division were you running as?

MPS - Command and control

### Describe the Bug

I was on a scene which required a road closure due to an ongoing incident in the road. I placed two speedzones one at each end of the junction along with multiple props to say the road is closed. The AI ignored this and crashed into the props along with driving through the gaps in the props where a speed zone of 0 was placed.

First link shows me setting up SZ https://medal.tv/games/gta-v/clips/ZGxk5bDYBE7jy/d133785ed8eV?invite=cr-MSxEd2EsMTcyMjk1MjA3LA

Second link shows traffic ignoring it https://medal.tv/games/gta-v/clips/ZGwDETI03_cwE/d133794QS8QQ?invite=cr-MSxGajIsMTcyMjk1MjA3LA

### Expected Behavior

The expected behaviour is for the AI to respect the speedzone and not drive straight through it.

### To Reproduce

1. open up game
2. select MPS - command and control
3. attend a scene
4. using M menu set up speed zone
5. using M menu place road closed sign in speedzone along with two big cones at either end of the junction 
6. watch the chaos

**Comment by colossalengineer** [comment]
I've identified the issue I will fix when I get back home. @WolfRanger88 can you check lbl requests on GitHub as I have requested to copy the lbl repo to my pc so I can fix it while I'm away.

**Comment by telboycafc** [comment]
whats the update on this @colossalengineer

**Comment by colossalengineer** [comment]
This happens when the server has a lot to handle. I've not been able to find a solution.
