### ISSUE TITLE
Fault with ADU vehicle

### ISSUE THREAD

**Issue by MTS-1993** [LondonsBlueLine/tracker#607]
### What division were you running as?

DSU - Armed Dog Unit

### Describe the Bug

The new Ford Mondeo in ADU does not allow dogs to be placed in the crates at the rear. 

### Expected Behavior

Allow dogs to be placed and removed by using 'the eye'

**Comment by CalLBLRP** [comment]
Hiya bud,

This was fixed last night and has already been pushed to the live server. Please let me know if this still doesn't work when you next go on.

**Comment by MTS-1993** [comment]
Hey @CalLBLRP 

I've just jumped on mate and gave it ago but unfortunately it still doesn't work. The option isn't there when using the eye :/ ![image](https://user-images.githubusercontent.com/125998810/225927895-c15f1a0a-b73e-419b-be23-82d6d2553d84.jpeg)

**Comment by MTS-1993** [comment]
@CalLBLRP MPS286 mate
