### ISSUE TITLE
New BTP Kuga

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#609]
### Details

https://unionmods.com/?p=viewfile&file=1003  2014 Ford Kuga 

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/?p=viewfile&file=1003

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
@Gibby543 has this been put in yet ?

**Comment by CalLBLRP** [comment]
These have been added to the Development Server. QC will be commencing soon! - https://github.com/LondonsBlueLine/tracker/issues/601

**Comment by Gibby543** [comment]
Any update on this
