### ISSUE TITLE
MAKE FIREARMS CARS FASTER

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#61]
_## Issue created anonymously for a user ##_
I would prefer if the firearms fleet is faster as the cars are very slow and it took me like 4 minutes to do 1 mile for a Active Shooter, for example the XC90 (Unmarked) maxes at like 80mph. Please look over the whole fleet to ensure firearms vehicles are at least over 110mph, 

Many thanks.

**Comment by CalLBLRP** [comment]
Thank you for your opinion on our SFC vehicles.. However, I have tested the Unmarked XC90 and the vehicle is maxing around 90-95. Can you please attach any recordings you may have with your vehicle maxing out "at like" 80mph.

**Comment by jxckUK** [comment]
In regards to the performance of the XC90 it is also worth noting that I wouldn't expect this to be a RRV. Something smaller with a higher performance line should be used when intending to rapidly deploy to a scene.

As long as there are suitable vehicles in SFC that can be used as RRVs then I'm happy for this to be closed out.
