### ISSUE TITLE
[MLO] Bolingbroke Penitentiary

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#610]
It is an American themed MLO however it will give the prison in game some use.

Is this a possibility. There is a possibility to work on this MLO from the files to create a more British feeling as stated in the description it does say we can improve it.

https://www.gta5-mods.com/maps/prison-3-mlo-interiors-bolingbroke-penitentiary-fivem-ragemp

**Comment by telboycafc** [comment]
I can't see why we wouldn't be able to add this in, will need to pass QC.

**Comment by Firemanryan** [comment]
its fairly easy to de Americanise it. ill download it and have a look and see what i can do. it will be next week before i get to look at it though @telboycafc

**Comment by Jjones033** [comment]
Hi guys is there an update on this possible MLO?
