### ISSUE TITLE
BTP Garage

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#611]
### What division were you running as?

BTP

### Describe the Bug

Can BTP 47 be added into the Garage as a Ford Kuga
And can the "Peugeot Kuga" be renamed Peugeot 5008

### Expected Behavior

As above 

### To Reproduce

Thanks :)

**Comment by telboycafc** [comment]
hi gibby. what is btp 47 at the moment then ?

**Comment by telboycafc** [comment]
This has been completed and pushed to the Dev. Ready for merge when others are ready to main. There are other commits so haven't pushed to main yet.

**Comment by Gibby543** [comment]
Hi mate BTP 47 is a Ford Kuga can the other Two ford Kuga's be named Ford kuga instead of Peugeot Kuga

**Comment by telboycafc** [comment]
this has been done.
