### ISSUE TITLE
New MPS GC vehicle suggestion

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#613]
### Details

Mercedes Benz AMG GT els, download contains a red/blue and a blue/blue, I would only want the blue obviously. The post does not mention anything about FiveM.

### How did you find the asset?

LSPDFR

### Source

https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/41543-mercedes-amg-gt-els-addon-rb-bb/

### I have done the following

- [ ] Checked its suitable for FiveM
- [ ] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hiya mate, this vehicle has been denied. Sorry for any inconveniences; please keep the suggestion coming!
