### ISSUE TITLE
Tape menu command not working after using it a few times

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#614]
### What division were you running as?

MPS - Command and control

### Describe the Bug

Decided to create a little scene at franklins house using the tape menu and set some tape up. After adjusting 4 parts of my tape to the right height i then went to try and edit the height of my 5th tape however when doing the /tapemenu command nothing would come up. you can see from the clip /tape command works but tapemenu doesnt.

@telboycafc 

https://medal.tv/games/gta-v/clips/115deTrgaSGYgp/d1337k3xu605?invite=cr-MSw0ZW0sMTcyMjk1MjA3LA

### Expected Behavior

when i do /tapemenu to come up with the tapemenu

### To Reproduce

1. start up game
2. MPS - Command and control
3. Use cones from prop menu 
4. collect tape from car
5. start placing tape on the cones
6. edit the height of the first 4 tapes
7. attempt to edit the 5th tape and show you cant bring up the menu

**Comment by telboycafc** [comment]
Hello Josh, I have replicated this in the dev, and could not find any issues with the tape. May have been a off the cusp issue. But i have tried the tape menu more than 7 times and worked on all occasions along with spawning tape and changing the height, and found no issues....in essence....it seems like a you problem..... lol
