### ISSUE TITLE
BTP Senior Constable Tag

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#615]
### What division were you running as?

BTP

### Describe the Bug

Can i get this tag made pls :) Access to BTP Command Garage in game 

### Expected Behavior

:D

### To Reproduce

:D

**Comment by telboycafc** [comment]
whats the tag ?

**Comment by Gibby543** [comment]
BTP Senior Constable

**Comment by CalLBLRP** [comment]
Done.
