### ISSUE TITLE
CoLP Issues

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#616]
### What division were you running as?

CoLP

### Describe the Bug

As CoLP We Can't Track People As It thinks were Civ And Were Not Able to Use the Third Eye Menu As CoLP.

### Expected Behavior

We Know it's New and expected to have some bugs but if you can could you fix it please.

**Comment by RI1CAL** [comment]
can confirm this is the case, may require @jxckUK . Eye menu does not work for police interactions nor tracking

**Comment by telboycafc** [comment]
@WolfRanger88 do we know what the issue was, or if it has been resolved ?

**Comment by WolfRanger88** [comment]
It's the track menu which is colossal or Jack I believe.

Although why is colp being used before full release?!!!

**Comment by telboycafc** [comment]
Believe these issues have been resolved.
