### ISSUE TITLE
CLP04 ELS

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#617]
### What division were you running as?

MPS - Command and control (COLP)

### Describe the Bug

CLP04 Ford Transit PT does not have any ELS configured

### Expected Behavior

to have ELS

### To Reproduce

Get CLP04 out of garage press keybind to turn lights on and see it has no ELS
press keybind for horn and see it goes to the american siren

**Comment by colossalengineer** [comment]
We know it will be pushed on next update

**Comment by colossalengineer** [comment]
> @colossalengineer was this done ?

Read above
