### ISSUE TITLE
DSU Vehicles 

### ISSUE THREAD

**Issue by KX11Liam** [LondonsBlueLine/tracker#619]
### Details

https://www.gta5-mods.com/paintjobs/met-police-dog-car-skoda

### How did you find the asset?

GTA5Mods

### Source

https://www.gta5-mods.com/paintjobs/met-police-dog-car-skoda

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by CalLBLRP** [comment]
Hiya, 

This has been added to our Development Server. QC will commence soon! - https://github.com/LondonsBlueLine/qc/issues/109
