### ISSUE TITLE
LFB Fire crash

### ISSUE THREAD

**Issue by Firemanryan** [LondonsBlueLine/tracker#621]
### What division were you running as?

LFB

### Describe the Bug

went to put a fire out with foam. 

### Expected Behavior

not to crash 

### To Reproduce

[CfxCrashDump_2023_04_13_19_23_04.zip](https://github.com/LondonsBlueLine/tracker/files/11225791/CfxCrashDump_2023_04_13_19_23_04.zip)

**Comment by CalLBLRP** [comment]
Hiya mate, we will put this on our priority list for you. We'll review the issue during the week!

**Comment by telboycafc** [comment]
Recent update was down loaded from london studios. Hopefully resolved. If it happens again let us know.
