### ISSUE TITLE
Vehicle Locking and Unlocking not working.

### ISSUE THREAD

**Issue by MrJC9** [LondonsBlueLine/tracker#623]
### What division were you running as?

LAS

### Describe the Bug

This issue is present across all division's and services. You are currently unable to lock and unlock your vehicle using 'U'. This issue has been tested by myself and @colossalengineer including others in game. I believe colossal was looking at this with me in game and disabled the MOE script and vehicle locking started working again so it looks to be a conflict between Vehicle locking and the MOE script. 

### Expected Behavior

Vehicles to lock and unlock using 'U'.

### To Reproduce

Simply load into the server, get into a vehicle and try to use 'U' to lock/unlock. You will see a message appear in the top corner that says 'No door found'.

**Comment by telboycafc** [comment]
@colossalengineer update please ?

**Comment by colossalengineer** [comment]
I'm not the one working on it I've told A6 Cal which it's his script that is corsing the issue.

**Comment by telboycafc** [comment]
@colossalengineer what is the issues with this ?

**Comment by colossalengineer** [comment]
Method of entry has the same key as vehicle locking. U KEY.

**Comment by jxckUK** [comment]
The key bind can be changed for the car lock within your key mappings to resolve this in the short term. I can roll out a change to the default mapping of the car locks (as there is no way to change MOE default) but this will only change for new players.

**Comment by jxckUK** [comment]
The default keybind has been changed to "O" for locking and unlocking vehicles. Existing players should manually update their keybind within the settings to avoid conflicts.
