### ISSUE TITLE
Spawn Selection

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#624]
### What division were you running as?

None

### Describe the Bug

When i loaded into the dev server it only gave me the option to spawn as City of London Police or Civilian
![Desktop Screenshot 2023 04 16 - 13 43 23 54](https://user-images.githubusercontent.com/117676135/232312407-593da63f-2eb1-4a0f-b7b7-57f6fbfb95b5.png)

### Expected Behavior

To have have all the relevant services lsited such as LAS, LFB, MPS, Civ and CoLP

### To Reproduce

to load into dev and spawn selection

**Comment by Jjones033** [comment]
Did click refresh and nothing changed

**Comment by CalLBLRP** [comment]
We will take a look. However, this is the Development Server so technically there will be bugs/things we need to review, not really a bug at this current time though.
