### ISSUE TITLE
The new prop menu

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#626]
### What division were you running as?

Met - C&C

### Describe the Bug

The new scene menu that should come up when clicking M does not seem to open anymore

### Expected Behavior

To open up the scene menu to allow us to place the props down

### To Reproduce

Load into game
Met
command
Spawn
press M

**Comment by colossalengineer** [comment]
Fix Wolf pushed to main to early. Before I fixed it in dev as toolkit was changed

**Comment by telboycafc** [comment]
@colossalengineer has this been resolved do you know ?
