### ISSUE TITLE
Live map

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#627]
### What division were you running as?

N/A

### Describe the Bug

The live map on CAD does not work and prompts you to view documents on this link
https://docs.snailycad.org/docs/fivem-integrations/live-map#connecting-to-snailycadv4

I suspect it will be because of the merge over to jack.

### Expected Behavior

To allow us to track units 

### To Reproduce

Login on Cad
Go to live map see the prompt in the top corner

**Comment by telboycafc** [comment]
this has been fixed. Thanks for reporting.
