### ISSUE TITLE
BTP Volvo xc90

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#629]
### What division were you running as?

AFO

### Describe the Bug

Handling on the XC90 BTP Firearms suv is like a truck

### Expected Behavior

Car handling

### To Reproduce

Drive the car lol

**Comment by CalLBLRP** [comment]
@RI1CAL 

Hiya lad, any chance you could give this a quick look over for me please?

**Comment by Gibby543** [comment]
Any update on this

**Comment by Gibby543** [comment]
Anything?

**Comment by colossalengineer** [comment]
![Uploading image.png…]()

**Comment by colossalengineer** [comment]
Its on are road map

**Comment by telboycafc** [comment]
This has been fixed by me. Sacked the modders handling line off and put our own in. Tested and works.
