### ISSUE TITLE
BTP EMERGENCY INTERVENTION UNIT

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#631]
### Details

Features;
-ELS Enabled
-1:1 Accurate Setup
-Created with joint Effort from Prime X IGM
 
(Re Skin Perms Pending)

### How did you find the asset?

Modder

### Source
https://discord.com/channels/932777610184888351/933001131997663263/1100532951625768981
### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by CalLBLRP** [comment]
Good Evening, 

This request has been put on the backlog since we are required to find the sufficient funds for the asset(s). 

This could take some time. 

Thanks, 
 Cal.

**Comment by telboycafc** [comment]
As above from Cal, also we are going to need an overhaul of what assets we have, and need a clear out, before adding more at the moment. So this will be put on ice.

**Comment by telboycafc** [comment]
@CalLBLRP funds have been sent over for this.
