### ISSUE TITLE
RTPC BMW G21

### ISSUE THREAD

**Issue by James-30lbl** [LondonsBlueLine/tracker#632]
### What division were you running as?

RTPC

### Describe the Bug

/matrix install does not work on this vehicle even though it has a matrix board.

### Expected Behavior

To be able to control matrix board

### To Reproduce

t /matrix install

**Comment by James-30lbl** [comment]
![image](https://github.com/LondonsBlueLine/tracker/assets/124095335/137092d2-bb82-4902-8473-c271b341c9d5)

**Comment by telboycafc** [comment]
James that vehicle may have its own board in the model. To turn it on is normally the L key but you haven't put the MPS number so I cant even check.

**Comment by James-30lbl** [comment]
Hi Tel, thanks for the reply. From memory I think it did have its own board. Also, after posting it Colossal did say to me in a VC it may also be because it was only for donator vehicles. 
Unfortunately we can't get MPS numbers so we are unable to report them accurately.

**Comment by telboycafc** [comment]
Hello James. Looking at the config, yes it is a donator perk for specific vehicles in donator garage. This vehicle is not on the list for it.

**Comment by telboycafc** [comment]
wasnt a donator vehicle you piece of nob cheese.... much love.
