### ISSUE TITLE
BMW M2 Gold command Garage

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#635]
### What division were you running as?

C&C

### Describe the Bug

Hello, please can you add spikes and ANPR to the BMW M2 in gold command garage. Thank you.

### Expected Behavior

.

### To Reproduce

.

**Comment by telboycafc** [comment]
jam spikes should already be in the boot of this car. ANPR has been added in dev but waiting for push aiming for friday.

**Comment by JamStonedScones** [comment]
Sorry, can we not add the FivePD spikes to this please as they actually work haha

**Comment by telboycafc** [comment]
done and pushed.
