### ISSUE TITLE
Server connection timed out! 

### ISSUE THREAD

**Issue by MTS-1993** [LondonsBlueLine/tracker#636]
### What division were you running as?

Command and Control

### Describe the Bug

Client -> server connection timed out. Please try again later

![Picture1](https://github.com/LondonsBlueLine/tracker/assets/125998810/0c29591d-7398-4970-8c1b-0df470f73114)

### Expected Behavior

Not to keep disconnecting - It chucked all players out of the server

### To Reproduce

N/A

**Comment by S1Josh** [comment]
Client -> server connection timed out. Please try again later.

Timeout info: game=22.44 ±6.96 ~0, recv=2416.38 ±9281.64 ~38364, send=24.00 ±3.61 ~27

Timeout - 20:41

**Comment by CalLBLRP** [comment]
Sounds like a you issue.

**Comment by S1Josh** [comment]
@CalLBLRP Thank you darling look forward to hearing you have fixed it x

**Comment by MTS-1993** [comment]
> Sounds like a you issue.

I think its a you issue!!!
