### ISSUE TITLE
[ELS] PEUGEOT 308 CoLP

### ISSUE THREAD

**Issue by connoreth** [LondonsBlueLine/tracker#637]
### Details

PEUGEOT 308

### How did you find the asset?

Modder

### Source

https://unionmods.com/file/els-peugeot-308-308---generic---response

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by connoreth** [comment]
This will be for CoLP thanks <3

**Comment by connoreth** [comment]
RPU

**Comment by telboycafc** [comment]
Hello Connor. 

Sadly this has been declined due to vehicles lack of quality. Also, LBL is in the process of having a good clear out of vehicles. There may be some vehicles that become available in the server during the reshuffle that could be used.
