### ISSUE TITLE
 2020 VOLVO V90

### ISSUE THREAD

**Issue by connoreth** [LondonsBlueLine/tracker#638]
### Details

 2020 VOLVO V90

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/file/els-2020-volvo-v90---generic---roads-policing

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by connoreth** [comment]
This will Be for CoLP

**Comment by connoreth** [comment]
RPU again <3

**Comment by telboycafc** [comment]
This is going to be declined due to RUP disbanded in COLP, Plus the need for a reduction in server vehicles.
