### ISSUE TITLE
CoLP RPU 

### ISSUE THREAD

**Issue by connoreth** [LondonsBlueLine/tracker#639]
### Details

AUDI A4

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/file/els-audi-a4-2017-generic-rpu-unmarked-

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
Division disbanded, vehicles not required.
