### ISSUE TITLE
TFU CoLP

### ISSUE THREAD

**Issue by connoreth** [LondonsBlueLine/tracker#640]
### Details

BMW X5 2016

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/file/els-bmw-x5-2016-fictional-armed-response-vehi

### I have done the following

- [x] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
Division disbanded. Vehicle not required.
