### ISSUE TITLE
TFU CoLP Vehicle

### ISSUE THREAD

**Issue by connoreth** [LondonsBlueLine/tracker#641]
### Details

 VOLVO V90 R

### How did you find the asset?

Union Mods

### Source

https://unionmods.com/file/2019-police-volvo-v90-r-design-els-enabled

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
Nice model, but division has been disbanded, vehicle is not required now.
