### ISSUE TITLE
Siren for btp

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#643]
### Details

Hi if possible could the Clear tone version of this siren be added to btp vehicles?

### How did you find the asset?

Other

### Source

https://modification-universe.com/forums/resources/standby-rsg-mcs-32.862/

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [ ] Yes
- [X] No

**Comment by telboycafc** [comment]
Unfortunately, we have no server slots left for any more sirens to add. Any new sirens would have to overwrite existing ones, and at the moment, there are none we want to delete.
