### ISSUE TITLE
Btp Polestar 

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#644]
### Details

Polestar 2 Marked BTP

### How did you find the asset?

Modder

### Source

https://blighty3d.co.uk/collections/new-products/products/2022-btp-style-polestar-2-marked

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by telboycafc** [comment]
Direction of BTP at the moment as you're aware gibs is it's being merged with MPS. It's a nice model but we have too many vehicles at the moment server wide.
