### ISSUE TITLE
SFC G36C

### ISSUE THREAD

**Issue by Dunley2034** [LondonsBlueLine/tracker#646]
### What division were you running as?

SFC

### Describe the Bug

When you use the SFC weapon G36C you are unable to unfold the weapon on /weapons

### Expected Behavior

When you open the menu go to G36 then stocks and press fold stock and the weapons stock is folded

**Comment by telboycafc** [comment]
@Dunley2034 does this still occur  ?

**Comment by S1Josh** [comment]
@Dunley2034 Do you get the G36 out of the armoury before attempting to customise the weapon as I used the weapon last night with no issues at all

**Comment by telboycafc** [comment]
@Dunley2034

**Comment by Dunley2034** [comment]
Yes that’s what I did but the only thing is everything else works apart from unfolding the stock is the only problem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by colossalengineer** [comment]
The menu was removed to stop people from cheating the weapon in when not needed.
