### ISSUE TITLE
Benzz Davis Police Station Updated 

### ISSUE THREAD

**Issue by Dunley2034** [LondonsBlueLine/tracker#649]
Just mentioning that davis police station has had an update and it might be something good to add the the server  
![image](https://github.com/LondonsBlueLine/tracker/assets/128969342/9225f695-195d-4b4b-80c6-a2e1ce84dfd3)

Message Link: https://discord.com/channels/744733620840955905/899327636474572851/1118174762888347709

**Comment by CalLBLRP** [comment]
Hiya, 

Thank for letting us know. We will look into this shortly! 

Thanks,
Cal.

**Comment by telboycafc** [comment]
Sadly, Benz will not provide us with the update, as the person who purchased this for the server is is no longer part of the leadership team. And so we can not provide the proof of purchase as said person is no longer here. I have tried explaining that the asset was brought for the server and that the server own the asset, not an individual, but sadly Benz does not seem interested and will only deal with the purchaser. This is disappointing and will most probably deter us away from any future purchases there, as it does seem a bit unfair.
