### ISSUE TITLE
Panther unit

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#65]
Can i please have the following vehicles moved from RTPC into a sub-garage like Scorpion and interceptors called Panther.
![image](https://user-images.githubusercontent.com/100094183/154863589-b9994a90-5f7d-4fbd-8488-d93f4e3ea0ca.png)
![image](https://user-images.githubusercontent.com/100094183/154863599-2521538f-e0c1-4816-9515-095fe7b74e40.png)
![image](https://user-images.githubusercontent.com/100094183/154863624-7ba37eb8-33db-4f81-b362-f94711da771d.png)
![image](https://user-images.githubusercontent.com/100094183/154863629-500073fd-e7b5-4419-8079-fe34f84e12d5.png)
![image](https://user-images.githubusercontent.com/100094183/154863638-45c474a6-8e81-4515-b811-080b7ac278f2.png)
![image](https://user-images.githubusercontent.com/100094183/154863647-816795d2-991d-4318-a092-5951dd47b7f9.png)
![image](https://user-images.githubusercontent.com/100094183/154863654-053a4248-72b3-4584-83d3-cb8957e0a984.png)

Can I please have a copy of this one vehicle from CPS also
![image](https://user-images.githubusercontent.com/100094183/154863691-33235a20-daf2-4bb0-ac71-4ef27212ac28.png)

and also move these from Interceptor to panther also
![image](https://user-images.githubusercontent.com/100094183/154863739-eb6eead9-c6cc-4d7f-abe9-e61ea916762e.png)
![image](https://user-images.githubusercontent.com/100094183/154863746-756cac1d-3773-4233-a277-101881c3ab79.png)
![image](https://user-images.githubusercontent.com/100094183/154863755-a1403a22-737f-4f18-be10-33f5108ddc9e.png)
![image](https://user-images.githubusercontent.com/100094183/154863764-7e675d87-af88-475a-9029-671045a6ebca.png)

and can i have this uniform added into a locker room sub section for panther (black shirt traffic officer with body armor on 0)
![image](https://user-images.githubusercontent.com/100094183/154863881-8a7dc9d0-bc85-45d3-a1a6-f17685db1d70.png)

Thanks guys love you all!!

**Comment by JamStonedScones** [comment]
for dale, move to Bronze command and reskin for supervisor please bby 
![image](https://user-images.githubusercontent.com/100094183/156938154-345e3d56-4539-4d4a-982b-61a06fe904b2.png)

**Comment by JamStonedScones** [comment]
Mess with the handling of some interceptor cars, not too clear on what we are going with them right now need to sit and work it all out.

**Comment by telboycafc** [comment]
Uniform is all done for Panther.

**Comment by Dale1987** [comment]
Me and jam have spoken a little about this,  will be looking to start this over the weekend when i have sone time off work

**Comment by telboycafc** [comment]
@Dale1987 has this been completed ?

**Comment by Dale1987** [comment]
yes just the handling of some vehicles we need to look at soon

**Comment by jxckUK** [comment]
This was completed.
