### ISSUE TITLE
Camera issue 

### ISSUE THREAD

**Issue by Elliof999** [LondonsBlueLine/tracker#651]
### What division were you running as?

BTP 

### Describe the Bug

In the BTP command, garage the Jaguars camera is really far away from the vehicle

### Expected Behavior

Makes a camera angle like all the other cars

**Comment by telboycafc** [comment]
errrm...we don't adjust the camera on the cars. Have you tried pressing V on your keyboard to change the view ?

**Comment by Elliof999** [comment]
Yes I have the camera is just very far away

**Comment by telboycafc** [comment]
@Elliof999 BTP done have a jaguar in any of their garages......??

**Comment by Elliof999** [comment]
Meant mustang

**Comment by telboycafc** [comment]
This has been tested, and i can not find anything wrong with the vehicle. Press V on you keyboard to move the camera view. There is no other action that can be taken on this, as i can not find any faults.
