### ISSUE TITLE
Station 

### ISSUE THREAD

**Issue by Elliof999** [LondonsBlueLine/tracker#653]
### What division were you running as?

BTP

### Describe the Bug

The BTP station at Mirro Park is glitched there is half a shelf coming through the outside wall 

### Expected Behavior

It not to come through the wall 

### To Reproduce

Got the the station and stand outside the car park wall and you will see

**Comment by telboycafc** [comment]
We are not able to modify any BTP stations as we are not the original creators. Time being this will have to be something we persevere with. It doesn't have a major impact to game play.
