### ISSUE TITLE
Body cam

### ISSUE THREAD

**Issue by Gibby543** [LondonsBlueLine/tracker#655]
### What division were you running as?

BCU

### Describe the Bug

Can we remove this script as its annoying and dosent really serve a purpose and takes up space.

### Expected Behavior

No Body cam 

### To Reproduce

Remove body cam hahah

**Comment by telboycafc** [comment]
A vote has been put on the server for everyone's opinion. You can disable it by removing any key bind you have set up for it.

**Comment by telboycafc** [comment]
Body cam has been voted out, so it will be taken out.
