### ISSUE TITLE
LBL website 

### ISSUE THREAD

**Issue by Elliof999** [LondonsBlueLine/tracker#656]
### What division were you running as?

NA

### Describe the Bug

Could we have the BTP page on the website updated please 

### Expected Behavior

For the sgt app to be closed and the commands structure to be updated 

### To Reproduce

Na

**Comment by S1Josh** [comment]
Afternoon elliot I will be working on the website regarding other areas. I will add this to my list

**Comment by S1Josh** [comment]
BTP page updated

**Comment by telboycafc** [comment]
thanks @S1Josh
