### ISSUE TITLE
MPS 276 get registered as a police car

### ISSUE THREAD

**Issue by pwatts67** [LondonsBlueLine/tracker#657]
### What division were you running as?

SFC

### Describe the Bug

MPS 276 isnt registered as a police car so i doesn't let me pull people over and AI dont respond to ELS

### Expected Behavior

i thought the AI were gonna respond to the ELS nad let me pull them over

### To Reproduce

ive not got anything else

**Comment by telboycafc** [comment]
hello, we will look in to this at some point and fix if it is fixable. 

thanks.

**Comment by telboycafc** [comment]
fixed tested and will be pushed on Friday in the update.

**Comment by pwatts67** [comment]
ok thanks tel
