### ISSUE TITLE
LAS66

### ISSUE THREAD

**Issue by Elliof999** [LondonsBlueLine/tracker#658]
### What division were you running as?

NA

### Describe the Bug

LAS66 has a missing texture on the center post could this be fixed please 

### Expected Behavior

For LAS66 to have all its textures

### To Reproduce

Load in LAS66 and look at center post and it will either be gray or purple

**Comment by CalLBLRP** [comment]
Hello,

As we have already discussed in a voice channel. We are already aware of this issue and is already getting fixed. 

Please be patient.

Thanks,
Cal.

**Comment by CalLBLRP** [comment]
This has been fixed and will be in the main server on our Friday update.

**Comment by Elliof999** [comment]
LAS66 is now missing other textures
