### ISSUE TITLE
LAS vehicles

### ISSUE THREAD

**Issue by riley202010** [LondonsBlueLine/tracker#659]
https://unionmods.com/file/els-volvo-xc90-laa-physician-response-unit

**Comment by CalLBLRP** [comment]
We already have this vehicle. Thanks for the suggestion though!

**Comment by riley202010** [comment]
> We already have this vehicle. Thanks for the suggestion though!

Ok I have more on the website do you kown when it's coming out

**Comment by colossalengineer** [comment]
> 

that has not yet been decided but I would recommend in the mean time you become a LAS AP. As well as show dedication to LAS

**Comment by colossalengineer** [comment]
@riley202010

**Comment by riley202010** [comment]
> @riley202010 

Ok
