### ISSUE TITLE
[FEAT]Command uniforms

### ISSUE THREAD

**Issue by MrP3n9u1n** [LondonsBlueLine/tracker#66]
A update to command uniform so we dont just have white shirts, and have a option to put on vest or other items of clothing

**Comment by jxckUK** [comment]
You need to give us numbers really mate, set it up how you want it in game and send it across.

**Comment by MrP3n9u1n** [comment]
![20220225160220_1](https://user-images.githubusercontent.com/75227401/155759140-a930d848-8be7-4385-b2d4-2bc1868d7ba8.jpg) can we have a option for shirt only and one for vest for all command

**Comment by telboycafc** [comment]
i am slightly confused about what is being asked here. Is this a uniform you would like putting in the locker ?

**Comment by telboycafc** [comment]
completed and ready to be pushed to main build.
