### ISSUE TITLE
LFB 64M turntable ladder

### ISSUE THREAD

**Issue by pwatts67** [LondonsBlueLine/tracker#662]
### Details

a LFB turntable ladder 64m working 

### How did you find the asset?

Other

### Source

https://www.alienmodding.co.uk/fire-listings-page-3/lfb-working-64m-tl

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by pwatts67** [comment]
im willing to pay for it if need be

**Comment by telboycafc** [comment]
Hello, 

Thanks for the suggestion. We do have a turn table ladder vehicle in game already. We will put this under future review.
