### ISSUE TITLE
new met sirens and London textures

### ISSUE THREAD

**Issue by riley202010** [LondonsBlueLine/tracker#664]
### Details

watch https://www.youtube.com/watch?v=m7dZ-SAamCk&t=274s 
in till the end and you will know what i mean
4:01 

i am willing to pay for it if need 

### How did you find the asset?

Other

### Source

https://www.youtube.com/watch?v=m7dZ-SAamCk&t=274s

### I have done the following

- [X] Checked its suitable for FiveM
- [X] Checked its permitted/authorised for FiveM
- [X] Checked it has an appropriate skin or has reskin permissions

### Does this vehicle require funding?

- [X] Yes
- [ ] No

**Comment by CalLBLRP** [comment]
Hiya,

Not sure what you are trying to request here? You have just placed a youtube video and not the link to the way we can look at purchasing said sirens. 

Additionally, we aren't looking for any new sirens as of yet. However, we thank you for your suggestion! 

Regards,
Cal.
