### ISSUE TITLE
seat bets 

### ISSUE THREAD

**Issue by riley202010** [LondonsBlueLine/tracker#665]
### What division were you running as?

all cars in all teams 

### Describe the Bug

the seat belts script dost work 

### Expected Behavior

so i click m as it is for me and when i test it out before going on pitrol i can jump out of the car

**Comment by James-30lbl** [comment]
Have you checked your key binds?

**Comment by riley202010** [comment]
> Have you checked your key binds?

i will have a look  but i have looked so may times
 and its the same so
