### ISSUE TITLE
Stingers not functioning on FivePD vehicles

### ISSUE THREAD

**Issue by pwatts67** [LondonsBlueLine/tracker#668]
### What division were you running as?

RTPC

### Describe the Bug

its not exactly a bug but MPS 255 needs the fivpd stinger added to it because the one out the bott doesnt work but the fivepd one always works
it also needs the ANPR script added to it

### Expected Behavior

be able to grab it out your boot

**Comment by pwatts67** [comment]
and the ANPR added to it

**Comment by CalLBLRP** [comment]
Hiya, 

Quick update for you. 

- [ ] ANPR Added 
- [ ] Stinger Added (assigned to @WolfRanger88)

**Comment by jxckUK** [comment]
> * [ ]  Stinger Added (assigned to @WolfRanger88)

@CalLBLRP - Stingers are controlled via PH-MPS and are in all cars as long as the player is within RTPC. Can we close this?
