### ISSUE TITLE
[FEAT] SFC Request 

### ISSUE THREAD

**Issue by CalLBLRP** [LondonsBlueLine/tracker#67]
Is there any chance of getting the Targets added to a separate menu under the objects menu perhaps and get the Targets that are in the kill house at the airport into a menu that can be placed by SFC members. Rules will be put in place of course regarding this. 

Also, is there any chance of getting the kill house moved to the military base and the vehicle training obstacle too to the airport due to the planes that like to land when doing training are very annoying and it interrupts the session.

**Comment by jxckUK** [comment]
Yes this is possible - my ideal scenario is creating our own scene menu but thats a few roadmap items away to be honest.

In the meantime maybe @WolfRanger88 can look at adding this into the existing menu?
