### ISSUE TITLE
LFB engines

### ISSUE THREAD

**Issue by pwatts67** [LondonsBlueLine/tracker#687]
### What division were you running as?

LFB

### Describe the Bug

LFB44 and LFB45 need BA,turnout and hose added to it

### Expected Behavior

be able to get it of the appliance

### To Reproduce

add the script to it

**Comment by colossalengineer** [comment]
This is something you will need to as Ryan as he is the one who request the equipment on the vehicles

**Comment by pwatts67** [comment]
so i need to ask ryan for it?

**Comment by CalLBLRP** [comment]
Correct.

**Comment by Firemanryan** [comment]
how? i dont have access to the configs, the list was created months ago!

**Comment by pwatts67** [comment]
so colossal needs to add it basically

**Comment by CalLBLRP** [comment]
Yes. However, he is currently away from dev work this week due to other commitments.
