### ISSUE TITLE
[BUG] Helimed Detection

### ISSUE THREAD

**Issue by telboycafc** [LondonsBlueLine/tracker#69]
Helimed is not useable. Have to go right to the back of the hit box to get the stretcher out. Can't get the stretcher back in now. It will not prompt to put stretcher in vehicle, making it not use able at the moment. Seems to have got worse.

**Comment by jxckUK** [comment]
https://github.com/ProjectHyde/ProjectHyde/commit/c9fbba71dcb215d42218893ed1083412e1632688 - Wolf updated detection rate.
