### ISSUE TITLE
Additional forces

### ISSUE THREAD

**Issue by joatway13** [LondonsBlueLine/tracker#75]
Hi This is for the future suggestion,
Is there a possibility that there would be a job for Trashman/Binman/Operative within the server. I can give some help/information towards this suggestion as I have IRL experience.
Please keep me updated
J. Oatway

**Comment by jxckUK** [comment]
Hi @joatway13,

I have thought a little on the topic and here is my current stance:

The server (at least from a development perspective) is focused on emergency services. Our roadmap is long and jam packed with things we want to accomplish and I can't see an opening for something that isn't our core focus.

This isn't a never, it's just a not in the immediate horizon and as such I'm going to close it out.

Cheers,

Jack
