### ISSUE TITLE
[FEAT] new custody suite

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#81]
There is a new custody suite available from Mirror park studios which looks good and could be useful to do more custody style to scenarios don't have link at moment but when I do I will add it

**Comment by Kyymather** [comment]
https://mirror-park-studios.tebex.io/package/4987551

**Comment by Dale1987** [comment]
This is something to look at in future as its quite an expensive purchase and we have other items that are higher on our priority list at the moment.

**Comment by jxckUK** [comment]
> This is something to look at in future as its quite an expensive purchase and we have other items that are higher on our priority list at the moment.

I agree, the other issue I see is that this is exclusively a custody suite and our focus at the moment is to bring more full station locations to the game.
