### ISSUE TITLE
Additional garages

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#82]
_## Issue created anonymously for a user ##_
Add unmarked bike and tac ops vehicles to rtpc and maybe some fancy SP.C cars awell

**Comment by Dale1987** [comment]
S.pc already have a garage with a vehicle in, RTPC dont use unmarked bikes, tac ops is not something im wanting to spend hours skinning cars for as RTPC already has enough sub divisions

**Comment by jxckUK** [comment]
> S.pc already have a garage with a vehicle in, RTPC dont use unmarked bikes, tac ops is not something im wanting to spend hours skinning cars for as RTPC already has enough sub divisions

I agree with this for the most part - we can certainly add a couple for S.PC vehicles once we have some spare that are appropriate.

**Comment by Dale1987** [comment]
new S.PC vehicle added
