### ISSUE TITLE
Adding additional vests / replacing existing ones

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#85]
_## Issue created anonymously for a user ##_
https://sinnersmodshop.com/products/hertfordshire-police-response-vest-eup-model?_pos=23&_sid=6596838e6&_ss=r

Stunning hi vis vest compared to one we have now

**Comment by Dale1987** [comment]
I like this vest could be good for RTPC units

**Comment by JamStonedScones** [comment]
100% agree, would love these vests for my units

**Comment by telboycafc** [comment]
Vest has been purchased thanks to a donator. Awaiting decryption key to download from sinners.
