### ISSUE TITLE
Additional LAS props and vehicles

### ISSUE THREAD

**Issue by Kyymather** [LondonsBlueLine/tracker#92]
Here are some props that I think would be good for LAS sorry for the long suggestion 

Wheelchair- For when LAS transfer someone to hospital that doesn't need a stretcher they can grab one have done two links as there is two versions 
Link 1: 
https://forum.cfx.re/t/release-qalle-wheelchair-wheelchair-for-ems-standalone/196625/112
Link 2:
https://www.gta5-mods.com/vehicles/wheelchair-add-on-sp-fivem

Backpack/kit- can be used in RP to make it look like LAS have equipment with them again two links for different items the second one has a police option that can be use for SFC as they are trained in advanced first aid
Link 1: 
https://store.state-zero.com/products/emas-backpack?_pos=1&_sid=bd9ab4bd0&_ss=r
Link 2:
https://store.state-zero.com/products/ems-kit 

New ambulance with enterable interior 
Link:https://store.state-zero.com/products/2017-sprinter-generic-was-ambulance

**Comment by jxckUK** [comment]
Wheelchair has been something @telboycafc has wanted to add for a while. In regards to the additional props I certainly think that'll help but we have a limited allocation of funding for things like this so it will be down to a priority list. Same with the additional ambulance.

**Comment by telboycafc** [comment]
We have a wheel chair that is useable. Maybe jack can look in to it more in terms of being able to have the option of getting it in and out of a vehicle.

**Comment by jxckUK** [comment]
> LAS bag purchased, any update about wheelchair?

Wheelchair is in and has been for a while I think, /wheelchair

**Comment by Dale1987** [comment]
Yeah ended up testing last night.

**Comment by jxckUK** [comment]
Closing this out as the additional equipment is part of PH-LAS V2. 

https://github.com/ProjectHyde/ProjectHyde/issues/29
