### ISSUE TITLE
Medical bag

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#96]
_## Issue created anonymously for a user ##_
Being able to go up to any ARV, when you open the boot you're welcomed with the weapons and equipment etc, but also with a "BELS Bag". When you click the option, it performs an animation and puts the bag on your back. To drop it on the floor for roleplay, there could be a /belsdrop /belsup or even a keybind.

astronOMY.#0001

https://www.unionmods.com/?p=viewfile&file=567

**Comment by Dale1987** [comment]
This is a model to use in vehicles and not a prop
