### ISSUE TITLE
Moderation request - discord & fivem intergration

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#98]
_## Issue created anonymously for a user ##_
Either F5 or F6 menu, or somewhere else that you are able to press a section to be able to request a moderator, possibly asking the person for a reason and the player (can make that optional) and it gets sent to a channel in #moderator and tags @Game Moderator, allowing mods to be notified when people are being little shits.

Went hand in hand with the "no nametags above heads" conversation.

**Comment by CalLBLRP** [comment]
+1 only: 

A cooldown is set to prevent spam and constant harassment towards Game Moderators.

**Comment by jxckUK** [comment]
Closed in favour of roadmap item: https://github.com/ProjectHyde/ProjectHyde/issues/60
